### ISSUE TITLE
Thread 'tokio-runtime-worker-3' panicked at 'internal error: entered unreachable code

### ISSUE THREAD

**Issue by xuqzab** [paritytech/polkadot#106]
emielvanderhoek/substrate-alexander:v0.3.2  docker image

Docker container crashed with following output to terminal.  Restarting the container resulted in immediate crash (upon connecting with alexander peers) with same output, same banned peer and error message.  The container was running on a fairly high end laptop with ubuntu 18.04 os.  Ironically the same docker image running on two older laptops (one positively ancient), on the same home network, have not crashed but one is stuck at block 200,968 while the other is keeping up at block 201,420 currently.  Terminal output on both running nodes shows frequent banned peer messages.  My network has been exhibiting higher than usual latency intermittently (thank you Xfinity).

2019-01-23 19:34:14 Banned PeerId(QmXnBNEYRJQqx5HeGfFyvs3UvTraQHEqHKEsVukyvt8YRU) (#44)
2019-01-23 19:34:14 Purposefully dropping 44 ; reason: Bad("Unexpected response packet received from peer")
2019-01-23 19:34:14 Banned PeerId(QmXnBNEYRJQqx5HeGfFyvs3UvTraQHEqHKEsVukyvt8YRU) (#44)
2019-01-23 19:34:14 Purposefully dropping 44 ; reason: Bad("Unexpected response packet received from peer")
2019-01-23 19:34:14 Banned PeerId(QmXnBNEYRJQqx5HeGfFyvs3UvTraQHEqHKEsVukyvt8YRU) (#44)

====================

stack backtrace:
   0:     0x56084fb97aad - backtrace::backtrace::trace::h1248f0dc5c279727
   1:     0x56084fb96bd2 - <backtrace::capture::Backtrace as core::default::Default>::default::hc9a8e6a2a06dfa11
   2:     0x56084f3cf3f8 - substrate_cli::panic_hook::panic_hook::hdbeae637bff12cb8
   3:     0x56084f3cf0f8 - core::ops::function::Fn::call::h7c1eb9b6bfa49438
   4:     0x56084fc9eaf9 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be
                        at src/libstd/panicking.rs:495
   5:     0x56084fc9e5a1 - std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1
                        at src/libstd/panicking.rs:398
   6:     0x56084fc9e4ee - std::panicking::begin_panic_fmt::h11fdc4cc73917110
                        at src/libstd/panicking.rs:353
   7:     0x56084f125f92 - <substrate_finality_grandpa::Environment<B, E, Block, N, RA> as finality_grandpa::Chain<<Block as sr_primitives::traits::Block>::Hash, <<Block as sr_primitives::traits::Block>::Header as sr_primitives::traits::Header>::Number>>::best_chain_containing::hb6426ebf50730bfb
   8:     0x56084f1a3043 - <finality_grandpa::voter::VotingRound<H, N, E>>::poll::hff2953c01b4eb618
   9:     0x56084f1b2155 - <finality_grandpa::voter::Voter<H, N, E, CommitIn, CommitOut>>::process_best_round::h2d85027424e7ce17
  10:     0x56084f1648ff - <finality_grandpa::voter::Voter<H, N, E, CommitIn, CommitOut> as futures::future::Future>::poll::h47d17f9cb7f395de
  11:     0x56084f156e54 - <futures::future::select2::Select2<A, B> as futures::future::Future>::poll::hb4fe18efaefbd6ae
  12:     0x56084ef57763 - <futures::future::chain::Chain<A, B, C>>::poll::hdd55b4b035c6404b
  13:     0x56084ef9eaf6 - <futures::future::loop_fn::LoopFn<A, F> as futures::future::Future>::poll::hdaaca68947fc3932
  14:     0x56084f225deb - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h121f6c2ea4aa2ffc
  15:     0x56084f27b55e - <futures::future::select::Select<A, B> as futures::future::Future>::poll::h46a22d0adbf3aef8
  16:     0x56084ef51c71 - <futures::future::chain::Chain<A, B, C>>::poll::ha0928f3c38ba4526
  17:     0x56084fc683c1 - futures::task_impl::std::set::h4e650e554073e01e
  18:     0x56084fc69cc5 - <futures::task_impl::Spawn<T>>::poll_future_notify::he7d23a198d713520
  19:     0x56084fc6d170 - std::panicking::try::do_call::h9c843760c3feda6a
  20:     0x56084fcaf759 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  21:     0x56084fc6aefb - tokio_threadpool::task::Task::run::h54015314b7848e6d
  22:     0x56084fc64955 - tokio_threadpool::worker::Worker::run_task::hdeaf9d053ebc9b85
  23:     0x56084fc63ffe - tokio_threadpool::worker::Worker::run::h4cae410655bc13ff
  24:     0x56084fc4ae66 - <std::thread::local::LocalKey<T>>::with::he0d6480a2d44d226
  25:     0x56084fc4aa27 - <std::thread::local::LocalKey<T>>::with::h085d3aeedcd83eaa
  26:     0x56084fc4acb1 - <std::thread::local::LocalKey<T>>::with::ha479ba99e96b54e0
  27:     0x56084fc44cb9 - tokio::runtime::builder::Builder::build::{{closure}}::h8dd564ad5c95d76b
  28:     0x56084fc6b772 - <std::thread::local::LocalKey<T>>::with::h770463a77b89b22b
  29:     0x56084fc6b289 - <std::thread::local::LocalKey<T>>::with::h1dd785a094acf76e
  30:     0x56084fc6cd17 - std::sys_common::backtrace::__rust_begin_short_backtrace::h530c2e1673231280
  31:     0x56084fc6d12b - std::panicking::try::do_call::h325fb79c9c3b76f7
  32:     0x56084fcaf759 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  33:     0x56084fc6ee5f - <F as alloc::boxed::FnBox<A>>::call_box::hc0bbd07e08d7bbc2
  34:     0x56084fca333d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
                         - std::sys_common::thread::start_thread::h9605a7df0f911844
                        at src/libstd/sys_common/thread.rs:24
                         - std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
                        at src/libstd/sys/unix/thread.rs:90
  35:     0x7fa016a926b9 - start_thread
  36:     0x7fa0165b241c - clone
  37:                0x0 - <unknown>

Thread 'tokio-runtime-worker-3' panicked at 'internal error: entered unreachable code: this is a bug. `target_hash` is in blockchain but wasn't found following all leaves backwards', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/e920bd2/core/client/src/client.rs:963

This is a bug. Please report it at:

    https://github.com/paritytech/polkadot/issues/new

**Comment by xuqzab** [comment]
Sorry, see that polkadot is up to 0.3.4, this issue was on 0.3.2
