### ISSUE TITLE
[not sure if bug] Unable to start polkadot with --validator

### ISSUE THREAD

**Issue by gregorst3** [paritytech/polkadot#110]
Hi, in the recent days i was stuck at X height;
If i tried to launch polkadot with `polkadot` the process was starting but still not syncing,
If I tried to launch polkadot with `polkadot --name X --validator --key X`
it returned this error after it started to sync new blocks.
```
====================

stack backtrace:
   0:     0x5636c290b37d - backtrace::backtrace::trace::h544964ff9f0fac62
   1:     0x5636c290a4a2 - <backtrace::capture::Backtrace as core::default::Defa                                                                                                             ult>::default::he75e8a7c41cf8eac
   2:     0x5636c21052f8 - substrate_cli::panic_hook::panic_hook::h97897d72ee5ad                                                                                                             86c
   3:     0x5636c2104ff8 - core::ops::function::Fn::call::h9415fae6b943d4e7
   4:     0x5636c2a12429 - std::panicking::rust_panic_with_hook::h8cbdfe43764887                                                                                                             be
                        at src/libstd/panicking.rs:495
   5:     0x5636c2a11ed1 - std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1
                        at src/libstd/panicking.rs:398
   6:     0x5636c2a11db5 - rust_begin_unwind
                        at src/libstd/panicking.rs:325
   7:     0x5636c2a29d8c - core::panicking::panic_fmt::h4d67173bc68f6d5a
                        at src/libcore/panicking.rs:95
   8:     0x5636c2a29e02 - core::option::expect_failed::h2f881c519f1d8001
                        at src/libcore/option.rs:1008
   9:     0x5636c1d5ec8c - <substrate_finality_grandpa::Environment<B, E, Block,                                                                                                              N, RA> as finality_grandpa::Chain<<Block as sr_primitives::traits::Block>::Hash                                                                                                             , <<Block as sr_primitives::traits::Block>::Header as sr_primitives::traits::Hea                                                                                                             der>::Number>>::best_chain_containing::h1e5aab70ab653424
  10:     0x5636c1e3b226 - <finality_grandpa::voter::VotingRound<H, N, E>>::poll                                                                                                             ::h9701079af1cfada9
  11:     0x5636c1e54fc5 - <finality_grandpa::voter::Voter<H, N, E, CommitIn, Co                                                                                                             mmitOut>>::process_best_round::h878079f386c78991
  12:     0x5636c1e1bcff - <finality_grandpa::voter::Voter<H, N, E, CommitIn, Co                                                                                                             mmitOut> as futures::future::Future>::poll::h313c45dd58c29183
  13:     0x5636c1d89050 - <futures::future::select2::Select2<A, B> as futures::                                                                                                             future::Future>::poll::he2187d064aea0db1
  14:     0x5636c1fdc683 - <futures::future::chain::Chain<A, B, C>>::poll::h134d                                                                                                             e306032d3f61
  15:     0x5636c1c08e06 - <futures::future::loop_fn::LoopFn<A, F> as futures::f                                                                                                             uture::Future>::poll::h1ed4a29fcadd4da9
  16:     0x5636c1ff3547 - <futures::future::join::Join<A, B> as futures::future                                                                                                             ::Future>::poll::h3b65d4afc50a54be
  17:     0x5636c1ec1239 - <futures::future::select::Select<A, B> as futures::fu                                                                                                             ture::Future>::poll::h6dfe7b6f7fc75a6f
  18:     0x5636c1fe9751 - <futures::future::chain::Chain<A, B, C>>::poll::ha962                                                                                                             b7741e07b50f
  19:     0x5636c29dbce1 - futures::task_impl::std::set::ha675998835d9777e

Gregorst, [22.01.19 21:38]

  20:     0x5636c29dd5e5 - <futures::task_impl::Spawn<T>>::poll_future_notify::h                                                                                                             f56f5259b11d209f
  21:     0x5636c29e0a90 - std::panicking::try::do_call::h3e2dc8917104e71c
  22:     0x5636c2a23089 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  23:     0x5636c29de81b - tokio_threadpool::task::Task::run::h9855397de4f00f81
  24:     0x5636c29d8275 - tokio_threadpool::worker::Worker::run_task::h1da4ec4c                                                                                                             3810b26a
  25:     0x5636c29d791e - tokio_threadpool::worker::Worker::run::hfa53eb1e4f72e                                                                                                             585
  26:     0x5636c29be466 - <std::thread::local::LocalKey<T>>::with::h26c07fb6016                                                                                                             527e8
  27:     0x5636c29be347 - <std::thread::local::LocalKey<T>>::with::h08191b9fffd                                                                                                             c4f3d
  28:     0x5636c29be651 - <std::thread::local::LocalKey<T>>::with::h36347f1e44b                                                                                                             69600
  29:     0x5636c29b85d9 - tokio::runtime::builder::Builder::build::{{closure}}:                                                                                                             :hbd376883e27277f8
  30:     0x5636c29dee52 - <std::thread::local::LocalKey<T>>::with::h2713c564c73                                                                                                             e54ca
  31:     0x5636c29df0b9 - <std::thread::local::LocalKey<T>>::with::hadef08c65db                                                                                                             6f195
  32:     0x5636c29e0637 - std::sys_common::backtrace::__rust_begin_short_backtr                                                                                                             ace::h0518f89ec5981bad
  33:     0x5636c29e0a4b - std::panicking::try::do_call::h05819a532c24c309
  34:     0x5636c2a23089 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  35:     0x5636c29e277f - <F as alloc::boxed::FnBox<A>>::call_box::h699e6129d11                                                                                                             aa145
  36:     0x5636c2a16c6d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output                                                                                                             =R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/l                                                                                                             iballoc/boxed.rs:683
                         - std::sys_common::thread::start_thread::h9605a7df0f911                                                                                                             844
                        at src/libstd/sys_common/thread.rs:24
                         - std::sys::unix::thread::Thread::new::thread_start::hc                                                                                                             a8e72c41fa9d291
                        at src/libstd/sys/unix/thread.rs:90
  37:     0x7f963f9d16f9 - start_thread
  38:     0x7f963f4f1b5c - clone
  39:                0x0 - <unknown>

Thread 'tokio-runtime-worker-1' panicked at 'Header known to exist after `best_c                                                                                                             ontaining` call; qed', src/libcore/option.rs:1008

This is a bug. Please report it at:

    https://github.com/paritytech/polkadot/issues/new
```
Purging the chain fixed this

**Comment by gregorst3** [comment]
I don’t remember if I was experiencing this in the previous version, nor if this was fixed

**Comment by rphmeier** [comment]
Try v0.3.8 with a fresh DB -- this should be fixed after recent substrate fixes.
