### ISSUE TITLE
panicked at 'Signature verification failed.', /build/runtime/kusama/src/lib.rs:1:1

### ISSUE THREAD

**Issue by past2017** [paritytech/polkadot#1106]
when kill polkadot process by kill PID
some error in log, version is 0.7.33 in ubuntu
```
2020-05-17 02:26:52 ⚙️  Syncing  0.0 bps, target=#2340896 (25 peers), best: #2305988 (0x0c2a…38b0), finalized #2305536 (0x629d…4c38), ⬇ 5.0kiB/s ⬆ 1.4kiB/s
2020-05-17 02:26:58 ⚙️  Syncing  0.0 bps, target=#2340897 (25 peers), best: #2305988 (0x0c2a…38b0), finalized #2305536 (0x629d…4c38), ⬇ 4.5kiB/s ⬆ 2.6kiB/s
2020-05-17 02:31:02 Haven't received async result from verification task. Returning false.
2020-05-17 02:31:02 panicked at 'Signature verification failed.', /build/runtime/kusama/src/lib.rs:1:1
2020-05-17 02:31:05 Block prepare storage changes error:
Execution(Wasmi(Trap(Trap { kind: Unreachable })))
```

**Comment by bkchr** [comment]
So you have seen this error when killing polkadot? This is absolutely fine.

**Comment by past2017** [comment]
> So you have seen this error when killing polkadot? This is absolutely fine.

yes, i want to restart polkadot process and so I get the polkadot's PID and kill this PID
but even after ten minutes polkadot process is still alive
and then I found this issue in his log

**Comment by bkchr** [comment]
Force killing should be okay, but it should respect `kill`.
