### ISSUE TITLE
polkadot raise an error on Ctrl-C

### ISSUE THREAD

**Issue by jasl** [paritytech/polkadot#1249]
polkadot 0.8.7 binary from GitHub releases page

I'm using this shell script

```
#!/bin/bash

WORK_PATH=$(dirname $(readlink -f "$0"))
NODE_NAME="my-kusama-validator-1"
CHAIN_NAME="kusama"

$WORK_PATH/polkadot \
  --chain $CHAIN_NAME \
  --base-path $WORK_PATH \
  --database paritydb \
  --wasm-execution Compiled \
  --name $NODE_NAME \
  --pruning=archive \
  "$@"
```

syncing blocks, then I type `Ctrl-C` to quit `polkadot` then I see

```
...
2020-06-11 15:50:10 ⚙️  Syncing 187.6 bps, target=#2702685 (27 peers), best: #2064960 (0xa756…2dfb), finalized #2064896 (0x962d…5123), ⬇ 126.5kiB/s ⬆ 3.4kiB/s
^C
====================

Version: 0.8.7-3b3020c6-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:515
   2: rust_begin_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:419
   3: core::panicking::panic_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/panicking.rs:111
   4: core::option::expect_failed
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/option.rs:1260
   5: futures_channel::mpsc::UnboundedReceiver<T>::next_message
   6: <futures_channel::mpsc::UnboundedReceiver<T> as futures_core::stream::Stream>::poll_next
   7: <sc_network::service::out_events::Receiver as futures_core::stream::Stream>::poll_next
   8: futures_util::future::future::FutureExt::now_or_never
   9: <sc_network::service::out_events::Receiver as core::ops::drop::Drop>::drop
  10: core::ptr::drop_in_place
  11: core::ptr::drop_in_place
  12: alloc::sync::Arc<T>::drop_slow
  13: core::ptr::drop_in_place
  14: core::ptr::drop_in_place
  15: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  16: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  17: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  18: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  19: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  22: tokio::runtime::task::raw::poll
  23: std::thread::local::LocalKey<T>::with
  24: tokio::runtime::thread_pool::worker::Context::run_task
  25: tokio::runtime::thread_pool::worker::Context::run
  26: tokio::macros::scoped_tls::ScopedKey<T>::set
  27: tokio::runtime::thread_pool::worker::run
  28: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  29: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  30: tokio::runtime::task::raw::poll
  31: tokio::runtime::blocking::pool::Inner::run
  32: tokio::runtime::context::enter
  33: std::sys_common::backtrace::__rust_begin_short_backtrace
  34: core::ops::function::FnOnce::call_once{{vtable.shim}}
  35: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/sys/unix/thread.rs:87
  36: start_thread
  37: clone


Thread 'tokio-runtime-worker' panicked at 'Receiver::next_message called after `None`', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.5/src/mpsc/mod.rs:1141

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
```

**Comment by bkchr** [comment]
Should be fixed by https://github.com/paritytech/substrate/pull/6458
