### ISSUE TITLE
polkadot 0.8.7 raise an error on running 

### ISSUE THREAD

**Issue by jasl** [paritytech/polkadot#1254]
polkadot 0.8.7 from GitHub binary release
ubuntu 20.04
 
```
2020-06-12 12:24:35 💸 new validator set of size 350 has been elected via ElectionCompute::Unsigned for era 905
2020-06-12 12:24:38 💤 Idle (24 peers), best: #2714441 (0x28c0…ef06), finalized #2714364 (0x6f60…a223), ⬇ 9.3kiB/s ⬆ 5.4kiB/s
2020-06-12 12:24:40 ✨ Imported #2714922 (0xef9c…382c)
2020-06-12 12:24:40 ✨ Imported #2714923 (0xed4f…16d8)
2020-06-12 12:24:40 ✨ Imported #2714923 (0x76ac…8b21)
2020-06-12 12:24:43 ✨ Imported #2714924 (0xab80…daa3)
2020-06-12 12:24:43 💤 Idle (24 peers), best: #2714924 (0xab80…daa3), finalized #2714921 (0xb1ed…42e9), ⬇ 239.1kiB/s ⬆ 52.5kiB/s
2020-06-12 12:24:48 💤 Idle (24 peers), best: #2714924 (0xab80…daa3), finalized #2714921 (0xb1ed…42e9), ⬇ 76.4kiB/s ⬆ 3.7kiB/s
2020-06-12 12:24:50 ✨ Imported #2714925 (0xc698…3461)
2020-06-12 12:24:53 💤 Idle (24 peers), best: #2714925 (0xc698…3461), finalized #2714923 (0xed4f…16d8), ⬇ 199.6kiB/s ⬆ 625.5kiB/s
2020-06-12 12:24:54 ✨ Imported #2714926 (0xb453…e687)
2020-06-12 12:24:58 💤 Idle (24 peers), best: #2714926 (0xb453…e687), finalized #2714923 (0xed4f…16d8), ⬇ 102.3kiB/s ⬆ 40.1kiB/s
2020-06-12 12:25:01 ✨ Imported #2714927 (0xa82d…52ef)
2020-06-12 12:25:02 ♻️  Reorg on #2714927,0xa82d…52ef to #2714927,0x26c7…25f5, common ancestor #2714926,0xb453…e687
2020-06-12 12:25:02 ✨ Imported #2714927 (0x26c7…25f5)
2020-06-12 12:25:03 💤 Idle (24 peers), best: #2714927 (0x26c7…25f5), finalized #2714924 (0xab80…daa3), ⬇ 209.3kiB/s ⬆ 376.1kiB/s
2020-06-12 12:25:07 ✨ Imported #2714928 (0xef22…d082)
2020-06-12 12:25:08 💤 Idle (24 peers), best: #2714928 (0xef22…d082), finalized #2714925 (0xc698…3461), ⬇ 104.2kiB/s ⬆ 121.9kiB/s
2020-06-12 12:25:13 ✨ Imported #2714929 (0x10e2…5b6a)
2020-06-12 12:25:13 💤 Idle (24 peers), best: #2714929 (0x10e2…5b6a), finalized #2714926 (0xb453…e687), ⬇ 247.0kiB/s ⬆ 126.3kiB/s
2020-06-12 12:25:18 💤 Idle (25 peers), best: #2714929 (0x10e2…5b6a), finalized #2714926 (0xb453…e687), ⬇ 71.1kiB/s ⬆ 4.7kiB/s
2020-06-12 12:25:19 Background worker error: Corruption: Bad log entry type

====================

Version: 0.8.7-3b3020c6-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:515
   2: rust_begin_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:419
   3: std::panicking::begin_panic_fmt
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:373
   4: <sc_client_db::parity_db::DbAdapter as sp_database::Database<H>>::commit
   5: sc_client_db::Backend<Block>::try_commit_operation
   6: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::commit_operation
   7: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
   8: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
   9: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  10: sp_consensus::import_queue::import_single_block_metered
  11: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  12: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  13: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
  14: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  15: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  16: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: std::thread::local::LocalKey<T>::with
  19: futures_executor::local_pool::block_on
  20: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  21: std::panicking::try
  22: tokio::runtime::task::raw::poll
  23: tokio::runtime::blocking::pool::Inner::run
  24: tokio::runtime::context::enter
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/sys/unix/thread.rs:87
  28: start_thread
  29: clone


Thread 'tokio-runtime-worker' panicked at 'Critical database error: Background(Corruption("Bad log entry type"))', /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/macros.rs:16

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
```

**Comment by bkchr** [comment]
CC @arkpar

**Comment by jasl** [comment]
UPDATE: the datebase has corrupted, restart polkadot will output like

![image](https://user-images.githubusercontent.com/1024162/84514306-61754480-acfd-11ea-8d87-f428fe9b6a9d.png)

but sorry I misoperation that deleted the instance

**Comment by arkpar** [comment]
If this happens again please send us files `log0`, `log1` and `log2` located in `<db dir>/chains/kusama/paritydb/`
