### ISSUE TITLE
Polkadot raise error on `Ctrl-C`

### ISSUE THREAD

**Issue by jasl** [paritytech/polkadot#1300]
Use `0.8.11` binary release

```
2020-06-21 08:59:57 Parity Polkadot
2020-06-21 08:59:57 ✌️  version 0.8.11-fb66e42f-x86_64-linux-gnu
2020-06-21 08:59:57 ❤️  by Parity Technologies <admin@parity.io>, 2017-2020
2020-06-21 08:59:57 📋 Chain specification: Polkadot CC1
2020-06-21 08:59:57 🏷  Node name: iosg-polkadot-sentry-3
2020-06-21 08:59:57 👤 Role: SENTRY
2020-06-21 08:59:57 💾 Database: ParityDb at /data/polkadot/chains/polkadot/paritydb
2020-06-21 08:59:57 ⛓  Native runtime: polkadot-11 (parity-polkadot-0.tx0.au0)
2020-06-21 09:00:03 📦 Highest known block at #369768
2020-06-21 09:00:03 🏷  Local node identity is: 12D3KooWQnRUgeZztCduXxRswZLWc3arQVRp78BDKoxoFB5mpQsq (legacy representation: QmR1AfPEYdQfacGJNihoBKy12AtigknoU3Dx1uH5zNYr23)
2020-06-21 09:00:03 〽️ Prometheus server started at 127.0.0.1:9615
2020-06-21 09:00:03 🔍 Discovered new external address for our node: /ip4/35.207.118.63/tcp/30333/p2p/12D3KooWQnRUgeZztCduXxRswZLWc3arQVRp78BDKoxoFB5mpQsq
2020-06-21 09:00:03 🔍 Discovered new external address for our node: /ip4/10.0.1.173/tcp/30333/p2p/12D3KooWQnRUgeZztCduXxRswZLWc3arQVRp78BDKoxoFB5mpQsq
2020-06-21 09:00:04 🔍 Discovered new external address for our node: /ip4/10.0.0.162/tcp/30333/p2p/12D3KooWQnRUgeZztCduXxRswZLWc3arQVRp78BDKoxoFB5mpQsq
2020-06-21 09:00:08 💤 Idle (11 peers), best: #369776 (0xcd34…6171), finalized #369765 (0x1d0f…75ab), ⬇ 68.1kiB/s ⬆ 20.3kiB/s
2020-06-21 09:00:13 💤 Idle (15 peers), best: #369808 (0x0b20…fd47), finalized #369765 (0x1d0f…75ab), ⬇ 42.0kiB/s ⬆ 24.2kiB/s
2020-06-21 09:00:18 💤 Idle (19 peers), best: #369813 (0x32e0…c1e8), finalized #369765 (0x1d0f…75ab), ⬇ 71.4kiB/s ⬆ 48.2kiB/s
2020-06-21 09:00:18 🔍 Discovered new external address for our node: /ip4/10.156.1.51/tcp/30333/p2p/12D3KooWQnRUgeZztCduXxRswZLWc3arQVRp78BDKoxoFB5mpQsq
2020-06-21 09:00:20 🔍 Discovered new external address for our node: /ip4/10.156.1.48/tcp/30333/p2p/12D3KooWQnRUgeZztCduXxRswZLWc3arQVRp78BDKoxoFB5mpQsq
2020-06-21 09:00:20 🔍 Discovered new external address for our node: /ip4/10.0.1.29/tcp/30333/p2p/12D3KooWQnRUgeZztCduXxRswZLWc3arQVRp78BDKoxoFB5mpQsq
2020-06-21 09:00:23 💤 Idle (21 peers), best: #369844 (0xde58…c041), finalized #369765 (0x1d0f…75ab), ⬇ 63.0kiB/s ⬆ 47.4kiB/s
2020-06-21 09:00:27 🔍 Discovered new external address for our node: /ip4/10.156.1.56/tcp/30333/p2p/12D3KooWQnRUgeZztCduXxRswZLWc3arQVRp78BDKoxoFB5mpQsq
2020-06-21 09:00:28 💤 Idle (24 peers), best: #369892 (0xd321…f480), finalized #369765 (0x1d0f…75ab), ⬇ 65.4kiB/s ⬆ 40.8kiB/s
2020-06-21 09:00:33 💤 Idle (25 peers), best: #370021 (0xb616…ff7f), finalized #369765 (0x1d0f…75ab), ⬇ 39.0kiB/s ⬆ 22.8kiB/s
2020-06-21 09:00:35 ✨ Imported #370127 (0x3134…5285)
2020-06-21 09:00:35 ✨ Imported #370127 (0x8aee…ce42)
2020-06-21 09:00:35 ✨ Imported #370128 (0x161b…61d1)
2020-06-21 09:00:35 ✨ Imported #370129 (0x8f25…4c38)
2020-06-21 09:00:35 ✨ Imported #370130 (0x32f9…dab5)
2020-06-21 09:00:35 ✨ Imported #370131 (0x6d6f…eb83)
^C2020-06-21 09:00:35 Essential task `grandpa-voter` failed. Shutting down service.

====================

Version: 0.8.11-fb66e42f-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:515
   2: rust_begin_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:419
   3: core::panicking::panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/panicking.rs:111
   4: core::option::expect_failed
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/option.rs:1260
   5: futures_channel::mpsc::UnboundedReceiver<T>::next_message
   6: <futures_channel::mpsc::UnboundedReceiver<T> as futures_core::stream::Stream>::poll_next
   7: <sc_network::service::out_events::Receiver as futures_core::stream::Stream>::poll_next
   8: futures_util::future::future::FutureExt::now_or_never
   9: <sc_network::service::out_events::Receiver as core::ops::drop::Drop>::drop
  10: core::ptr::drop_in_place
  11: core::ptr::drop_in_place
  12: alloc::sync::Arc<T>::drop_slow
  13: core::ptr::drop_in_place
  14: core::ptr::drop_in_place
  15: core::ptr::drop_in_place
  16: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as core::ops::drop::Drop>::drop
  17: alloc::sync::Arc<T>::drop_slow
  18: alloc::sync::Arc<T>::drop_slow
  19: alloc::sync::Arc<T>::drop_slow
  20: alloc::sync::Arc<T>::drop_slow
  21: <hashbrown::raw::RawTable<T> as core::ops::drop::Drop>::drop
  22: alloc::sync::Arc<T>::drop_slow
  23: core::ptr::drop_in_place
  24: core::ptr::drop_in_place
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys/unix/thread.rs:87
  28: start_thread
  29: clone


Thread '<unnamed>' panicked at 'Receiver::next_message called after `None`', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.5/src/mpsc/mod.rs:1141

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
```

**Comment by bkchr** [comment]
Should be fixed now
