### ISSUE TITLE
panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1

### ISSUE THREAD

**Issue by jasl** [paritytech/polkadot#1323]
- Ubuntu 18.04 latest, 2 Core 8G memory
- 0.8.12
- Linux binary from GitHub releases page
- Kusama chain
- Sentry role

I'm upgrading my Kusama validator cluster from 0.8.7 to 0.8.12 by:

- stop polkadot
- replace old binary with 0.8.12
- start polkadot

Validator node looks work great after upgrade, but a sentry node looks weird

I see infinite output like this

```
...
2020-06-26 16:27:48 📞 Notifications queue with peer 12D3KooWCnHw9nfPxLvTybkiAUPbAFxoqcsLHGWHWkFLVMiBRMSx is full, dropped message (protocol: [47, 112, 97, 114, 105, 116, 121, 116, 101, 99, 104, 47, 103, 114, 97, 110, 100, 112, 97, 47, 49])
2020-06-26 16:27:48 📞 Notifications queue with peer 12D3KooWCnHw9nfPxLvTybkiAUPbAFxoqcsLHGWHWkFLVMiBRMSx is full, dropped message (protocol: [47, 112, 97, 114, 105, 116, 121, 116, 101, 99, 104, 47, 103, 114, 97, 110, 100, 112, 97, 47, 49])
2020-06-26 16:27:48 📞 Notifications queue with peer 12D3KooWCnHw9nfPxLvTybkiAUPbAFxoqcsLHGWHWkFLVMiBRMSx is full, dropped message (protocol: [47, 112, 97, 114, 105, 116, 121, 116, 101, 99, 104, 47, 103, 114, 97, 110, 100, 112, 97, 47, 49])
2020-06-26 16:27:48 📞 Notifications queue with peer 12D3KooWCnHw9nfPxLvTybkiAUPbAFxoqcsLHGWHWkFLVMiBRMSx is full, dropped message (protocol: [47, 112, 97, 114, 105, 116, 121, 116, 101, 99, 104, 47, 103, 114, 97, 110, 100, 112, 97, 47, 49])
2020-06-26 16:27:48 ✨ Imported #2917358 (0x7853…5494)
2020-06-26 16:27:48 💤 Idle (39 peers), best: #2917358 (0x7853…5494), finalized #2917355 (0x680a…a029), ⬇ 419.1kiB/s ⬆ 423.4kiB/s
2020-06-26 16:27:53 💤 Idle (38 peers), best: #2917358 (0x7853…5494), finalized #2917355 (0x680a…a029), ⬇ 476.1kiB/s ⬆ 284.4kiB/s
2020-06-26 16:27:55 📞 Notifications queue with peer 12D3KooWCnHw9nfPxLvTybkiAUPbAFxoqcsLHGWHWkFLVMiBRMSx is full, dropped message (protocol: [47, 112, 97, 114, 105, 116, 121, 116, 101, 99, 104, 47, 103, 114, 97, 110, 100, 112, 97, 47, 49])
2020-06-26 16:27:55 📞 Notifications queue with peer 12D3KooWCnHw9nfPxLvTybkiAUPbAFxoqcsLHGWHWkFLVMiBRMSx is full, dropped message (protocol: [47, 112, 97, 114, 105, 116, 121, 116, 101, 99, 104, 47, 103, 114, 97, 110, 100, 112, 97, 47, 49])
2020-06-26 16:27:55 📞 Notifications queue with peer 12D3KooWCnHw9nfPxLvTybkiAUPbAFxoqcsLHGWHWkFLVMiBRMSx is full, dropped message (protocol: [47, 112, 97, 114, 105, 116, 121, 116, 101, 99, 104, 47, 103, 114, 97, 110, 100, 112, 97, 47, 49])
...
```

`📞 Notifications queue with peer 12D3KooWCnHw9nfPxLvTybkiAUPbAFxoqcsLHGWHWkFLVMiBRMSx is full, dropped message (protocol: [47, 112, 97, 114, 105, 116, 121, 116, 101, 99, 104, 47, 103, 114, 97, 110, 100, 112, 97, 47, 49])` appeared about hundreds between every blocks.

I stop polkadot then restart, the output:

```
2020-06-26 16:28:50 ----------------------------
2020-06-26 16:28:50 This chain is not in any way
2020-06-26 16:28:50       endorsed by the
2020-06-26 16:28:50      KUSAMA FOUNDATION
2020-06-26 16:28:50 ----------------------------
2020-06-26 16:28:50 Parity Polkadot
2020-06-26 16:28:50 ✌️  version 0.8.12-03067290-x86_64-linux-gnu
2020-06-26 16:28:50 ❤️  by Parity Technologies <admin@parity.io>, 2017-2020
2020-06-26 16:28:50 📋 Chain specification: Kusama
2020-06-26 16:28:50 🏷  Node name: iosg-kusama-sentry-1
2020-06-26 16:28:50 👤 Role: SENTRY
2020-06-26 16:28:50 💾 Database: ParityDb at /data/kusama/chains/ksmcc3/paritydb
2020-06-26 16:28:50 ⛓  Native runtime: kusama-2012 (parity-kusama-0.tx1.au2)
2020-06-26 16:28:50 📦 Highest known block at #2917365
2020-06-26 16:28:50 🏷  Local node identity is: 12D3KooWCqsof9wiHJgc62nKz2a8gaP9PSyeKMi8jEcgLB93r5b4 (legacy representation: QmYTHPHZVUzk9hRSeeGzP2B7Jtm8GvowonjLvH2iR4uxUL)
2020-06-26 16:28:50 〽️ Prometheus server started at 127.0.0.1:9615
2020-06-26 16:28:51 🔍 Discovered new external address for our node: /ip4/10.172.0.13/tcp/30333/p2p/12D3KooWCqsof9wiHJgc62nKz2a8gaP9PSyeKMi8jEcgLB93r5b4
2020-06-26 16:28:51 🔍 Discovered new external address for our node: /ip4/34.65.147.45/tcp/30333/p2p/12D3KooWCqsof9wiHJgc62nKz2a8gaP9PSyeKMi8jEcgLB93r5b4
2020-06-26 16:28:51 🔍 Discovered new external address for our node: /ip4/10.0.1.29/tcp/30333/p2p/12D3KooWCqsof9wiHJgc62nKz2a8gaP9PSyeKMi8jEcgLB93r5b4
2020-06-26 16:28:54 ✨ Imported #2917367 (0x6367…5ccd)
2020-06-26 16:28:54 🔍 Discovered new external address for our node: /ip4/10.156.1.51/tcp/30333/p2p/12D3KooWCqsof9wiHJgc62nKz2a8gaP9PSyeKMi8jEcgLB93r5b4
2020-06-26 16:28:54 ✨ Imported #2917368 (0x64ba…a62e)
2020-06-26 16:28:55 💤 Idle (18 peers), best: #2917368 (0x64ba…a62e), finalized #2917365 (0x5d6c…7156), ⬇ 178.3kiB/s ⬆ 290.0kiB/s
2020-06-26 16:28:58 ✨ Imported #2917366 (0xd2a2…d7cf)
2020-06-26 16:28:59 ✨ Imported #2917367 (0x9fb7…e8d9)
2020-06-26 16:29:00 💤 Idle (19 peers), best: #2917368 (0x64ba…a62e), finalized #2917366 (0xdc5a…3777), ⬇ 272.0kiB/s ⬆ 309.2kiB/s
2020-06-26 16:29:01 ✨ Imported #2917369 (0xfaf7…63b1)
2020-06-26 16:29:01 panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1
2020-06-26 16:29:01 panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1
2020-06-26 16:29:01 panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1
2020-06-26 16:29:01 panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1
2020-06-26 16:29:01 panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1
2020-06-26 16:29:01 panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1
2020-06-26 16:29:01 panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1
2020-06-26 16:29:01 panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1
2020-06-26 16:29:01 panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1
2020-06-26 16:29:01 panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1
2020-06-26 16:29:02 🔍 Discovered new external address for our node: /ip4/10.3.2.2/tcp/30333/p2p/12D3KooWCqsof9wiHJgc62nKz2a8gaP9PSyeKMi8jEcgLB93r5b4
2020-06-26 16:29:05 💤 Idle (21 peers), best: #2917369 (0xfaf7…63b1), finalized #2917367 (0x6367…5ccd), ⬇ 342.0kiB/s ⬆ 341.8kiB/s
2020-06-26 16:29:07 ✨ Imported #2917370 (0xa96c…6dc0)
2020-06-26 16:29:10 💤 Idle (23 peers), best: #2917370 (0xa96c…6dc0), finalized #2917367 (0x6367…5ccd), ⬇ 223.3kiB/s ⬆ 264.1kiB/s
2020-06-26 16:29:13 ✨ Imported #2917371 (0x83de…784c)
2020-06-26 16:29:13 ✨ Imported #2917371 (0x236d…cb46)
2020-06-26 16:29:15 🔍 Discovered new external address for our node: /ip4/10.36.2.1/tcp/30333/p2p/12D3KooWCqsof9wiHJgc62nKz2a8gaP9PSyeKMi8jEcgLB93r5b4
2020-06-26 16:29:15 💤 Idle (24 peers), best: #2917371 (0x83de…784c), finalized #2917368 (0x64ba…a62e), ⬇ 206.5kiB/s ⬆ 369.1kiB/s
2020-06-26 16:29:19 ✨ Imported #2917372 (0x7d3a…c889)
2020-06-26 16:29:19 ✨ Imported #2917372 (0x395f…5192)
2020-06-26 16:29:20 💤 Idle (29 peers), best: #2917372 (0x7d3a…c889), finalized #2917369 (0xfaf7…63b1), ⬇ 215.1kiB/s ⬆ 301.7kiB/s
2020-06-26 16:29:25 ✨ Imported #2917373 (0x855f…cddc)
2020-06-26 16:29:25 💤 Idle (30 peers), best: #2917373 (0x855f…cddc), finalized #2917369 (0xfaf7…63b1), ⬇ 216.5kiB/s ⬆ 286.8kiB/s
2020-06-26 16:29:25 🔍 Discovered new external address for our node: /ip4/10.0.0.162/tcp/30333/p2p/12D3KooWCqsof9wiHJgc62nKz2a8gaP9PSyeKMi8jEcgLB93r5b4
2020-06-26 16:29:28 🔍 Discovered new external address for our node: /ip4/10.156.1.51/tcp/30333/p2p/12D3KooWCqsof9wiHJgc62nKz2a8gaP9PSyeKMi8jEcgLB93r5b4
2020-06-26 16:29:30 💤 Idle (31 peers), best: #2917373 (0x855f…cddc), finalized #2917371 (0x83de…784c), ⬇ 373.3kiB/s ⬆ 432.0kiB/s
```

Short times later, I look hundreds `📞 Notifications queue with peer 12D3KooWNaR72YQyv11xsGQZxZ6hgRGvrjbzaWvGgGxtkN6Fhcpk is full, dropped message (protocol: [47, 112, 97, 114, 105, 116, 121, 116, 101, 99, 104, 47, 103, 114, 97, 110, 100, 112, 97, 47, 49])` again.

Should I ignore these output?

BTW, the start sentry node command

```bash
#!/bin/bash

WORK_PATH=$(dirname $(readlink -f "$0"))
NODE_NAME="iosg-kusama-sentry-1"
CHAIN_NAME="kusama"
VALIDATOR_IDENTITY="/ip4/10.172.0.12/tcp/30333/p2p/12D3KooWQvpayA6JawfLYNftPPS87tJptQRATsAuaCFFe5b1GPLk"

$WORK_PATH/polkadot \
  --chain $CHAIN_NAME \
  --base-path $WORK_PATH \
  --database paritydb \
  --wasm-execution Compiled \
  --name $NODE_NAME \
  --sentry $VALIDATOR_IDENTITY \
  "$@"
```

**Comment by jasl** [comment]
I also curious about `/Users/gav/Core/polkadot/runtime/kusama/src/lib.rs` does the Linux binary compiled by Gavin's macOS?

**Comment by jasl** [comment]
I confirmed this only appear on 0.8.12 and sentry node only, validator looks normal

**Comment by bkchr** [comment]
That is totally fine. It just means that someone tried to send you some junk transaction.

**Comment by jasl** [comment]
> That is totally fine. It just means that someone tried to send you some junk transaction.

`panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/kusama/src/lib.rs:945:1`

This also normal? I'm curiors because it leaks compiler's env info

**Comment by bkchr** [comment]
This is a panic and you just see the location of the panicking code. This is totally normal.

**Comment by jasl** [comment]
> This is a panic and you just see the location of the panicking code. This is totally normal.

ok... thanks for clarification

**Comment by icodezjb** [comment]
I had a similar problem.
Using the wrong or outdated polkadot.js types via polkadot.js.org.
Resolved it by cleaning and configuring the correct type
