### ISSUE TITLE
Panic running a polkadot full node v0.8.13

### ISSUE THREAD

**Issue by ianhe8x** [paritytech/polkadot#1337]
Node is run in a gcp kube cluster, upgraded from v0.8.2. 
Full node with no extra cli except --base-path=somepath
After upgrade to v0.8.13, the node launched and panic twice. Though after that it runs with no error.

Here's all logs:
```
2020-07-02 03:24:14 Parity Polkadot
2020-07-02 03:24:14 ✌️  version 0.8.13-90d5dbe-x86_64-linux-gnu
2020-07-02 03:24:14 ❤️  by Parity Technologies <admin@parity.io>, 2017-2020
2020-07-02 03:24:14 📋 Chain specification: Polkadot CC1
2020-07-02 03:24:14 🏷  Node name: incompetent-clocks-6711
2020-07-02 03:24:14 👤 Role: FULL
2020-07-02 03:24:14 💾 Database: RocksDb at /chain-data/chains/polkadot/db
2020-07-02 03:24:14 ⛓  Native runtime: polkadot-13 (parity-polkadot-0.tx2.au0)
2020-07-02 03:24:15 📦 Highest known block at #521723
2020-07-02 03:24:15 🏷  Local node identity is: 12D3KooWEZQoUgmY9oXbKCQZoM6JeHFd9upsKj3qQb7MjZuVQV3u (legacy representation: QmTSGuVYsqXatbr2ZSH4ee7AHLAU6yLBADVx1iaKoXBAGk)
2020-07-02 03:24:15 〽️ Prometheus server started at 127.0.0.1:9615
2020-07-02 03:24:16 🔍 Discovered new external address for our node: /ip4/10.0.0.162/tcp/30333/p2p/12D3KooWEZQoUgmY9oXbKCQZoM6JeHFd9upsKj3qQb7MjZuVQV3u
2020-07-02 03:24:16 🔍 Discovered new external address for our node: /ip4/35.227.175.122/tcp/30333/p2p/12D3KooWEZQoUgmY9oXbKCQZoM6JeHFd9upsKj3qQb7MjZuVQV3u
2020-07-02 03:24:16 🔍 Discovered new external address for our node: /ip4/10.0.1.173/tcp/30333/p2p/12D3KooWEZQoUgmY9oXbKCQZoM6JeHFd9upsKj3qQb7MjZuVQV3u
2020-07-02 03:24:20 ⚙️  Syncing, target=#524091 (6 peers), best: #521754 (0x4711…772d), finalized #521728 (0x02d1…7057), ⬇ 159.0kiB/s ⬆ 10.6kiB/s
2020-07-02 03:24:25 💤 Idle (12 peers), best: #521856 (0xf4c5…7f2d), finalized #521728 (0x02d1…7057), ⬇ 117.1kiB/s ⬆ 14.5kiB/s

====================

Version: 0.8.13-90d5dbe-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:515
   2: std::panicking::begin_panic
   3: <slog_scope::NoGlobalLoggerSet as slog::Drain>::log
   4: std::thread::local::LocalKey<T>::with
   5: <sc_consensus_babe::BabeVerifier<Block,Client> as sp_consensus::import_queue::Verifier<Block>>::verify
   6: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   7: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
   8: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
   9: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  10: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: futures_executor::local_pool::block_on
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  14: tokio::runtime::task::core::Core<T,S>::poll
  15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  16: tokio::runtime::task::raw::poll
  17: tokio::runtime::blocking::pool::Inner::run
  18: tokio::runtime::context::enter
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
  20: core::ops::function::FnOnce::call_once{{vtable.shim}}
  21: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys/unix/thread.rs:87
  22: start_thread
  23: clone


Thread 'tokio-runtime-worker' panicked at 'slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.3.0/lib.rs:125

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
```

**Comment by bkchr** [comment]
Is this reproducible?

**Comment by ianhe8x** [comment]
it still happens from time to time. I can add some extra logs only if I know what it is.
