### ISSUE TITLE
request rpc(author_rotateKeys) failed

### ISSUE THREAD

**Issue by yaanhyy** [paritytech/polkadot#1487]
the log:

```
====================

Version: 0.8.13-90d5dbe-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:515
   2: rust_begin_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:419
   3: core::panicking::panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/panicking.rs:111
   4: core::option::expect_none_failed
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/option.rs:1268
   5: <&mut dyn sp_externalities::Externalities as sp_io::crypto::Crypto>::ed25519_generate_version_1
   6: sp_externalities::scope_limited::with_externalities
   7: sp_io::crypto::ed25519_generate_version_1
   8: <<sp_io::crypto::HostFunctions as sp_wasm_interface::HostFunctions>::host_functions::ExtCryptoEd25519GenerateVersion1 as sp_wasm_interface::Function>::execute
   9: <sc_executor_wasmi::FunctionExecutor as wasmi::host::Externals>::invoke_index
  10: wasmi::func::FuncInstance::invoke
  11: wasmi::runner::Interpreter::start_execution
  12: wasmi::func::FuncInstance::invoke
  13: <sc_executor_wasmi::WasmiInstance as sc_executor_common::wasm_runtime::WasmInstance>::call
  14: std::panic::catch_unwind
  15: std::thread::local::LocalKey<T>::with
  16: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  17: sc_executor::wasm_runtime::RuntimeCache::with_instance
  18: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  19: sp_state_machine::StateMachine<B,H,N,Exec>::execute_aux
  20: sp_state_machine::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  21: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  22: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  23: sp_session::runtime_decl_for_SessionKeys::generate_session_keys_call_api_at
  24: sp_session::SessionKeys::generate_session_keys
  25: <sc_rpc::author::Author<P,Client> as sc_rpc_api::author::rpc_impl_AuthorApi::gen_server::AuthorApi<<P as sp_transaction_pool::pool::TransactionPool>::Hash,<<P as sp_transaction_pool::pool::TransactionPool>::Block as sp_runtime::traits::Block>::Hash>>::rotate_keys
  26: <jsonrpc_core::delegates::DelegateAsyncMethod<T,F> as jsonrpc_core::calls::RpcMethod<M>>::call
  27: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  28: futures::future::chain::Chain<A,B,C>::poll
  29: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  30: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  31: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  32: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  33: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  34: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  35: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  36: <jsonrpc_http_server::handler::Handler<M,S> as futures::future::Future>::poll
  37: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  38: <hyper::server::conn::Connection<I,S,E> as futures::future::Future>::poll
  39: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  40: futures::future::chain::Chain<A,B,C>::poll
  41: futures::task_impl::std::set
  42: tokio_threadpool::task::Task::run
  43: tokio_threadpool::worker::Worker::run_task
  44: tokio_threadpool::worker::Worker::run
  45: tokio_timer::clock::clock::with_default
  46: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  47: std::thread::local::LocalKey<T>::with
  48: std::thread::local::LocalKey<T>::with
  49: std::sys_common::backtrace::__rust_begin_short_backtrace
  50: core::ops::function::FnOnce::call_once{{vtable.shim}}
  51: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys/unix/thread.rs:87
  52: start_thread
  53: clone


Thread 'http.worker10' panicked at '`ed25519_generate` failed: Other("No such file or directory (os error 2)")', /mnt/.cargo/git/checkouts/substrate-7e08433d4c370a21/e8f9018/primitives/io/src/lib.rs:430

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
```

**Comment by bkchr** [comment]
Hey, how did you started the node?

**Comment by chenzongxiong** [comment]
same problem.
I run it via docker, command is: 
```
docker run --rm -it -p 9933:9933 -p 30333:30333 -p 9944:9944 parity/polkadot:latest --rpc-external  --ws-external --dev --name "PolkaDocker"
```
And the version is ""

**Comment by bkchr** [comment]
This is not the same problem. Your problem is that you don't enable unsafe rpc methods. (see --help `--rpc-methods=Unsafe`)
