### ISSUE TITLE
BUG: Thread 'tokio-runtime-worker' panicked at 'Our process exists.

### ISSUE THREAD

**Issue by DanielMagro97** [paritytech/polkadot#1507]
Validator is running v0.8.19, however crashes every few minutes with this error:
```bash
Jul 30 22:50:20 kusama-validator polkadot[3539175]: 2020-07-30 22:50:20 ✨ Imported #3398640 (0x2140…3159)
Jul 30 22:50:20 kusama-validator polkadot[3539175]: 2020-07-30 22:50:20 ✍️ Starting parachain attestation session (parent: 0x2140…3159) with active duty LocalDuty { validation: Relay, index: 129 }
Jul 30 22:50:22 kusama-validator polkadot[3539175]: ====================
Jul 30 22:50:22 kusama-validator polkadot[3539175]: Version: 0.8.19-3a189f5d-x86_64-linux-gnu
Jul 30 22:50:22 kusama-validator polkadot[3539175]:    0: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:    1: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:    2: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:    3: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:    4: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:    5: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:    6: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:    7: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:    8: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:    9: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   10: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   11: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   12: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   13: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   14: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   15: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   16: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   17: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   18: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   19: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   20: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   21: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   22: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   23: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   24: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   25: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   26: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   27: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]:   28: <unknown>
Jul 30 22:50:22 kusama-validator polkadot[3539175]: Thread 'tokio-runtime-worker' panicked at 'Our process exists. qed.: Io(Custom { kind: Other, error: IoErrorWrapper { path: "/proc/3539175/stat", inner: None } }, Some("/proc/3539175/stat"))', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/065b0f3/client/service/src/metrics.rs:210
Jul 30 22:50:22 kusama-validator polkadot[3539175]: This is a bug. Please report it at:
Jul 30 22:50:22 kusama-validator polkadot[3539175]:         https://github.com/paritytech/polkadot/issues/new
```

Other times, it throws this error:
```bash
Jul 30 22:54:55 kusama-validator polkadot[3539699]: 2020-07-30 22:54:55 ✨ Imported #3398682 (0x72c8…2bf9)
Jul 30 22:54:55 kusama-validator polkadot[3539699]: 2020-07-30 22:54:55 ✍️ Starting parachain attestation session (parent: 0x72c8…2bf9) with active duty LocalDuty { validation: Relay, index: 129 }
Jul 30 22:54:55 kusama-validator polkadot[3539699]: 2020-07-30 22:54:55 Essential task `grandpa-voter` failed. Shutting down service.
Jul 30 22:54:55 kusama-validator polkadot[3539699]: 2020-07-30 22:54:55 Availability worker exiting
Jul 30 22:54:55 kusama-validator polkadot[3539699]: Error: Input("Essential task failed.")
```

**Comment by arkpar** [comment]
What's your linux distribution? Does it have procfs? Does the user have access to `/proc` ?

**Comment by DanielMagro97** [comment]
We're using Ubuntu 20.04
Yes I think our VMs use procfs, we have a /proc folder
I've just run `chmod -R 777 proc` but I don't think anything changed, I think it was already that way

**Comment by bkchr** [comment]
@DanielMagro97 can you share the vm image? To reproduce it?

**Comment by DanielMagro97** [comment]
@bkchr would it be ok if we schedule a call instead? I can then run anything you need me to.
In the meantime can I downgrade to v0.8.14?

**Comment by bkchr** [comment]
Or a docker container would also work.

**Comment by staking4all** [comment]
Hi

this bug has affected my node. I have validators and sentries that just keep crashing. Below is from the log. On my side it was hard to notice as I have it running as a process and keeps starting on failure.

As a result i have been slashed :(

Below is an extract from the log. I have also attached the logs in zip file

```
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]: Version: 0.8.19-3a189f5d-x86_64-linux-gnu
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:    0: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:    1: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:    2: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:    3: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:    4: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:    5: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:    6: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:    7: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:    8: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:    9: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   10: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   11: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   12: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   13: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   14: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   15: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   16: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   17: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   18: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   19: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   20: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   21: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   22: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   23: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   24: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   25: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   26: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   27: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]:   28: <unknown>
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]: Thread 'tokio-runtime-worker' panicked at 'Our process exists. qed.: Io(Custom { kind: Other, error: IoErrorWrapper { path: "/proc/17363/stat", inner: None } }, Some("/proc/17363/stat"))', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/065b0f3/client/service/src/metrics.rs:210
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]: This is a bug. Please report it at:
Aug  3 06:32:40 kusama-validator-01 polkadot[17363]: #011https://github.com/paritytech/polkadot/issues/new
Aug  3 06:32:40 kusama-validator-01 systemd[1]: ksm.service: Main process exited, code=exited, status=1/FAILURE
Aug  3 06:32:40 kusama-validator-01 systemd[1]: ksm.service: Failed with result 'exit-code'.
Aug  3 06:32:40 kusama-validator-01 kernel: [1086817.510476] [UFW BLOCK] IN=ens3 OUT= MAC=56:00:02:e6:f7:96:fe:00:02:e6:f7:96:08:00 SRC=87.251.74.215 DST=45.77.207.104 LEN=40 TOS=0x00 PREC=0x00 TTL=241 ID=52245 PROTO=TCP SPT=43246 DPT=12235 WINDOW=1024 RES=0x00 SYN URGP=0 
Aug  3 06:32:41 kusama-validator-01 systemd[1]: ksm.service: Service hold-off time over, scheduling restart.
Aug  3 06:32:41 kusama-validator-01 systemd[1]: ksm.service: Scheduled restart job, restart counter is at 612.
Aug  3 06:32:41 kusama-validator-01 systemd[1]: Stopped Kusama Validator.
Aug  3 06:32:41 kusama-validator-01 systemd[1]: Started Kusama Validator.

```

[syslog.zip](https://github.com/paritytech/polkadot/files/5016225/syslog.zip)
