### ISSUE TITLE
This is a bug. Please report it at

### ISSUE THREAD

**Issue by garysdevil** [paritytech/polkadot#1751]
System: Linux version 4.4.0-180-generic (buildd@lcy01-amd64-004) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #210-Ubuntu SMP Fri May 15 17:06:15 UTC 2020
Machine Config: 4C 8G
Polkadot Version：0.8.24
swap: don't use it.
Role:  full node 
Network: westend
Start Commad: /home/polkadot/polkadot --pruning archive --name "wx_test_westend_node01"  -d /data/polkadot --rpc-external --ws-external --rpc-cors all --chain westend  --unsafe-pruning
Reason: I found that the block height doesn't increase. So I upgrade the version from 0.8.14 to 0.8.24, without reset data.
logs:
```
2020-09-25 14:30:33.353 main WARN sc_cli::config  Low open file descriptor limit configured for the process. Current value: 4096, recommended value: 10000.
2020-09-25 14:30:33.358 main INFO sc_cli::runner  Parity Polkadot
2020-09-25 14:30:33.358 main INFO sc_cli::runner  ✌️  version 0.8.24-5cbc418a-x86_64-linux-gnu
2020-09-25 14:30:33.358 main INFO sc_cli::runner  ❤️  by Parity Technologies <admin@parity.io>, 2017-2020
2020-09-25 14:30:33.358 main INFO sc_cli::runner  📋 Chain specification: Westend
2020-09-25 14:30:33.358 main INFO sc_cli::runner  🏷  Node name: wx_test_westend_node01
2020-09-25 14:30:33.358 main INFO sc_cli::runner  👤 Role: FULL
2020-09-25 14:30:33.358 main INFO sc_cli::runner  💾 Database: RocksDb at /data/polkadot/chains/westend2/db
2020-09-25 14:30:33.358 main INFO sc_cli::runner  ⛓  Native runtime: westend-43 (parity-westend-1.tx3.au2)
2020-09-25 14:30:33.471 main INFO sub-libp2p  🏷  Local node identity is: 12D3KooWNseAWBvyLp5nVLVPYS6Lc3oQpWuyggmABJd8pdu1eDaL (legacy representation: 12D3KooWNseAWBvyLp5nVLVPYS6Lc3oQpWuyggmABJd8pdu1eDaL)
2020-09-25 14:30:33.473 main INFO sc_service::builder  📦 Highest known block at #2153470
2020-09-25 14:30:33.474 tokio-runtime-worker INFO substrate_prometheus_endpoint::known_os  〽️ Prometheus server started at 127.0.0.1:9615
2020-09-25 14:30:36.816 tokio-runtime-worker INFO sub-libp2p  🔍 Discovered new external address for our node: /ip4/180.167.100.186/tcp/30333/p2p/12D3KooWNseAWBvyLp5nVLVPYS6Lc3oQpWuyggmABJd8pdu1eDaL
2020-09-25 14:30:38.477 tokio-runtime-worker INFO substrate  ⚙️  Syncing, target=#2363795 (2 peers), best: #2153470 (0xa1b9…f89a), finalized #2153467 (0xb057…3426), ⬇ 3.9kiB/s ⬆ 2.5kiB/s
2020-09-25 14:30:41.946 tokio-runtime-worker INFO staking  💸 Election window is Open(2153530). Snapshot created
2020-09-25 14:30:42.578 tokio-runtime-worker INFO staking  💸 A better solution (with compute ElectionCompute::Unsigned and score [17574744335106, 8795459310588578, 9613406844905080016695411062494]) has been validated and stored on chain.
Hash: given=f9517592e8ba6c9d4bda92d177d76edba1fe63dd84c2199ef609d48fa74af35a, expected=aa5fe2257193d8ed10c83664a54202f5fb3490ca8141f6a99c07effbef9bad55

====================

Version: 0.8.24-5cbc418a-x86_64-linux-gnu

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: start_thread
  37: clone
Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:13

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

2020-09-25 14:30:43.477 tokio-runtime-worker INFO substrate  ⚙️  Syncing 31.6 bps, target=#2363796 (8 peers), best: #2153628 (0xf6db…d9dd), finalized #2153472 (0xda64…b177), ⬇ 54.8kiB/s ⬆ 3.3kiB/s
2020-09-25 14:30:43.918 tokio-runtime-worker INFO staking  💸 new validator set of size 12 has been elected via ElectionCompute::Unsigned for era 2689
2020-09-25 14:30:48.477 tokio-runtime-worker INFO substrate  ⚙️  Syncing 120.0 bps, target=#2363797 (10 peers), best: #2154228 (0x7f30…4258), finalized #2153984 (0xc20b…a3e5), ⬇ 178.9kiB/s ⬆ 4.0kiB/s
Hash: given=cb9831145aafaee8f6e1f3da6304d1e89c0de2d88235b4e1b549f5ae27ef2b18, expected=f388b2f7121163a59a1ff5004e3c2744fc37b475d7976ff973142796aed13afc

====================

Version: 0.8.24-5cbc418a-x86_64-linux-gnu

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
...
...
...
...
....
...

  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: start_thread
  37: clone
  
  
Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:13
  
This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

2020-09-25 14:36:28.490 tokio-runtime-worker INFO substrate  ⚙️  Syncing 48.4 bps, target=#2363847 (20 peers), best: #2181040 (0x4076…6aa2), finalized #2180608 (0x58b1…27b9), ⬇ 4.6kiB/s ⬆ 2.7kiB/s
                                                                                                                                                                                                  7446,1     
```

**Comment by bkchr** [comment]
Does this still happen after restart?

**Comment by garysdevil** [comment]
> Does this still happen after restart?

Sorry,  I stop the old version, replace the binary file, start polkadot. I seem to have not to restart the new version.
After that, I use the 0.8.23 version, it can run well

**Comment by garysdevil** [comment]
> Does this still happen after restart?

I changed into 0.8.24 from 0.8.23 version today, it can run well now.
But, why happed that wrong "This is a bug. Please report it at:" when I run the 0.8.24 version firstly
