### ISSUE TITLE
Thread 'main' panicked at 'assertion failed

### ISSUE THREAD

**Issue by khssnv** [paritytech/polkadot#200]
I've just attempted to launch a local testnet by [guide](https://github.com/paritytech/polkadot#31-hacking-on-polkadot) from readme. Building from latest commit [e3d66f0](https://github.com/paritytech/polkadot/commit/e3d66f0dc79badcf11a2f100f12232b1405aec17) cause an error. Please find a log below.

```console
╭─khassanov@32vd ~/Workspace/polkadot  ‹master›
╰─$ cargo run -- --version
    Finished dev [unoptimized + debuginfo] target(s) in 0.56s
     Running `target/debug/polkadot --version`
polkadot 0.4.0-e3d66f0d-x86_64-linux-gnu
```

<details>
  <summary>stack backtrace</summary>

```console
╭─khassanov@32vd ~/Workspace/polkadot  ‹master›
╰─$ rm -rf ~/.local/share/polkadot && cargo run -- --dev                                                                                                                                                1 ↵
    Finished dev [unoptimized + debuginfo] target(s) in 0.55s
     Running `target/debug/polkadot --dev`
2019-03-30 23:02:35 Parity Polkadot
2019-03-30 23:02:35   version 0.4.0-e3d66f0d-x86_64-linux-gnu
2019-03-30 23:02:35   by Parity Team <admin@parity.io>, 2017-2019
2019-03-30 23:02:35 Chain specification: Development
2019-03-30 23:02:35 Node name: ceaseless-kettle-7012
2019-03-30 23:02:35 Roles: AUTHORITY

====================

stack backtrace:
   0: substrate_panic_handler::panic_hook::hf6e3b9cf2a06c311 (0x56234807be4d)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/panic-handler/src/lib.rs:82
   1: substrate_panic_handler::set::{{closure}}::haea63ca4614ec523 (0x56234807b9e6)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/panic-handler/src/lib.rs:31
   2: std::panicking::rust_panic_with_hook::h744417edfe714d72 (0x5623488321b9)
             at src/libstd/panicking.rs:482
   3: std::panicking::begin_panic::h06555e04985f249c (0x5623480214c7)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/panicking.rs:412
   4: <srml_staking::GenesisConfig<T> as sr_primitives::BuildStorage>::assimilate_storage::{{closure}}::{{closure}}::h6041c3c5be4b26f6 (0x562346ba87e9)
             at /home/khassanov/Workspace/polkadot/<::std::macros::panic macros>:3
   5: environmental::using::{{closure}}::h37d0815f65ff08ac (0x562346bcb520)
             at /home/khassanov/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.0.1/src/lib.rs:88
   6: <std::thread::local::LocalKey<T>>::try_with::h48ff190d7220d39a (0x562346c20540)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/thread/local.rs:299
   7: <std::thread::local::LocalKey<T>>::with::h04114fcf66c93ef5 (0x562346c20307)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/thread/local.rs:245
   8: environmental::using::h772c1c9daa9a3273 (0x562346bcb400)
             at /home/khassanov/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.0.1/src/lib.rs:65
   9: sr_io::ext::using::h6bfd5696f4b4a11f (0x562346c174ab)
             at /home/khassanov/Workspace/polkadot/<::environmental::environmental macros>:21
  10: sr_io::with_storage::h3bab117b6fa3084c (0x562346c171dd)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/sr-io/src/../with_std.rs:242
  11: <srml_staking::GenesisConfig<T> as sr_primitives::BuildStorage>::assimilate_storage::{{closure}}::h5a6473f47d0c6b51 (0x562346ba8350)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/srml/staking/src/lib.rs:486
  12: <srml_staking::GenesisConfig<T> as sr_primitives::BuildStorage>::assimilate_storage::h65f76e172dedf309 (0x562346ba8292)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/srml/staking/src/lib.rs:399
  13: <polkadot_runtime::GenesisConfig as sr_primitives::BuildStorage>::assimilate_storage::h2ea35f194aa9a650 (0x562346a052b3)
             at /home/khassanov/Workspace/polkadot/<::sr_primitives::impl_outer_config macros>:20
  14: sr_primitives::BuildStorage::build_storage::h839ded2b67050fc8 (0x56234624a38b)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/sr-primitives/src/lib.rs:105
  15: <&'a substrate_service::chain_spec::ChainSpec<G> as sr_primitives::BuildStorage>::build_storage::he34c7bd6ae76ebf6 (0x56234622b4d3)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/service/src/chain_spec.rs:71
  16: <substrate_client::client::Client<B, E, Block, RA>>::new::hc04b7d90d30e953a (0x562345cb547e)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/client/src/client.rs:283
  17: substrate_client_db::new_client::hfaed726c82c3dd34 (0x562345b1d53c)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/client/db/src/lib.rs:95
  18: <substrate_service::components::FullComponents<Factory> as substrate_service::components::Components>::build_client::h422e30a53f829206 (0x5623458d9ffe)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/service/src/components.rs:461
  19: <substrate_service::Service<Components>>::new::h4efafd154ffd2275 (0x56234572fe0b)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/service/src/lib.rs:129
  20: <substrate_service::components::FullComponents<Factory>>::new::hc5bff06e4e4f9097 (0x5623458dc37f)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/service/src/components.rs:418
  21: <polkadot_service::Factory as substrate_service::components::ServiceFactory>::new_full::{{closure}}::he0c7878a37ad5cea (0x56234681ea4d)
             at service/src/lib.rs:170
  22: <polkadot_service::Factory as substrate_service::components::ServiceFactory>::new_full::h1065c6ecacd8edf1 (0x5623458e27d3)
             at /home/khassanov/Workspace/polkadot/<::substrate_service::construct_service_factory macros>:50
  23: polkadot_cli::run::{{closure}}::hc4527fb5389543c7 (0x562345632325)
             at /home/khassanov/Workspace/polkadot/cli/src/lib.rs:108
  24: substrate_cli::run_node::h84387fed35c88dd4 (0x562345674571)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/cli/src/lib.rs:506
  25: substrate_cli::parse_and_execute::h83ddec5613fd766d (0x56234566f11e)
             at /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/core/cli/src/lib.rs:230
  26: polkadot_cli::run::h4b486aa27b863dfa (0x56234563142b)
             at /home/khassanov/Workspace/polkadot/cli/src/lib.rs:87
  27: polkadot::run::h19ea40c81e9d9623 (0x5623456b8df9)
             at src/main.rs:73
  28: polkadot::main::h2c668eb19f59ebd9 (0x5623456b8e20)
             at /home/khassanov/Workspace/polkadot/<::error_chain::quick_main::quick_main macros>:4
  29: std::rt::lang_start::{{closure}}::hba5a706e2f6831a5 (0x562345677b0f)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  30: std::rt::lang_start_internal::{{closure}}::h8ad4264c6b68797c (0x562348831ae2)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::h7a0381557c6c2cee
             at src/libstd/panicking.rs:297
  31: __rust_maybe_catch_panic (0x562348838099)
             at src/libpanic_unwind/lib.rs:92
  32: std::panicking::try::h72cb0fef6e9c0ab1 (0x5623488326f5)
             at src/libstd/panicking.rs:276
      std::panic::catch_unwind::hbff071ae76e6f224
             at src/libstd/panic.rs:388
      std::rt::lang_start_internal::he0d8d06abc6f912f
             at src/libstd/rt.rs:48
  33: std::rt::lang_start::h9c69281104a00f00 (0x562345677ae8)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  34: main (0x5623456b9049)
  35: __libc_start_main (0x7f91766f4b96)
  36: _start (0x5623455f6909)
  37: <unknown> (0x0)

Thread 'main' panicked at 'assertion failed: T::Currency::free_balance(&stash) >= balance', /home/khassanov/.cargo/git/checkouts/substrate-7e08433d4c370a21/8bf08ca/srml/staking/src/lib.rs:488

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new
```
</details>

**Comment by khssnv** [comment]
Rolled back to tag `v0.3.15`, commit `6d488979bc4be7275cd76c9287d6fb56f74ae5a9`, it works.
