### ISSUE TITLE
Storage root must match that calculated

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#2016]
Running with Mac Mini M1

Not sure if this have anything to do with arm build. Did not see this issue on Kusama node with same binary.

I also did a cargo update locally to fix some build issue with arm64.

CLI: `polkadot --chain=polkadot --wasm-execution=Compiled --pruning=archive`

`version 0.8.26-a0541ce7-aarch64-macos`

```
0|polkadot  | 2020-11-26 23:12:24  💤 Idle (15 peers), best: #2634817 (0x1c44…8b24), finalized #2634815 (0xb0f2…dafb), ⬇ 44.2kiB/s ⬆ 24.2kiB/s
0|polkadot  | Hash: given=74173a8e7d7dec4aafbca76136f936edf0ac0bbe6a5b1da2845deaeddc323b48, expected=b0436e6fd019ad8a1810b72a1365794b4aa1f035c2dd6a768497e065f57255dd
0|polkadot  | ====================
0|polkadot  | Version: 0.8.26-a0541ce7-aarch64-macos
0|polkadot  |    0: backtrace::backtrace
0|polkadot  | ::trace
0|polkadot  |    1: backtrace::capture::Backtrace::new
0|polkadot  |    2: sp_panic_handler::set::{{closure}}
0|polkadot  |    3: std::panicking::rust_panic_with_hook
0|polkadot  |              at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:595:17
0|polkadot  |    4: std::panicking::begin_panic::{{closure}}
0|polkadot  |    5: std::sys_common
0|polkadot  | ::backtrace::__rust_end_short_backtrace
0|polkadot  |    6: std::panicking::begin_panic
0|polkadot  |    7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::final_checks
0|polkadot  |    8: tracing::span::Span::in_scope
0|polkadot  |    9: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
0|polkadot  |   10: <polkadot_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic
0|polkadot  | ::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,polkadot_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<polkadot_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<polkadot_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<polkadot_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<polkadot_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<polkadot_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<polkadot_runtime::
0|polkadot  | Runtime>,pallet_transaction_payment::ChargeTransactionPayment<polkadot_runtime::Runtime>,polkadot_runtime_common::claims::PrevalidateAttests<polkadot_runtime::Runtime>)>>>>::execute_block
0|polkadot  |   11: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
0|polkadot  |   12: std::thread::local::LocalKey<T>::with
0|polkadot  |   13: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
0|polkadot  |   14: sc_executor::wasm_runtime::RuntimeCache::with_instance
0|polkadot  |   15: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
0|polkadot  |   16: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
0|polkadot  |   17: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
0|polkadot  |   18: <
0|polkadot  | sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
0|polkadot  |   19: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
0|polkadot  |   20: sp_api::runtime_decl_for_Core::execute_block_call_api_at
0|polkadot  |   21: sp_api::Core::execute_block_with_context
0|polkadot  |   22: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus
0|polkadot  | ::block_import::BlockImport<Block>>::import_block
0|polkadot  |   23: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
0|polkadot  |   24: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
0|polkadot  |   25: sp_consensus::import_queue::import_single_block_metered
0|polkadot  |   26: <futures_util::future::poll_fn::PollFn<F
0|polkadot  | > as core::future::future::Future>::poll
0|polkadot  |   27: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
0|polkadot  |   28: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
0|polkadot  |   29: <futures_util::future
0|polkadot  | ::poll_fn::PollFn<F> as core::future::future::Future>::poll
0|polkadot  |   30: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
0|polkadot  |   31: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
0|polkadot  |   32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
0|polkadot  |   33: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
0|polkadot  |   34: std::thread::local::LocalKey<T>::with
0|polkadot  |   35: futures_executor::local_pool::block_on
0|polkadot  |   36: tokio::runtime::task::core::Core<T,S>::poll
0|polkadot  |   37: <std::panic::AssertUnwindSafe<F> as core::ops::
0|polkadot  | function::FnOnce<()>>::call_once
0|polkadot  |   38: tokio::runtime::task::raw::poll
0|polkadot  |   39: tokio::runtime::blocking::pool::Inner::run
0|polkadot  |   40: tokio::runtime::context::enter
0|polkadot  |   41: std::sys_common::backtrace::__rust_begin_short_backtrace
0|polkadot  |   42: core::ops::function::FnOnce::call_once{{vtable.shim}}
0|polkadot  |   43: <alloc::boxed::Box<F,A> as core::ops::function
0|polkadot  | ::FnOnce<Args>>::call_once
0|polkadot  |              at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/alloc/src/boxed.rs:1318:9
0|polkadot  |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
0|polkadot  |              at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/alloc/src/boxed.rs:1318:9
0|polkadot  |       std::sys::unix::
0|polkadot  | thread::Thread::new::thread_start
0|polkadot  |              at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/sys/unix/thread.rs:71:17
0|polkadot  |   44: _pthread_kill
0|polkadot  | Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /Users/xiliangchen/.cargo/git/checkouts/substrate-7e08433d4c370a21/cff25fb/frame/executive/src/lib.rs:416
0|polkadot  | This is a bug. Please report it at:
0|polkadot  | 	https://github.com/paritytech/polkadot/issues/new
0|polkadot  | 2020-11-26 23:12:26  ✨ Imported #2634818 (0x7079…386d)
```

**Comment by bkchr** [comment]
Please run with `--execution wasm`
