### ISSUE TITLE
libp2p crash related for request-response

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#2307]
While running polkadot of c222fd6d8 I've got this.

```
====================

Version: 0.8.27-c222fd6d8-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/fde692739576089729885b7f79aa2232cb9778c5/library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/fde692739576089729885b7f79aa2232cb9778c5/library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/fde692739576089729885b7f79aa2232cb9778c5/library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/fde692739576089729885b7f79aa2232cb9778c5/library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/fde692739576089729885b7f79aa2232cb9778c5/library/core/src/panicking.rs:92
   6: core::option::expect_failed
             at /rustc/fde692739576089729885b7f79aa2232cb9778c5/library/core/src/option.rs:1258
   7: <sc_network::request_responses::RequestResponsesBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   8: <sc_network::behaviour::Behaviour<B,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   9: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::poll_next_event
  10: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
  11: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  12: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  18: std::thread::local::LocalKey<T>::with
  19: futures_executor::local_pool::block_on
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  21: tokio::runtime::task::harness::Harness<T,S>::poll
  22: tokio::runtime::blocking::pool::Inner::run
  23: tokio::runtime::context::enter
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
  26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/fde692739576089729885b7f79aa2232cb9778c5/library/alloc/src/boxed.rs:1480
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/fde692739576089729885b7f79aa2232cb9778c5/library/alloc/src/boxed.rs:1480
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/fde692739576089729885b7f79aa2232cb9778c5/library/std/src/sys/unix/thread.rs:71
  27: start_thread
  28: __clone


Thread 'tokio-runtime-worker' panicked at 'To find request arrival time for answered request.', /home/lilpep/.cargo/git/checkouts/substrate-7e08433d4c370a21/bd5c9a6/client/network/src/request_responses.rs:589
```

**Comment by tomaka** [comment]
cc @romanb @mxinden

**Comment by tomaka** [comment]
As far as I understand this is a local setup where 3 nodes connected to each other are on the same machine.
This might be hint, as a ping time of 0 might cause events to be reported in the wrong order, for example.

**Comment by mxinden** [comment]
I have a suspicion which I still need to prove.

A `libp2p-request-response` behaviour uses monotonically increasing request ids to identify requests, starting with `1`. The Substrate `request-responses` behaviour combines multiple `libp2p-request-response` behaviours and keeps track of requests in a combined collection by their request id. Combining two or more `libp2p-request-response` behaviours allows request id collisions.

A collision likely caused this panic, where the arrival time of one request overwrote the arrival time of a second request, both having the same id.

Again, I need to dig a bit to make sure this is the cause. Sorry for the inconvenience.

**Comment by tomaka** [comment]
That would make sense, as [we've just introduced the second request-response protocol](https://github.com/paritytech/polkadot/pull/2301) yesterday.

**Comment by tomaka** [comment]
> That would make sense, as we've just introduced a second request-response protocol yesterday, while there was only one before.

However that new request-response protocol definitely shouldn't receive any incoming request. There isn't even any code emitting requests at the moment.

**Comment by mxinden** [comment]
Thanks @pepyakin for raising awareness for the panic!
