### ISSUE TITLE
kusma node is panicking & failing to start

### ISSUE THREAD

**Issue by pkrasam** [paritytech/polkadot#2312]
```
Jan 23 15:21:10 w3ma systemd[1]: Started Kusama Validator.
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  ----------------------------
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  This chain is not in any way
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10        endorsed by the
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10       KUSAMA FOUNDATION
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  ----------------------------
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  Parity Polkadot
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  ✌️  version 0.8.27-2f845699-x86_64-linux-gnu
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  📋 Chain specification: Kusama
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  🏷 Node name: w3m
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  👤 Role: FULL
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  💾 Database: ParityDb at /home/polkadot/.local/share/polkadot/chains/ksmcc3/paritydb
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  ⛓  Native runtime: kusama-2027 (parity-kusama-0.tx3.au2)
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  🏷 Local node identity is: 12D3KooWKH9Z53i18tPp5sB6bJmgK2j9X26MdYX33pZfHfpsbSYX
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  📦 Highest known block at #5856195
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  〽️ Prometheus server started at 127.0.0.1:9615
Jan 23 15:21:10 w3ma polkadot[2660620]: 2021-01-23 15:21:10  Listening for new connections on 127.0.0.1:9944.
Jan 23 15:21:10 w3ma polkadot[2660620]: ====================
Jan 23 15:21:10 w3ma polkadot[2660620]: Version: 0.8.27-2f845699-x86_64-linux-gnu
Jan 23 15:21:10 w3ma polkadot[2660620]:    0: sp_panic_handler::set::{{closure}}
Jan 23 15:21:10 w3ma polkadot[2660620]:    1: std::panicking::rust_panic_with_hook
Jan 23 15:21:10 w3ma polkadot[2660620]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581
Jan 23 15:21:10 w3ma polkadot[2660620]:    2: std::panicking::begin_panic_handler::{{closure}}
Jan 23 15:21:10 w3ma polkadot[2660620]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
Jan 23 15:21:10 w3ma polkadot[2660620]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Jan 23 15:21:10 w3ma polkadot[2660620]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
Jan 23 15:21:10 w3ma polkadot[2660620]:    4: rust_begin_unwind
Jan 23 15:21:10 w3ma polkadot[2660620]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
Jan 23 15:21:10 w3ma polkadot[2660620]:    5: core::panicking::panic_fmt
Jan 23 15:21:10 w3ma polkadot[2660620]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
Jan 23 15:21:10 w3ma polkadot[2660620]:    6: core::option::expect_none_failed
Jan 23 15:21:10 w3ma polkadot[2660620]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
Jan 23 15:21:10 w3ma polkadot[2660620]:    7: <sp_state_machine::ext::Ext<H,N,B> as sp_externalities::Externalities>::storage
Jan 23 15:21:10 w3ma polkadot[2660620]:    8: <&mut dyn sp_externalities::Externalities as sp_io::storage::Storage>::get_version_1
Jan 23 15:21:10 w3ma polkadot[2660620]:    9: std::thread::local::LocalKey<T>::with
Jan 23 15:21:10 w3ma polkadot[2660620]:   10: sp_io::storage::get_version_1
Jan 23 15:21:10 w3ma polkadot[2660620]:   11: <<sp_io::storage::HostFunctions as sp_wasm_interface::HostFunctions>::host_functions::ExtStorageGetVersion1 as sp_wasm_interface::Function>::execute
Jan 23 15:21:10 w3ma polkadot[2660620]:   12: <sc_executor_wasmi::FunctionExecutor as wasmi::host::Externals>::invoke_index
Jan 23 15:21:10 w3ma polkadot[2660620]:   13: wasmi::func::FuncInstance::invoke
Jan 23 15:21:10 w3ma polkadot[2660620]:   14: wasmi::runner::Interpreter::start_execution
Jan 23 15:21:10 w3ma polkadot[2660620]:   15: wasmi::func::FuncInstance::invoke
Jan 23 15:21:10 w3ma polkadot[2660620]:   16: <sc_executor_wasmi::WasmiInstance as sc_executor_common::wasm_runtime::WasmInstance>::call
Jan 23 15:21:10 w3ma polkadot[2660620]:   17: sc_executor_common::wasm_runtime::WasmInstance::call_export
Jan 23 15:21:10 w3ma polkadot[2660620]:   18: std::panicking::try
Jan 23 15:21:10 w3ma polkadot[2660620]:   19: std::thread::local::LocalKey<T>::with
Jan 23 15:21:10 w3ma polkadot[2660620]:   20: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Jan 23 15:21:10 w3ma polkadot[2660620]:   21: sc_executor::wasm_runtime::RuntimeCache::with_instance
Jan 23 15:21:10 w3ma polkadot[2660620]:   22: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Jan 23 15:21:10 w3ma polkadot[2660620]:   23: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
Jan 23 15:21:10 w3ma polkadot[2660620]:   24: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Jan 23 15:21:10 w3ma polkadot[2660620]:   25: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Jan 23 15:21:10 w3ma polkadot[2660620]:   26: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Jan 23 15:21:10 w3ma polkadot[2660620]:   27: sp_api::runtime_decl_for_Core::initialize_block_call_api_at
Jan 23 15:21:10 w3ma polkadot[2660620]:   28: <kusama_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl
Jan 23 15:21:10 w3ma polkadot[2660620]:   29: sp_api::Core::initialize_block
Jan 23 15:21:10 w3ma polkadot[2660620]:   30: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Jan 23 15:21:10 w3ma polkadot[2660620]:   31: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Jan 23 15:21:10 w3ma polkadot[2660620]:   32: sp_block_builder::runtime_decl_for_BlockBuilder::check_inherents_call_api_at
Jan 23 15:21:10 w3ma polkadot[2660620]:   33: sp_block_builder::BlockBuilder::check_inherents
Jan 23 15:21:10 w3ma polkadot[2660620]:   34: <sc_consensus_babe::BabeVerifier<Block,Client,SelectChain,CAW> as sp_consensus::import_queue::Verifier<Block>>::verify
Jan 23 15:21:10 w3ma polkadot[2660620]:   35: sp_consensus::import_queue::import_single_block_metered
Jan 23 15:21:10 w3ma polkadot[2660620]:   36: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Jan 23 15:21:10 w3ma polkadot[2660620]:   37: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Jan 23 15:21:10 w3ma polkadot[2660620]:   38: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
Jan 23 15:21:10 w3ma polkadot[2660620]:   39: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Jan 23 15:21:10 w3ma polkadot[2660620]:   40: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Jan 23 15:21:10 w3ma polkadot[2660620]:   41: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Jan 23 15:21:10 w3ma polkadot[2660620]:   42: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jan 23 15:21:10 w3ma polkadot[2660620]:   43: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Jan 23 15:21:10 w3ma polkadot[2660620]:   44: std::thread::local::LocalKey<T>::with
Jan 23 15:21:10 w3ma polkadot[2660620]:   45: futures_executor::local_pool::block_on
Jan 23 15:21:10 w3ma polkadot[2660620]:   46: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Jan 23 15:21:10 w3ma polkadot[2660620]:   47: tokio::runtime::task::harness::Harness<T,S>::poll
Jan 23 15:21:10 w3ma polkadot[2660620]:   48: tokio::runtime::blocking::pool::Inner::run
Jan 23 15:21:10 w3ma polkadot[2660620]:   49: tokio::runtime::context::enter
Jan 23 15:21:10 w3ma polkadot[2660620]:   50: std::sys_common::backtrace::__rust_begin_short_backtrace
Jan 23 15:21:10 w3ma polkadot[2660620]:   51: core::ops::function::FnOnce::call_once{{vtable.shim}}
Jan 23 15:21:10 w3ma polkadot[2660620]:   52: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Jan 23 15:21:10 w3ma polkadot[2660620]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
Jan 23 15:21:10 w3ma polkadot[2660620]:       <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Jan 23 15:21:10 w3ma polkadot[2660620]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
Jan 23 15:21:10 w3ma polkadot[2660620]:       std::sys::unix::thread::Thread::new::thread_start
Jan 23 15:21:10 w3ma polkadot[2660620]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
Jan 23 15:21:10 w3ma polkadot[2660620]:   53: start_thread
Jan 23 15:21:10 w3ma polkadot[2660620]:   54: clone
Jan 23 15:21:10 w3ma polkadot[2660620]: Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0xb9d8d629ec256f9da3bf8dfdab580d572f2b82a99f7f95be6e5d633aec6bb401"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/8c3b3fb/primitives/state-machine/src/ext.rs:224
Jan 23 15:21:10 w3ma polkadot[2660620]: This is a bug. Please report it at:
Jan 23 15:21:10 w3ma polkadot[2660620]:         https://github.com/paritytech/polkadot/issues/new
Jan 23 15:21:10 w3ma systemd[1]: kusama.service: Main process exited, code=exited, status=1/FAILURE
Jan 23 15:21:10 w3ma systemd[1]: kusama.service: Failed with result 'exit-code'.
```

**Comment by arkpar** [comment]
Was there any kind of crash on a previous launch?

**Comment by pkrasam** [comment]
@arkpar I am not sure if there was a crash from previous launch -- how can i tell?

**Comment by pkrasam** [comment]
Is there a way to troubleshoot the current panic |or| should I consider start a re-sync from start?

**Comment by arkpar** [comment]
You'll have to re-sync. https://github.com/paritytech/substrate/pull/7961 should help prevent such issues in the future.

**Comment by pkrasam** [comment]
Thank you @arkpar kicked off re-sync from the beginning just in case.

Should we expect a new binary anytime soon with the change from ^ #7981 ?!

```
config.sync = true; // Flush each commit
```

**Comment by bkchr** [comment]
Yes there will be a new release in the next 2 weeks.

As this seems to be solved, I close the issue.
