### ISSUE TITLE
Starting a local chain fails

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot#232]
I am running `0.4.3`.

# what works:
`docker run --rm -it chevdor/polkadot:0.4.3 polkadot  --alice`

# what crashes:
`docker run --rm -it chevdor/polkadot:0.4.3 polkadot --chain=local  --alice`

The logs show:
```
2019-04-21 18:01:11 Parity Polkadot
2019-04-21 18:01:11   version 0.4.3-ecbe3f7-x86_64-linux-gnu
2019-04-21 18:01:11   by Parity Team <admin@parity.io>, 2017-2019
2019-04-21 18:01:11 Chain specification: Local Testnet
2019-04-21 18:01:11 Node name: Alice
2019-04-21 18:01:11 Roles: FULL

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h1adbb2274253a5f7 (0x55cba24741b0)
   1: std::panicking::rust_panic_with_hook::h744417edfe714d72 (0x55cba264ef29)
             at src/libstd/panicking.rs:482
   2: std::panicking::begin_panic::h310d5f164412d2ea (0x55cba1c80c94)
   3: <std::thread::local::LocalKey<T>>::with::hb3c1d67fab5220d1 (0x55cba1d1795e)
   4: sr_io::with_storage::h2d07d5e20c42caa6 (0x55cba1ce4a42)
   5: <srml_staking::GenesisConfig<T> as sr_primitives::BuildStorage>::assimilate_storage::hbf1a52cd3442d1b6 (0x55cba1ca024f)
   6: <polkadot_runtime::GenesisConfig as sr_primitives::BuildStorage>::assimilate_storage::h41853d71c4f85c7e (0x55cba1c7e158)
   7: sr_primitives::BuildStorage::build_storage::hcdf07329d83bf184 (0x55cba18322f8)
   8: <&'a substrate_service::chain_spec::ChainSpec<G> as sr_primitives::BuildStorage>::build_storage::hcb5ca6a81ca764f2 (0x55cba1bb09e5)
   9: <substrate_client::client::Client<B, E, Block, RA>>::new::ha7841cbd91662a72 (0x55cba1b53cd0)
  10: substrate_client_db::new_client::hc9a724557e7e6e97 (0x55cba17e5911)
  11: <substrate_service::components::FullComponents<Factory> as substrate_service::components::Components>::build_client::hfdd9a314df86e313 (0x55cba1a6169f)
  12: <substrate_service::Service<Components>>::new::h0e405ae48c74d91e (0x55cba196eaf9)
  13: <polkadot_service::Factory as substrate_service::components::ServiceFactory>::new_full::hba6d0a28f72a6368 (0x55cba169a6c6)
  14: substrate_cli::run_node::hb8a94eb715d444c3 (0x55cba15516e0)
  15: substrate_cli::parse_and_execute::h64faf0e8703b735f (0x55cba154b752)
  16: polkadot::main::h432499affdc289b3 (0x55cba15b2df2)
  17: std::rt::lang_start::{{closure}}::hcc9bbb6c803fd2cb (0x55cba159f032)
  18: std::rt::lang_start_internal::{{closure}}::h8ad4264c6b68797c (0x55cba264e852)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::h7a0381557c6c2cee
             at src/libstd/panicking.rs:297
  19: __rust_maybe_catch_panic (0x55cba26552d9)
             at src/libpanic_unwind/lib.rs:92
  20: std::panicking::try::h72cb0fef6e9c0ab1 (0x55cba264f465)
             at src/libstd/panicking.rs:276
      std::panic::catch_unwind::hbff071ae76e6f224
             at src/libstd/panic.rs:388
      std::rt::lang_start_internal::he0d8d06abc6f912f
             at src/libstd/rt.rs:48
  21: main (0x55cba15b2f91)
  22: __libc_start_main (0x7f128309782f)
  23: _start (0x55cba14bae78)
  24: <unknown> (0x0)

Thread 'main' panicked at 'assertion failed: T::Currency::free_balance(&stash) >= balance', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/89bbb7b/srml/staking/src/lib.rs:528

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
```

**Comment by chevdor** [comment]
The issue has been fixed after the tag `v0.4.3` was set in 3baa321fd97869159e567602f8fc8678c6ce0bcb

I published an image including the fix: `chevdor/polkadot:0.4.3-d3cbe655`

Additionally, it requires changing `--key Alice` into `--alice`
