### ISSUE TITLE
kusama bug

### ISSUE THREAD

**Issue by andreisid** [paritytech/polkadot#2475]
Feb 18 17:45:09 kusama-st polkadot[13360]: 2021-02-18 17:45:09  💤 Idle (49 peers), best: #6264931 (0x7606…9fd7), finalized #6264928 (0x99d6…b55f), ⬇ 1.7MiB/s ⬆ 909.4kiB/s
Feb 18 17:45:12 kusama-st polkadot[13360]: 2021-02-18 17:45:12  ✨ Imported #6264932 (0x1988…84f1)
Feb 18 17:45:14 kusama-st polkadot[13360]: 2021-02-18 17:45:14  💤 Idle (48 peers), best: #6264932 (0x1988…84f1), finalized #6264929 (0xa0ae…f9a6), ⬇ 2.0MiB/s ⬆ 1.7MiB/s
Feb 18 17:45:15 kusama-st polkadot[13360]: ====================
Feb 18 17:45:15 kusama-st polkadot[13360]: Version: 0.8.28-1-99043f78-x86_64-linux-gnu
Feb 18 17:45:15 kusama-st polkadot[13360]:    0: sp_panic_handler::set::{{closure}}
Feb 18 17:45:15 kusama-st polkadot[13360]:    1: std::panicking::rust_panic_with_hook
Feb 18 17:45:15 kusama-st polkadot[13360]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597
Feb 18 17:45:15 kusama-st polkadot[13360]:    2: std::panicking::begin_panic::{{closure}}
Feb 18 17:45:15 kusama-st polkadot[13360]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Feb 18 17:45:15 kusama-st polkadot[13360]:    4: std::panicking::begin_panic
Feb 18 17:45:15 kusama-st polkadot[13360]:    5: <libp2p_mdns::behaviour::Mdns as libp2p_swarm::behaviour::NetworkBehaviour>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:    6: <sc_network::discovery::DiscoveryBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:    7: <sc_network::behaviour::Behaviour<B,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:    8: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::poll_next_event
Feb 18 17:45:15 kusama-st polkadot[13360]:    9: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:   10: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
Feb 18 17:45:15 kusama-st polkadot[13360]:   11: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:   13: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:   14: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:   15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:   16: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:   17: std::thread::local::LocalKey<T>::with
Feb 18 17:45:15 kusama-st polkadot[13360]:   18: futures_executor::local_pool::block_on
Feb 18 17:45:15 kusama-st polkadot[13360]:   19: tokio::runtime::task::core::Core<T,S>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:   20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Feb 18 17:45:15 kusama-st polkadot[13360]:   21: tokio::runtime::task::harness::Harness<T,S>::poll
Feb 18 17:45:15 kusama-st polkadot[13360]:   22: tokio::runtime::blocking::pool::Inner::run
Feb 18 17:45:15 kusama-st polkadot[13360]:   23: tokio::runtime::context::enter
Feb 18 17:45:15 kusama-st polkadot[13360]:   24: std::sys_common::backtrace::__rust_begin_short_backtrace
Feb 18 17:45:15 kusama-st polkadot[13360]:   25: core::ops::function::FnOnce::call_once{{vtable.shim}}
Feb 18 17:45:15 kusama-st polkadot[13360]:   26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 18 17:45:15 kusama-st polkadot[13360]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
Feb 18 17:45:15 kusama-st polkadot[13360]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 18 17:45:15 kusama-st polkadot[13360]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
Feb 18 17:45:15 kusama-st polkadot[13360]:       std::sys::unix::thread::Thread::new::thread_start
Feb 18 17:45:15 kusama-st polkadot[13360]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread.rs:71
Feb 18 17:45:15 kusama-st polkadot[13360]:   27: start_thread
Feb 18 17:45:15 kusama-st polkadot[13360]:   28: __clone
Feb 18 17:45:15 kusama-st polkadot[13360]: Thread 'tokio-runtime-worker' panicked at 'Mdns poisoned', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-mdns-0.28.0/src/behaviour.rs:195
Feb 18 17:45:15 kusama-st polkadot[13360]: This is a bug. Please report it at:
Feb 18 17:45:15 kusama-st polkadot[13360]:         https://github.com/paritytech/polkadot/issues/new
Feb 18 17:45:15 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=exited, status=1/FAILURE
Feb 18 17:45:15 kusama-st systemd[1]: polkadot-validator.service: Failed with result 'exit-code'.

**Comment by bkchr** [comment]
CC @tomaka @romanb

**Comment by tomaka** [comment]
Just like https://github.com/paritytech/polkadot/issues/2428, this is an "impossible bug". None of the code paths can possibly reach the panic.

Are you modifying the source code? Using a custom Rust version? Something like that?

**Comment by andreisid** [comment]
hey, 
I am running a precompiled version that I got from here:  https://github.com/paritytech/polkadot/releases/download/v0.8.28-1/polkadot. 

./polkadot --version
polkadot 0.8.28-1-99043f78-x86_64-linux-gnu

This is my run commnd: ExecStart=/root/polkadot --validator --name stakethat --telemetry-url 'wss://telemetry-backend.w3f.community/submit 1'  --chain kusama
