### ISSUE TITLE
get block error

### ISSUE THREAD

**Issue by xihucuyu888** [paritytech/polkadot#2502]
node version v0.8.28,  polkadot 
"@polkadot/api": "3.10.2-0"
api.rpc.chain.getBlock('0xba00644eec6ba236f3314dc2e1e6bcc1df7aadbe4ebbf3e71412c669c5030f7c') 

logs:
Multiple instances of @polkadot/util-crypto detected, ensure that there is only one package in your dependency tree.
        5.7.1   /Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/api/node_modules/@polkadot/util-crypto
        5.7.1   /Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/metadata/node_modules/@polkadot/util-crypto
Multiple instances of @polkadot/util-crypto detected, ensure that there is only one package in your dependency tree.
        5.7.1   /Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/api/node_modules/@polkadot/util-crypto
        5.7.1   /Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/metadata/node_modules/@polkadot/util-crypto
        5.7.1   /Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/node_modules/@polkadot/util-crypto
Multiple instances of @polkadot/util-crypto detected, ensure that there is only one package in your dependency tree.
        5.7.1   /Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/api/node_modules/@polkadot/util-crypto
        5.7.1   /Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/metadata/node_modules/@polkadot/util-crypto
        5.7.1   /Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/node_modules/@polkadot/util-crypto
        5.7.1   /Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/api-derive/node_modules/@polkadot/util-crypto
block[now].hash=0xba00644eec6ba236f3314dc2e1e6bcc1df7aadbe4ebbf3e71412c669c5030f7c
2021-02-23 14:11:21        REGISTRY: Error: Call: failed decoding balances.transfer:: Struct: failed on args: {"dest":"LookupSource","value":"Compact<Balance>"}:: Balance: Input too large. Found input with 166 bits, expected 128
    at new GenericCall (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/generic/Call.js:147:13)
    at new Type (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/registry.js:340:16)
    at initType (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:69:12)
    at createType (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/registry.js:297:39)
    at Function.decodeExtrinsic (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/extrinsic/v4/Extrinsic.js:47:31)
    at new GenericExtrinsicV4 (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/extrinsic/v4/Extrinsic.js:30:27)
    at new Type (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/registry.js:340:16)
    at initType (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:49:19)
2021-02-23 14:11:21        REGISTRY: Error: createType(Call):: Call: failed decoding balances.transfer:: Struct: failed on args: {"dest":"LookupSource","value":"Compact<Balance>"}:: Balance: Input too large. Found input with 166 bits, expected 128
    at createTypeUnsafe (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:72:11)
    at createType (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/registry.js:297:39)
    at Function.decodeExtrinsic (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/extrinsic/v4/Extrinsic.js:47:31)
    at new GenericExtrinsicV4 (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/extrinsic/v4/Extrinsic.js:30:27)
    at new Type (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/registry.js:340:16)
    at initType (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:69:12)
    at createType (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/registry.js:297:39)
2021-02-23 14:11:21             VEC: Unable to decode on index 1 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding balances.transfer:: Struct: failed on args: {"dest":"LookupSource","value":"Compact<Balance>"}:: Balance: Input too large. Found input with 166 bits, expected 128
2021-02-23 14:11:21        REGISTRY: Error: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding balances.transfer:: Struct: failed on args: {"dest":"LookupSource","value":"Compact<Balance>"}:: Balance: Input too large. Found input with 166 bits, expected 128
    at Object.keys.reduce (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/codec/Struct.js:70:13)
    at Array.reduce (<anonymous>)
    at decodeStructFromObject (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/codec/Struct.js:24:29)
    at decodeStruct (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/codec/Struct.js:111:10)
    at new Struct (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/codec/Struct.js:132:26)
    at new <anonymous> (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/codec/Struct.js:150:9)
    at new Type (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/registry.js:340:16)
    at initType (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:69:12)
    at RpcCore._formatOutput (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/rpc-core/index.js:394:41)
2021-02-23 14:11:21        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding balances.transfer:: Struct: failed on args: {"dest":"LookupSource","value":"Compact<Balance>"}:: Balance: Input too large. Found input with 166 bits, expected 128
(node:2495) UnhandledPromiseRejectionWarning: Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding balances.transfer:: Struct: failed on args: {"dest":"LookupSource","value":"Compact<Balance>"}:: Balance: Input too large. Found input with 166 bits, expected 128
    at createTypeUnsafe (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/types/create/createType.js:72:11)
    at RpcCore._formatOutput (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/rpc-core/index.js:394:41)
    at callWithRegistry (/Users/talian/jadepool-st/jadepool-BN/blockchains/Polkadot/node_modules/@polkadot/rpc-core/index.js:262:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2495) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bkchr** [comment]
Wrong repo, but is solved now
