### ISSUE TITLE
installation on mac (m1)

### ISSUE THREAD

**Issue by pannous** [paritytech/polkadot#2505]
trying to install on a Mac (m1) with your suggested method

`cargo install --git https://github.com/paritytech/polkadot --tag v0.8.9`

fails with error:

`error: multiple packages with binaries found: polkadot, test-parachain-adder-collator`

**Comment by chevdor** [comment]
Hello,

As the message says, there are several binaries in the repo so cargo is not sure *what* you want to install.

If you want to install polkadot only, you can try:
```
cargo install --git https://github.com/paritytech/polkadot --tag v0.8.9 --bin polkadot
```

If you *want it all* :) you can also use:
```
cargo install --git https://github.com/paritytech/polkadot --tag v0.8.9 --bins 
```

**Comment by pannous** [comment]
your solution does not work, neither does adding ` -f polkadot` as suggested elsewhere:  
```
/opt/ai/pytorch/ cargo install --git https://github.com/paritytech/polkadot --tag v0.8.2 --bins     
    Updating git repository `https://github.com/paritytech/polkadot`
error: multiple packages with binaries found: polkadot, test-parachain-adder-collator
/opt/ai/pytorch/ cargo install --git https://github.com/paritytech/polkadot --tag v0.8.2 -f polkadot --bins
    Updating git repository `https://github.com/paritytech/polkadot`
  Installing polkadot v0.8.2 (https://github.com/paritytech/polkadot?tag=v0.8.2#a300f0db)
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/substrate`
error: failed to compile `polkadot v0.8.2 (https://github.com/paritytech/polkadot?tag=v0.8.2#a300f0db)`, intermediate artifacts can be found at `/var/folders/br/2jrjybxx7rg0t0by_hsqkgph0000gn/T/cargo-installesUSef`

Caused by:
  no matching package named `pallet-finality-tracker` found
```

**Comment by bkchr** [comment]
Why you are trying such an old release? Please us the latest release, probably even master.

**Comment by chevdor** [comment]
@pannous so using a fairly recent version and passing the pakage should solve the issue you have. I noticed that `--bin` does not work well with `--git`. You can try that:

```
cargo install --git https://github.com/paritytech/polkadot --tag v0.8.28 -- polkadot 
```

**Comment by bkchr** [comment]
When using `cargo install`, never forget to use `--locked`

**Comment by pannous** [comment]
Thanks

`cargo install --git https://github.com/paritytech/polkadot --tag v0.8.28 --locked -- polkadot`

```
error: failed to run custom build command for `ring v0.16.15`

Caused by:
  process didn't exit successfully: `/var/folders/br/2jrjybxx7rg0t0by_hsqkgph0000gn/T/cargo-install5QXvJ0/release/build/ring-cbbb00f18a1c9a0c/build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("aarch64-apple-darwin")
  HOST = Some("aarch64-apple-darwin")
  CC_aarch64-apple-darwin = None
  CC_aarch64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_aarch64-apple-darwin = None
  CFLAGS_aarch64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("crc,crypto,fp,fp16,lse,neon,ras,rcpc,rdm,v8.1a,v8.2a,v8.3a")

  --- stderr
  running "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/var/folders/br/2jrjybxx7rg0t0by_hsqkgph0000gn/T/cargo-install5QXvJ0/release/build/ring-3603ab6e056e069d/out/aesv8-armx-linux64.o" "/Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S"
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:18:17: error: unexpected token in '.section' directive
  .section .rodata
                  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:28:1: error: unknown directive
  .hidden GFp_aes_hw_set_encrypt_key
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:29:1: error: unknown directive
  .type GFp_aes_hw_set_encrypt_key,%function
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:161:1: error: unknown directive
  .size GFp_aes_hw_set_encrypt_key,.-GFp_aes_hw_set_encrypt_key
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:163:1: error: unknown directive
  .hidden GFp_aes_hw_encrypt
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:164:1: error: unknown directive
  .type GFp_aes_hw_encrypt,%function
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:191:1: error: unknown directive
  .size GFp_aes_hw_encrypt,.-GFp_aes_hw_encrypt
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:193:1: error: unknown directive
  .hidden GFp_aes_hw_decrypt
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:194:1: error: unknown directive
  .type GFp_aes_hw_decrypt,%function
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:221:1: error: unknown directive
  .size GFp_aes_hw_decrypt,.-GFp_aes_hw_decrypt
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:223:1: error: unknown directive
  .hidden GFp_aes_hw_ctr32_encrypt_blocks
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:224:1: error: unknown directive
  .type GFp_aes_hw_ctr32_encrypt_blocks,%function
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:403:1: error: unknown directive
  .size GFp_aes_hw_ctr32_encrypt_blocks,.-GFp_aes_hw_ctr32_encrypt_blocks
  ^
  /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/pregenerated/aesv8-armx-linux64.S:407:19: error: unexpected token in '.section' directive
  .section .note.GNU-stack,"",%progbits
                    ^
  thread 'main' panicked at 'execution failed', /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/build.rs:664:9
  stack backtrace:
     0:        0x10448675c - std::backtrace_rs::backtrace::libunwind::trace::hfb13038f037c000a
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:        0x10448675c - std::backtrace_rs::backtrace::trace_unsynchronized::hfd5696347470fa7d
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x10448675c - std::sys_common::backtrace::_print_fmt::hdf1e7b50816ccd2b
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/sys_common/backtrace.rs:67:5
     3:        0x10448675c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h043213eec1d948a5
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/sys_common/backtrace.rs:46:22
     4:        0x10449e0c4 - core::fmt::write::hf53968076cf4f14e
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/core/src/fmt/mod.rs:1092:17
     5:        0x1044829e8 - std::io::Write::write_fmt::h28b0246eee567fa4
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/io/mod.rs:1568:15
     6:        0x1044886fc - std::sys_common::backtrace::_print::h7a62d6bcf54b6634
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/sys_common/backtrace.rs:49:5
     7:        0x1044886fc - std::sys_common::backtrace::print::hb53039f14ad1e4cc
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/sys_common/backtrace.rs:36:9
     8:        0x1044886fc - std::panicking::default_hook::{{closure}}::h8d1966a8d6a15176
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/panicking.rs:208:50
     9:        0x104488224 - std::panicking::default_hook::h9e61206a690d3893
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/panicking.rs:225:9
    10:        0x104488cb0 - std::panicking::rust_panic_with_hook::hd1308496ca12fe75
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/panicking.rs:591:17
    11:        0x10444d66c - std::panicking::begin_panic::{{closure}}::h1581a49746d0f04b
    12:        0x104439fc8 - std::sys_common::backtrace::__rust_end_short_backtrace::h0aa51a83b527127e
    13:        0x1044a1d08 - std::panicking::begin_panic::h2175a395e1820874
    14:        0x10440b380 - build_script_build::run_command::h8414804454cb5c61
    15:        0x10440a3f8 - build_script_build::compile::h8724c642176de6ba
    16:        0x104409fdc - build_script_build::build_library::{{closure}}::h3a0a8d1dd8662a12
    17:        0x104407b14 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h199912ee5345d5ef
    18:        0x104411788 - core::option::Option<T>::map::h2f2ee47511bd3149
    19:        0x104417b34 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::hc6bb8f3cc9598a64
    20:        0x10440d154 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h2b68ec1f698b2308
    21:        0x10440fb38 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h6b78bf0fee422f9e
    22:        0x10440f5a4 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::hbe20ecc1a2ba0386
    23:        0x10441810c - core::iter::traits::iterator::Iterator::collect::hbb714c7d2aef5eb6
    24:        0x1044098c4 - build_script_build::build_library::hd2f34c6690dc9f66
    25:        0x10440968c - build_script_build::build_c_code::{{closure}}::ha17c25db7bf2d5d6
    26:        0x104414dc0 - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each::h2cbdc28dceada23a
    27:        0x104409280 - build_script_build::build_c_code::h8ddd6171516e1a66
    28:        0x104408418 - build_script_build::ring_build_rs_main::hfca0b1c8432a51fe
    29:        0x104407d2c - build_script_build::main::hcee40c2745e98658
    30:        0x104410868 - core::ops::function::FnOnce::call_once::h493e5b087a096a66
    31:        0x10441230c - std::sys_common::backtrace::__rust_begin_short_backtrace::h5e5db4e733e35fc6
    32:        0x10441069c - std::rt::lang_start::{{closure}}::h43409b31c7bcd030
    33:        0x104489010 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf5ddf54157e6c726
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/core/src/ops/function.rs:259:13
    34:        0x104489010 - std::panicking::try::do_call::h44e5ecc5a9e8a72f
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/panicking.rs:379:40
    35:        0x104489010 - std::panicking::try::h75f955d26adda2e7
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/panicking.rs:343:19
    36:        0x104489010 - std::panic::catch_unwind::h118d1549ab28cd4f
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/panic.rs:431:14
    37:        0x104489010 - std::rt::lang_start_internal::h11dfd92f6b2513dc
                                 at /rustc/a15f484b918a4533ad633ea903ccce82910af342/library/std/src/rt.rs:51:25
    38:        0x104410678 - std::rt::lang_start::h72fc8f941dbf71ec
    39:        0x10440ce4c - _main
```

I guess Apple M1 is just not supported yet ...

**Comment by bkchr** [comment]
Yeah. @xlc can say what you need to compile it

**Comment by xlc** [comment]
Building on M1 requires few specific override (rust-rocksdb & wasmtime) and you will also need few `cargo update -p` for `ring`, `libc` and maybe few other crates as well and on some commit you just won't be able to find a combination without conflicts.

The easiest why is build on x86 Mac and copy the binary over and run it under rosetta 2.

**Comment by crishoj** [comment]
I'm curious if anyone has been successful running a node on M1 natively, i.e. without rosetta 2?

**Comment by ordian** [comment]
cc #2899

**Comment by bjweaver** [comment]
I compiled 0.9.5 on an M1 MAC, but it crashes after a while with the following error.. 
06-21 18:55:12 Our view contains 0x44b7…0eb5 but the overseer never told use we should work on this added=0x44b7…0eb5
zsh: segmentation fault

polkadot 0.9.5-3ce09da50-aarch64-macos

**Comment by drahnr** [comment]
@bjweaver : 
The first issue would need a full backtrace, without this is very difficult to diagnose, could you please file an issue if it persists with the current latest release ( `0.9.18` )

The second error is tracked within https://github.com/paritytech/polkadot/issues/5318 , but I am not sure that's all to it.

---

We have multiple users of M1's and to my knowledge all issues are resolved by now. Feel free to open a new issue if there are any further issues.

Thank you!
