### ISSUE TITLE
Bug report from node

### ISSUE THREAD

**Issue by vindberg** [paritytech/polkadot#257]
Hi guys, we are getting this error now after a day of synching. Its happening for every new block:

```
> May 09 09:27:57 PolkadotTestnetNode polkadot[16383]: 2019-05-09 09:27:57 Imported #1249049 (0x3a2c…79d9)
> May 09 09:27:59 PolkadotTestnetNode polkadot[16383]: 2019-05-09 09:27:59 Idle (39 peers), best: #1249049 (0x3a2c…79d9), finalized #1249049 (0x3a2c…79d9), :arrow_down: 47.3kiB/s :arrow_up: 47.0kiB/s
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]: Hash: given=4db696aadfefd85de2944776e0fbff390c5bbbe4ee2e57cee7740ede186b4225, expected=6ce1a8f16bf808f85c47042947044c4d96779b9ec73a9e678fd5bab41c65681c
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]: ====================
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]: stack backtrace:
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:    0: substrate_panic_handler::set::{{closure}}::h3ba448d11c9d4906 (0x55d46c351e7f)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:    1: rust_panic_with_hook (0x55d46c540ea8)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:              at src/libstd/panicking.rs:482
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:    2: std::panicking::begin_panic::hb8979dca35e807e1 (0x55d46bbc8534)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:    3: <srml_executive::Executive<System, Block, Context, Payment, AllModules>>::execute_block::h56992249794675f5 (0x55d46bc0ea0d)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:    4: polkadot_runtime::api::dispatch::hb20b396d599b26e9 (0x55d46bc278c6)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:    5: std::panicking::try::do_call::h36122726b3debcb0 (0x55d46bba2001)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:    6: __rust_maybe_catch_panic (0x55d46c547109)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:              at src/libpanic_unwind/lib.rs:87
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:    7: substrate_executor::native_executor::safe_call::h636d6cc4e187df3e (0x55d46bba1ce2)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:    8: <std::thread::local::LocalKey<T>>::with::hcb506705eb873939 (0x55d46bba1706)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:    9: <polkadot_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h2e0538b9eaf21711 (0x55d46bba106c)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   10: <std::thread::local::LocalKey<T>>::with::hb025f199edb8c04d (0x55d46b9381d7)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   11: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_aux::h9a8b76e400f45a8f (0x55d46b7dbe62)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   12: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_call_with_native_else_wasm_strategy::h23d9d5be8e2a41cb (0x55d46b827012)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   13: <substrate_state_machine::StateMachine<'a, H, B, T, O, Exec>>::execute_using_consensus_failure_handler::h5bce23647d941d01 (0x55d46b7f9a41)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   14: <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::hed5b9d920b69bb08 (0x55d46b65c581)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   15: <substrate_client::client::Client<B, E, Block, RA>>::lock_import_and_run::{{closure}}::h1da4180bcefffda8 (0x55d46b9e96fa)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   16: <substrate_client::client::Client<B, E, Block, RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h889676ea46b082ca (0x55d46b9c6ce1)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   17: <substrate_finality_grandpa::import::GrandpaBlockImport<B, E, Block, RA, PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h30c8dd748be02801 (0x55d46b761b8c)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   18: substrate_consensus_common::import_queue::import_single_block::he627043a777f6ab9 (0x55d46b58c07d)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   19: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::import_a_batch_of_blocks::h1f99b95bd139a6f2 (0x55d46b5d0df8)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   20: std::sys_common::backtrace::__rust_begin_short_backtrace::h77a4fbe70b134ab1 (0x55d46bae27de)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   21: std::panicking::try::do_call::h5fe1a5170b39e751 (0x55d46b9d478d)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   22: __rust_maybe_catch_panic (0x55d46c547109)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:              at src/libpanic_unwind/lib.rs:87
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   23: <F as alloc::boxed::FnBox<A>>::call_box::h28881f186b02fe24 (0x55d46b5aab3e)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   24: call_once<(),()> (0x55d46c54644d)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:              at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/liballoc/boxed.rs:759
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:       start_thread
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:              at src/libstd/sys_common/thread.rs:14
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:       thread_start
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:              at src/libstd/sys/unix/thread.rs:81
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   25: start_thread (0x7f90def656da)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   26: __clone (0x7f90dea7688e)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:   27: <unknown> (0x0)
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]: Thread 'ImportQueueWorker' panicked at 'Storage root must match that calculated.', /home/polka/.cargo/git/checkouts/substrate-7e08433d4c370a21/9de71d5/srml/executive/src/lib.rs:243
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]: This is a bug. Please report it at:
> May 09 09:28:01 PolkadotTestnetNode polkadot[16383]:        
```

 

Our version is: git rev-parse HEAD
7f4db378ac7ade31dad5657af4069686d9e95595

Hope this can be of help to you.
Best,
Anders
Validators.com

**Comment by bkchr** [comment]
Do you still have the problem?
