### ISSUE TITLE
Westend syncing failed while using docker

### ISSUE THREAD

**Issue by DavidTranDucVL** [paritytech/polkadot#2633]
I'm trying to sync up Westend chain with docker. Initial docker run command:
```
docker run --name "WestendDocker" -p 9944:9944 parity/polkadot:v0.8.24 --chain westend --rpc-external --ws-external
```

At some point it failed, here's full log:
```
$ docker start -a WestendDocker 
2021-03-16 05:11:15.087 main INFO sc_cli::runner  Parity Polkadot
2021-03-16 05:11:15.087 main INFO sc_cli::runner  ✌️  version 0.8.24-5cbc418-x86_64-linux-gnu
2021-03-16 05:11:15.087 main INFO sc_cli::runner  ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
2021-03-16 05:11:15.087 main INFO sc_cli::runner  📋 Chain specification: Westend
2021-03-16 05:11:15.087 main INFO sc_cli::runner  🏷  Node name: animated-memory-0427
2021-03-16 05:11:15.087 main INFO sc_cli::runner  👤 Role: FULL
2021-03-16 05:11:15.087 main INFO sc_cli::runner  💾 Database: RocksDb at /polkadot/.local/share/polkadot/chains/westend2/db
2021-03-16 05:11:15.087 main INFO sc_cli::runner  ⛓  Native runtime: westend-43 (parity-westend-1.tx3.au2)
2021-03-16 05:11:15.192 main INFO sub-libp2p  🏷  Local node identity is: 12D3KooWHjRMBLkoY5Sv4vT95kFFMT6oxAms86bv5dLvPkoUFSxV (legacy representation: 12D3KooWHjRMBLkoY5Sv4vT95kFFMT6oxAms86bv5dLvPkoUFSxV)
2021-03-16 05:11:15.194 main INFO sc_service::builder  📦 Highest known block at #2143450
2021-03-16 05:11:15.194 tokio-runtime-worker INFO substrate_prometheus_endpoint::known_os  〽️ Prometheus server started at 127.0.0.1:9615
2021-03-16 05:11:16.766 tokio-runtime-worker INFO sub-libp2p  🔍 Discovered new external address for our node: /ip4/185.98.208.237/tcp/30333/p2p/12D3KooWHjRMBLkoY5Sv4vT95kFFMT6oxAms86bv5dLvPkoUFSxV
2021-03-16 05:11:20.199 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #2143450 (0x9c7c…29b6), finalized #2143232 (0xb89b…3ba1), ⬇ 3.9kiB/s ⬆ 2.4kiB/s
2021-03-16 05:11:25.200 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #2143450 (0x9c7c…29b6), finalized #2143232 (0xb89b…3ba1), ⬇ 1.2kiB/s ⬆ 0.5kiB/s
2021-03-16 05:11:30.200 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #2143450 (0x9c7c…29b6), finalized #2143232 (0xb89b…3ba1), ⬇ 1.2kiB/s ⬆ 1.1kiB/s
2021-03-16 05:11:35.200 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #2143450 (0x9c7c…29b6), finalized #2143232 (0xb89b…3ba1), ⬇ 2.0kiB/s ⬆ 1.4kiB/s
2021-03-16 05:11:40.201 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #2143450 (0x9c7c…29b6), finalized #2143232 (0xb89b…3ba1), ⬇ 2.2kiB/s ⬆ 1.8kiB/s
2021-03-16 05:11:45.201 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #2143450 (0x9c7c…29b6), finalized #2143232 (0xb89b…3ba1), ⬇ 3.2kiB/s ⬆ 2.9kiB/s
2021-03-16 05:11:50.201 tokio-runtime-worker INFO substrate  ⚙️  Syncing  0.0 bps, target=#4795884 (1 peers), best: #2143450 (0x9c7c…29b6), finalized #2143232 (0xb89b…3ba1), ⬇ 8.4kiB/s ⬆ 7.6kiB/s

====================

Version: 0.8.24-5cbc418-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
   2: std::panicking::begin_panic
   3: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
   4: <westend_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,westend_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<westend_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<westend_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<westend_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<westend_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<westend_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<westend_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<westend_runtime::Runtime>)>>>>::execute_block
   5: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
   6: std::thread::local::LocalKey<T>::with
   7: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
   8: sc_executor::wasm_runtime::RuntimeCache::with_instance
   9: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  10: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  11: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  12: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  13: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  14: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  15: sp_api::Core::execute_block_with_context
  16: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  17: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  18: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  19: sp_consensus::import_queue::import_single_block_metered
  20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  21: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  22: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
  23: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  24: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  25: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: std::thread::local::LocalKey<T>::with
  28: futures_executor::local_pool::block_on
  29: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  30: tokio::runtime::task::harness::Harness<T,S>::poll
  31: tokio::runtime::blocking::pool::Inner::run
  32: tokio::runtime::context::enter
  33: std::sys_common::backtrace::__rust_begin_short_backtrace
  34: core::ops::function::FnOnce::call_once{{vtable.shim}}
  35: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/sys/unix/thread.rs:87
  36: start_thread
  37: clone


Thread 'tokio-runtime-worker' panicked at 'Transaction would exhausts the block limits', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:13

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new


====================

Version: 0.8.24-5cbc418-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
   2: std::panicking::begin_panic
   3: <sp_runtime::SignatureBatching as core::ops::drop::Drop>::drop
   4: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
   5: <westend_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,westend_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<westend_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<westend_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<westend_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<westend_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<westend_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<westend_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<westend_runtime::Runtime>)>>>>::execute_block
   6: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
   7: std::thread::local::LocalKey<T>::with
   8: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
   9: sc_executor::wasm_runtime::RuntimeCache::with_instance
  10: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  11: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  12: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  13: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  14: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  15: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  16: sp_api::Core::execute_block_with_context
  17: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  18: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  19: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  20: sp_consensus::import_queue::import_single_block_metered
  21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  22: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  23: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
  24: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  25: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  26: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  28: std::thread::local::LocalKey<T>::with
  29: futures_executor::local_pool::block_on
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  31: tokio::runtime::task::harness::Harness<T,S>::poll
  32: tokio::runtime::blocking::pool::Inner::run
  33: tokio::runtime::context::enter
  34: std::sys_common::backtrace::__rust_begin_short_backtrace
  35: core::ops::function::FnOnce::call_once{{vtable.shim}}
  36: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/sys/unix/thread.rs:87
  37: start_thread
  38: clone


Thread 'tokio-runtime-worker' panicked at 'Signature verification has not been called before `SignatureBatching::drop`', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/647ad15/primitives/runtime/src/lib.rs:799

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

thread panicked while panicking. aborting.
```

**Comment by bkchr** [comment]
Please use the latest release.
