### ISSUE TITLE
error in auction/slot module

### ISSUE THREAD

**Issue by yrong** [paritytech/polkadot#2641]
```
polkadot --chain=westend-dev --alice
====================

Version: 0.8.29-6b474a44-x86_64-linux-gnu

   0: sp_panic_handler::panic_hook
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/primitives/panic-handler/src/lib.rs:150:18
   1: sp_panic_handler::set::{{closure}}
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/primitives/panic-handler/src/lib.rs:60:4
   2: std::panicking::rust_panic_with_hook
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:495:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:493:5
   6: core::panicking::panic_fmt
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/core/src/panicking.rs:92:14
   7: core::panicking::panic
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/core/src/panicking.rs:50:5
   8: polkadot_runtime_common::slots::Module<T>::manage_lease_period_start
             at runtime/common/src/slots.rs:235:5
   9: <polkadot_runtime_common::slots::Module<T> as frame_support::traits::OnInitialize<<T as frame_system::pallet::Config>::BlockNumber>>::on_initialize
             at runtime/common/src/slots.rs:149:5
  10: <(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/frame/support/src/traits.rs:1581:1
  11: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::initialize_block_impl
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/frame/executive/src/lib.rs:278:4
  12: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::initialize_block
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/frame/executive/src/lib.rs:242:3
  13: <westend_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,westend_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<westend_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<westend_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<westend_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<westend_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<westend_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<westend_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<westend_runtime::Runtime>)>>>>::initialize_block
             at runtime/westend/src/lib.rs:967:4
  14: sp_api::runtime_decl_for_Core::initialize_block_native_call_generator::{{closure}}
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/primitives/api/src/lib.rs:650:1
  15: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call::{{closure}}::{{closure}}
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/service/src/client/call_executor.rs:253:29
  16: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call::{{closure}}::{{closure}}
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/executor/src/native_executor.rs:514:61
  17: std::panicking::try::do_call
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  18: __rust_try
  19: std::panicking::try
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  20: std::panic::catch_unwind
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  21: sc_executor::native_executor::with_externalities_safe::{{closure}}
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/executor/src/native_executor.rs:62:4
  22: environmental::using::{{closure}}
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:126:3
  23: std::thread::local::LocalKey<T>::try_with
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  24: std::thread::local::LocalKey<T>::with
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  25: environmental::using
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:107:2
  26: sp_externalities::scope_limited::ext::using
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:253:5
  27: sp_externalities::scope_limited::set_and_run_with_externalities
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/primitives/externalities/src/scope_limited.rs:30:2
  28: sc_executor::native_executor::with_externalities_safe
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/executor/src/native_executor.rs:56:2
  29: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call::{{closure}}
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/executor/src/native_executor.rs:514:17
  30: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/executor/src/native_executor.rs:184:5
  31: sc_executor::wasm_runtime::VersionedRuntime::with_instance
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/executor/src/wasm_runtime.rs:94:18
  32: sc_executor::wasm_runtime::RuntimeCache::with_instance
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/executor/src/wasm_runtime.rs:273:6
  33: sc_executor::native_executor::WasmExecutor::with_instance
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/executor/src/native_executor.rs:173:9
  34: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/executor/src/native_executor.rs:470:16
  35: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/primitives/state-machine/src/lib.rs:423:31
  36: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/primitives/state-machine/src/lib.rs:555:7
  37: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/service/src/client/call_executor.rs:251:5
  38: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/service/src/client/client.rs:1671:3
  39: sp_api::runtime_decl_for_Core::initialize_block_call_api_at
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/primitives/api/src/lib.rs:650:1
  40: <westend_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl::{{closure}}
             at runtime/westend/src/lib.rs:956:1
  41: westend_runtime::RuntimeApiImpl<Block,C>::call_api_at
             at runtime/westend/src/lib.rs:956:1
  42: <westend_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl
             at runtime/westend/src/lib.rs:956:1
  43: sp_api::Core::initialize_block_with_context
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/primitives/api/src/lib.rs:650:1
  44: sc_block_builder::BlockBuilder<Block,A,B>::new
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/block-builder/src/lib.rs:176:3
  45: <sc_service::client::client::Client<B,E,Block,RA> as sc_block_builder::BlockBuilderProvider<B,Block,sc_service::client::client::Client<B,E,Block,RA>>>::new_block_at
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/service/src/client/client.rs:1304:3
  46: sc_basic_authorship::basic_authorship::Proposer<B,Block,C,A,PR>::propose_with::{{closure}}
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/basic-authorship/src/basic_authorship.rs:273:27
  47: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  48: <sc_basic_authorship::basic_authorship::Proposer<B,Block,C,A,PR> as sp_consensus::Proposer<Block>>::propose::{{closure}}
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/basic-authorship/src/basic_authorship.rs:235:14
  49: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  50: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  51: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/service/src/task_manager/prometheus_future.rs:61:3
  52: <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:361:9
  53: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/future/catch_unwind.rs:32:42
  54: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  55: std::panicking::try::do_call
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  56: __rust_try
  57: std::panicking::try
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  58: std::panic::catch_unwind
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  59: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/future/catch_unwind.rs:32:9
  60: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  61: futures_util::future::future::FutureExt::poll_unpin
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/future/mod.rs:561:9
  62: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/select.rs:92:36
  63: sc_service::task_manager::SpawnTaskHandle::spawn_inner::{{closure}}
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/service/src/task_manager/mod.rs:105:11
  64: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  65: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.4/src/lib.rs:258:9
  66: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  67: futures_executor::local_pool::block_on::{{closure}}
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:317:23
  68: futures_executor::local_pool::run_executor::{{closure}}
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:87:37
  69: std::thread::local::LocalKey<T>::try_with
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  70: std::thread::local::LocalKey<T>::with
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  71: futures_executor::local_pool::run_executor
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:83:5
  72: futures_executor::local_pool::block_on
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:317:5
  73: sc_cli::runner::Runner<C>::new::{{closure}}::{{closure}}
             at /home/ronyang/.cargo/git/checkouts/substrate-7e08433d4c370a21/da7ca4d/client/cli/src/runner.rs:133:44
  74: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/task.rs:38:21
  75: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:173:17
  76: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/loom/std/unsafe_cell.rs:14:9
  77: tokio::runtime::task::core::Core<T,S>::poll
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:158:13
  78: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:107:27
  79: core::ops::function::FnOnce::call_once
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  80: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  81: std::panicking::try::do_call
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  82: __rust_try
  83: std::panicking::try
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  84: std::panic::catch_unwind
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  85: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:89:19
  86: tokio::runtime::task::raw::poll
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:104:5
  87: tokio::runtime::task::raw::RawTask::poll
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:66:18
  88: tokio::runtime::task::Notified<S>::run
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/mod.rs:169:9
  89: tokio::runtime::blocking::pool::Inner::run
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/pool.rs:230:17
  90: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/pool.rs:210:21
  91: tokio::runtime::context::enter
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/context.rs:72:5
  92: tokio::runtime::handle::Handle::enter
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/handle.rs:76:9
  93: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/ronyang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/pool.rs:209:17
  94: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  95: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  96: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  97: std::panicking::try::do_call
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  98: __rust_try
  99: std::panicking::try
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
 100: std::panic::catch_unwind
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
 101: std::thread::Builder::spawn_unchecked::{{closure}}
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
 102: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /home/ronyang/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
 103: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys/unix/thread.rs:71:17
 104: start_thread
 105: clone


Thread 'tokio-runtime-worker' panicked at 'assertion failed: res.is_ok()', /ssd/myrust/polkadot/runtime/common/src/slots.rs:235

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

2021-03-18 19:31:24.444   WARN tokio-runtime-worker slots: Encountered consensus error: ClientImport("Blockchain(RuntimeApiError(Application(Execution(RuntimePanicked(\"assertion failed: res.is_ok()\")))))")    
2021-03-18 19:31:29.141   INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #99 (0x349b…2100), finalized #49 (0x926c…8781), ⬇ 0 ⬆ 0    
2021-03-18 19:31:30.217   INFO tokio-runtime-worker sc_basic_authorship::basic_authorship: 🙌 Starting consensus session on top of parent 0x349b7e474e608dff7ded0bc78626f12e8b45318241bdadc66deb8c8bfa2b2100    

```

**Comment by bkchr** [comment]
Would be nice if you could describe what you have done :) 

CC @shawntabrizi

**Comment by shawntabrizi** [comment]
Yeah it is not clear at all to me what is happening here. You are just trying to start a node?

Did you make sure to purge chain?

**Comment by yrong** [comment]
@shawntabrizi just setup  a dev envirionment and try the new parachain feature like creat/dissolve fund from portal, can't remember which action/extrinsic trigger the error and it dissapear after restart. see something like `This is a bug. Please report it` in log so report it here.  If does not help just ignore.

**Comment by shawntabrizi** [comment]
@yrong if you can provide reproduction steps then we can investigate further, but I don't really have anything to go off of here.

Feel free to reopen if you can identity that issue.

**Comment by shawntabrizi** [comment]
Ah the issue here may be caused if you did not register the para as a parathread before you tried to give it a slot?

Are you running your node using a debug build?

**Comment by yrong** [comment]
Exactly

**Comment by shawntabrizi** [comment]
I added a checkbox here for checking that a para is onboarded before processing a bid: https://github.com/paritytech/polkadot/issues/2624
