### ISSUE TITLE
availability-recovery: test is failing spuriously

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot#2838]
#2837
https://gitlab.parity.io/parity/polkadot/-/jobs/886575
```
[2021-04-07T11:33:25Z TRACE polkadot_availability_recovery::tests] received message msg=NetworkBridge(SendRequests([ChunkFetching(OutgoingRequest { peer: Authority(Public(306721211d5404bd9da88e0204360a1a9ab8b87c66c1bc2fcdd37f3c2222cc20 (5DAAnrj7...))), payload: ChunkFetchingRequest { candidate_hash: 0x84a8417987f93d6ee704834bc817e03fc7d9f6d782101ecbb98676933838c31c, index: ValidatorIndex(4) }, pending_response: Sender { inner: Inner { complete: false, data: Lock { locked: false, data: UnsafeCell }, rx_task: Lock { locked: false, data: UnsafeCell }, tx_task: Lock { locked: false, data: UnsafeCell } } } })], TryConnect)) 
[2021-04-07T11:33:25Z TRACE polkadot_availability_recovery::tests] waiting for message ... 
[2021-04-07T11:33:25Z TRACE polkadot_availability_recovery::tests] received message msg=NetworkBridge(SendRequests([ChunkFetching(OutgoingRequest { peer: Authority(Public(d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...))), payload: ChunkFetchingRequest { candidate_hash: 0x84a8417987f93d6ee704834bc817e03fc7d9f6d782101ecbb98676933838c31c, index: ValidatorIndex(1) }, pending_response: Sender { inner: Inner { complete: false, data: Lock { locked: false, data: UnsafeCell }, rx_task: Lock { locked: false, data: UnsafeCell }, tx_task: Lock { locked: false, data: UnsafeCell } } } })], TryConnect)) 
[2021-04-07T11:33:25Z TRACE polkadot_availability_recovery::tests] sending message msg=RecoverAvailableData(CandidateReceipt { descriptor: CandidateDescriptor { para_id: Id(0), relay_parent: 0x0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a, collator: Public(0000000000000000000000000000000000000000000000000000000000000000 (5C4hrfjw...)), persisted_validation_data_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, pov_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, erasure_root: 0x0000000000000000000000000000000000000000000000000000000000000000, signature: Signature(00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000), para_head: 0x0000000000000000000000000000000000000000000000000000000000000000 }, commitments_hash: 0x0000000000000000000000000000000000000000000000000000000000000000 }, 10, None, Sender { inner: Inner { complete: false, data: Lock { locked: false, data: UnsafeCell }, rx_task: Lock { locked: false, data: UnsafeCell }, tx_task: Lock { locked: false, data: UnsafeCell } } }) 
[2021-04-07T11:33:25Z TRACE polkadot_availability_recovery] handle_recover; receipt=CandidateReceipt { descriptor: CandidateDescriptor { para_id: Id(0), relay_parent: 0x0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a, collator: Public(0000000000000000000000000000000000000000000000000000000000000000 (5C4hrfjw...)), persisted_validation_data_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, pov_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, erasure_root: 0x0000000000000000000000000000000000000000000000000000000000000000, signature: Signature(00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000), para_head: 0x0000000000000000000000000000000000000000000000000000000000000000 }, commitments_hash: 0x0000000000000000000000000000000000000000000000000000000000000000 } session_index=10 backing_group=None response_sender=Sender { inner: Inner { complete: false, data: Lock { locked: false, data: UnsafeCell }, rx_task: Lock { locked: false, data: UnsafeCell }, tx_task: Lock { locked: false, data: UnsafeCell } } } subsystem="parachain::availability-recovery"
[2021-04-07T11:33:25Z TRACE polkadot_availability_recovery::tests] waiting for message ... 
[2021-04-07T11:33:25Z TRACE polkadot_availability_recovery::tests] received message msg=NetworkBridge(SendRequests([ChunkFetching(OutgoingRequest { peer: Authority(Public(8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48 (5FHneW46...))), payload: ChunkFetchingRequest { candidate_hash: 0x84a8417987f93d6ee704834bc817e03fc7d9f6d782101ecbb98676933838c31c, index: ValidatorIndex(2) }, pending_response: Sender { inner: Inner { complete: true, data: Lock { locked: false, data: UnsafeCell }, rx_task: Lock { locked: false, data: UnsafeCell }, tx_task: Lock { locked: false, data: UnsafeCell } } } })], TryConnect)) 
thread 'tests::availability_is_recovered_from_chunks_if_no_group_provided' panicked at 'assertion failed: `NetworkBridge(SendRequests([ChunkFetching(OutgoingRequest { peer: Authority(Public(8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48 (5FHneW46...))), payload: ChunkFetchingRequest { candidate_hash: 0x84a8417987f93d6ee704834bc817e03fc7d9f6d782101ecbb98676933838c31c, index: ValidatorIndex(2) }, pending_response: Sender { inner: Inner { complete: true, data: Lock { locked: false, data: UnsafeCell }, rx_task: Lock { locked: false, data: UnsafeCell }, tx_task: Lock { locked: false, data: UnsafeCell } } } })], TryConnect))` does not match `AllMessages::RuntimeApi(RuntimeApiMessage::Request(relay_parent,
                                                   RuntimeApiRequest::SessionInfo(session_index,
                                                                                  tx)))`', node/network/availability-recovery/src/tests.rs:187:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: std::thread::local::LocalKey<T>::with
   5: polkadot_availability_recovery::tests::availability_is_recovered_from_chunks_if_no_group_provided
   6: core::ops::function::FnOnce::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failures:
    tests::availability_is_recovered_from_chunks_if_no_group_provided
```

**Comment by ordian** [comment]
the failure is no longer reproducible after #2813 which #2837 did not include (old parent)
