### ISSUE TITLE
'Critical database error: Background(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }))'

### ISSUE THREAD

**Issue by m-saxemberg** [paritytech/polkadot#2965]
The following message appeared after an error in the Polkadot client. There is plenty of space on disk, ram and the latest client version is running in addition to parity db. The difference now is that the validator could restart easily without having to purge the database.

EDIT: the same problem continues to appear after restarting, synchronizing and running normally for a few minutes. The validator cannot run normally anymore, it only works for a little while.

```
2021-04-30 08:40:27  Background worker error: IO Error: failed to fill whole buffer                                                                             
                                                                              
 ====================    
 Version: 0.8.30-4b86755c3-x86_64-linux-gnu                                      
   0: sp_panic_handler::set::{{closure}}                                        
   1: std::panicking::rust_panic_with_hook                                      
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/p
anicking.rs:595:17                                                              
   2: std::panicking::begin_panic_handler::{{closure}} 
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13                                                                      
 3: std::sys_common::backtrace::__rust_end_short_backtrace                                 at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/s
ys_common/backtrace.rs:141:18                                                   

 4: rust_begin_unwind                           
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/p
anicking.rs:493:5                                                               
   5: std::panicking::begin_panic_fmt                                           
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/$
anicking.rs:435:5                                                               
   6: <sc_client_db::parity_db::DbAdapter as sp_database::Database<H>>::commit
   7: sc_client_db::Backend<Block>::try_commit_operation                        
   8: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::
commit_operation                                                                
   9: <sc_service::client::client::Client<B,E,Block,RA> as sc_client_api::backend::AuxStore>::insert_aux                                                        
  10: <sc_finality_grandpa::environment::Environment<B,Block,C,N,SC,VR> as final
ity_grandpa::voter::Environment<<Block as sp_runtime::traits::Block>::Hash,<<Blo
ck as sp_runtime::traits::Block>::Header as sp_runtime::traits::Header>::Number>
>::completed                                           
  11: <finality_grandpa::voter::Voter<H,N,E,GlobalIn,GlobalOut> as core::future::future::Future>::poll                                                            12: <sc_finality_grandpa::VoterWork<B,Block,C,N,SC,VR> as core::future::future::Future>::poll                                                                 
  13: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Fu
ture>::poll                                       
  14: <futures_util::future::select::Select<A,B> as core::future::future::Future
>::poll                                                                         
  15: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Fu
ture>::poll                                                                     
  16: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Fu
ture>::poll                                                                   
  17: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core:
:future::future::Future>::poll         
commit_operation                                                                
  18: <futures_util::future::select::Select<A,B> as core::future::future::Future
>::poll                                                                           
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Futur
e>::poll          
  20: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  21: std::thread::local::LocalKey<T>::with
  22: futures_executor::local_pool::block_on
  23: tokio::runtime::task::core::Core<T,S>::poll                                 
  24: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once     
  25: tokio::runtime::task::harness::Harness<T,S>::poll                                                             
  26: tokio::runtime::blocking::pool::Inner::run
  27: tokio::runtime::context::enter
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}                    
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src
/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src
/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start                         
             at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17                                                         
  31: start_thread
  32: clone                                                                   
                                           
                                            
Thread 'tokio-runtime-worker' panicked at 'Critical database error: Background(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }))', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/3655f9b/client/db/src/parity_db.rs:30                                             
                                                
This is a bug. Please report it at: 
                                                              
        https://github.com/paritytech/polkadot/issues/new                      
                                                                  `
```

**Comment by bkchr** [comment]
Cc @arkpar

**Comment by m-saxemberg** [comment]
now there is a .7z copy of the blockchain available upon request.

**Comment by arkpar** [comment]
> now there is a .7z copy of the blockchain available upon request.

Would be great to get that copy @m-saxemberg

**Comment by m-saxemberg** [comment]
PM on element sent.

**Comment by m-saxemberg** [comment]
Upload is complete

**Comment by arkpar** [comment]
I've finally got to testing with the provided database and could not reproduce the issue. It synced from block ~4.8m to the head of the chain and continued syncing after that for an hour. 

@m-saxemberg was that a cloud or a physical machine? Did switching to rocksdb help?

**Comment by m-saxemberg** [comment]
Bare metal / dedicated server and yes switching to rocksdb solved it.

**Comment by bkchr** [comment]
Probably was fixed already. There was no update here since more than 1 year.
