### ISSUE TITLE
panic - tokio-runtime-worker  assertion failed: _old_auth.is_some()

### ISSUE THREAD

**Issue by bjweaver** [paritytech/polkadot#2998]
0.9.0 node on Kusama chain panicked with the following logs:
```
Thread 'tokio-runtime-worker' panicked at 'assertion failed: _old_auth.is_some()', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/dc9acd2/client/authority-discovery/src/worker/addr_cache.rs:84
```

Log:
```
====================
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]: Version: 0.9.0-b5519e768-x86_64-linux-gnu
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:    0: sp_panic_handler::set::{{closure}}
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:    1: std::panicking::rust_panic_with_hook
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:              at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:    2: std::panicking::begin_panic_handler::{{closure}}
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:              at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:495:13
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:              at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:    4: rust_begin_unwind
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:              at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:    5: core::panicking::panic_fmt
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:              at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:    6: core::panicking::panic
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:              at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:    7: sc_authority_discovery::worker::addr_cache::AddrCache::insert
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:    8: sc_authority_discovery::worker::Worker<Client,Network,Block,DhtEventStream>::run::{{closure}}
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:    9: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   11: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   12: tokio::runtime::task::core::Core<T,S>::poll
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   13: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   14: tokio::runtime::task::harness::Harness<T,S>::poll
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   15: std::thread::local::LocalKey<T>::with
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   16: tokio::runtime::thread_pool::worker::Context::run_task
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   17: tokio::runtime::thread_pool::worker::Context::run
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   18: tokio::macros::scoped_tls::ScopedKey<T>::set
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   19: tokio::runtime::thread_pool::worker::run
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   20: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   21: tokio::runtime::task::core::Core<T,S>::poll
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   23: tokio::runtime::task::harness::Harness<T,S>::poll
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   24: tokio::runtime::blocking::pool::Inner::run
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   25: tokio::runtime::context::enter
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   26: std::sys_common::backtrace::__rust_begin_short_backtrace
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   27: core::ops::function::FnOnce::call_once{{vtable.shim}}
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:              at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:              at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:       std::sys::unix::thread::Thread::new::thread_start
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:              at rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   29: start_thread
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:   30: clone
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]: Thread 'tokio-runtime-worker' panicked at 'assertion failed: _old_auth.is_some()', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/dc9acd2/client/authority-discovery/src/worker/addr_cache.rs:84
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]: This is a bug. Please report it at:
May 08 19:29:33 ip-10-10-28-226 polkadot[29537]:         https://github.com/paritytech/polkadot/issues/new
May 08 19:29:33 ip-10-10-28-226 systemd[1]: polkadot.service: Main process exited, code=exited, status=1/FAILURE
May 08 19:29:33 ip-10-10-28-226 systemd[1]: polkadot.service: Failed with result 'exit-code'.
```

**Comment by bkchr** [comment]
Please use the release build!

`cargo build --release`

cc @tomaka

**Comment by m4dbi7** [comment]
same here with the official binary

**Comment by bjweaver** [comment]
> Please use the release build!
> 
> `cargo build --release`
> 
> cc @tomaka

This was the release build.

**Comment by tomaka** [comment]
Apparently our GitHub binaries have debug assertions enabled, which really shouldn't be the case.

**Comment by LukeWheeldon** [comment]
Same here, using Debian packages.
