### ISSUE TITLE
RuntimePanicked("Storage root must match that calculated.")

### ISSUE THREAD

**Issue by foomip** [paritytech/polkadot#3095]
System info:
- Ubuntu 20.04.2 LTS
- Kernel 5.4.0-65-generic #73-Ubuntu
- 64GB RAM
- 32GB Swap

```
Version: 0.8.30-4b86755c3-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::final_checks
   6: tracing::span::Span::in_scope
   7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block
   8: <polkadot_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,polkadot_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<polkadot_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<polkadot_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<polkadot_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<polkadot_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<polkadot_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<polkadot_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<polkadot_runtime::Runtime>,polkadot_runtime_common::claims::PrevalidateAttests<polkadot_runtime::Runtime>)>>>>::execute_block
   9: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
  10: std::panicking::try
  11: std::thread::local::LocalKey<T>::with
  12: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  13: sc_executor::wasm_runtime::RuntimeCache::with_instance
  14: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  16: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  17: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  18: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  19: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  20: sp_api::Core::execute_block_with_context
  21: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  22: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  23: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  24: <alloc::boxed::Box<dyn sp_consensus::block_import::BlockImport<B>+Error = sp_consensus::error::Error+Transaction = Transaction+core::marker::Send+core::marker::Sync> as sp_consensus::block_import::BlockImport<B>>::import_block
  25: sp_consensus::import_queue::import_single_block_metered
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  28: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  29: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  30: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  32: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  33: std::thread::local::LocalKey<T>::with
  34: futures_executor::local_pool::block_on
  35: tokio::runtime::task::core::Core<T,S>::poll
  36: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  37: tokio::runtime::task::raw::poll
  38: tokio::runtime::blocking::pool::Inner::run
  39: tokio::runtime::context::enter
  40: std::sys_common::backtrace::__rust_begin_short_backtrace
  41: core::ops::function::FnOnce::call_once{{vtable.shim}}
  42: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys/unix/thread.rs:71:17
  43: start_thread
  44: clone


Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /storage/polkadot/.cargo/git/checkouts/substrate-7e08433d4c370a21/3655f9b/frame/executive/src/lib.rs:455

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

2021-05-25 07:38:41  Block prepare storage changes error:
RuntimeApiError(Application(Execution(RuntimePanicked("Storage root must match that calculated."))))
```

This error was also showing up before doing the recommended downgrade from 0.9.2 to 0.8.30

**Comment by bkchr** [comment]
This will be resolved with the next node release
