### ISSUE TITLE
Storage root mismatch causes tokio-runtime-worker-1 panic

### ISSUE THREAD

**Issue by fgimenez** [paritytech/polkadot#328]
Running a node built from 81645ec8f1f0401081b9b288295d8d6ca6f3e503 and using a custom chainspec like https://paste.ubuntu.com/p/vXcY7Z9MT3/ i get this error in the log:
```
====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h9be6c97865beab64 (0x55ec24c6ab30)
   1: std::panicking::rust_panic_with_hook::h057ff03eb4c8000f (0x55ec24d88269)
             at src/libstd/panicking.rs:478
   2: std::panicking::begin_panic::he7b1362a4ee3b76d (0x55ec248b9455)
   3: srml_executive::Executive<System,Block,Context,Payment,UnsignedValidator,AllModules>::execute_block::he52b2422ed255070 (0x55ec2493f8ba)
   4: polkadot_runtime::api::dispatch::hd322bfffcc84643f (0x55ec2488ed15)
   5: std::panicking::try::do_call::h4f346ffa20da596d (0x55ec242e4112)
   6: __rust_maybe_catch_panic (0x55ec24d8d5fa)
             at src/libpanic_unwind/lib.rs:85
   7: substrate_executor::native_executor::safe_call::hac0cca6fc33c6059 (0x55ec242e418a)
   8: std::thread::local::LocalKey<T>::with::hc82bfd0704050fdf (0x55ec242e3cd7)
   9: <polkadot_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h7716f70f947649c2 (0x55ec242e385d)
  10: std::thread::local::LocalKey<T>::with::h0d48d27a06168f56 (0x55ec24109b1f)
  11: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h4fa0fe37ce24b189 (0x55ec23f8de99)
  12: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_call_with_native_else_wasm_strategy::hf5958433f3b5b60b (0x55ec23fe7482)
  13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h7b30e6ad11e2c560 (0x55ec23fba298)
  14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h7eb2dd0fd5f3fbd6 (0x55ec2417d5ff)
  15: substrate_client::client::Client<B,E,Block,RA>::lock_import_and_run::{{closure}}::h228b8d39e5ba2645 (0x55ec23bee89c)
  16: <substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::he4e1f7f50fc400a0 (0x55ec23bd80a9)
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,PRA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h39db773813c2296f (0x55ec24057af7)
  18: <futures::future::map::Map<A,F> as futures::future::Future>::poll::hb0bd15f38fd4c729 (0x55ec23d8f79c)
  19: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h374e4e4d27112e07 (0x55ec24096bd1)
  20: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h6061540885d14959 (0x55ec24097e1e)
  21: futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll::h39f4deb86badfb18 (0x55ec23e91dcd)
  22: std::panicking::try::do_call::h3700c19df002f0cf (0x55ec241411ca)
  23: __rust_maybe_catch_panic (0x55ec24d8d5fa)
             at src/libpanic_unwind/lib.rs:85
  24: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll::h5e38b46687e736b1 (0x55ec23dd9a17)
  25: futures::task_impl::std::set::h5b7f6d3b00241213 (0x55ec24b031f2)
  26: std::panicking::try::do_call::h93dccd1ade0f11c7 (0x55ec24b02c22)
  27: __rust_maybe_catch_panic (0x55ec24d8d5fa)
             at src/libpanic_unwind/lib.rs:85
  28: tokio_threadpool::task::Task::run::hc5a476fd073f2aa7 (0x55ec24b002b9)
  29: tokio_threadpool::worker::Worker::run_task::h13d829c0efc3c3f4 (0x55ec24af9c25)
  30: tokio_threadpool::worker::Worker::run::h3d382b0f61ffb833 (0x55ec24af911e)
  31: std::thread::local::LocalKey<T>::with::hdc75d242dc7c69da (0x55ec24ae0f4e)
  32: std::thread::local::LocalKey<T>::with::h14ef81981995f488 (0x55ec24ae0aef)
  33: std::thread::local::LocalKey<T>::with::h22c74f068b4dbe37 (0x55ec24ae0c7b)
  34: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h41b2dacccfefe4f4 (0x55ec24ae785e)
  35: std::thread::local::LocalKey<T>::with::hf60d27737b64b716 (0x55ec24b04003)
  36: std::thread::local::LocalKey<T>::with::h10dada60d01c1d7a (0x55ec24b0388e)
  37: std::sys_common::backtrace::__rust_begin_short_backtrace::h8e281eb5054aac20 (0x55ec24afb801)
  38: std::panicking::try::do_call::hf00ac30abf586bc5 (0x55ec24b02c6c)
  39: __rust_maybe_catch_panic (0x55ec24d8d5fa)
             at src/libpanic_unwind/lib.rs:85
  40: core::ops::function::FnOnce::call_once{{vtable.shim}}::hc86e4c7ca2cac263 (0x55ec24afc460)
  41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h805c3cc89d534c05 (0x55ec24d753af)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  42: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9ebda9db5f03daf3 (0x55ec24d8c910)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
      std::sys_common::thread::start_thread::ha32838ccbb8a8179
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h6f10b78f26c98dc6
             at src/libstd/sys/unix/thread.rs:79
  43: start_thread (0x7f47b8ee56ba)
  44: clone (0x7f47b8a0541d)
  45: <unknown> (0x0)

Thread 'tokio-runtime-worker-1' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/198e5c9/srml/executive/src/lib.rs:325

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
```
The error repeats on blocks 59, 119, 179, 239,... Apart from the error in the logs all seem to be working normally.

**Comment by fgimenez** [comment]
No longer happens with latest master.

**Comment by debuggor** [comment]
i get the same error today, master , and this bug have fix?

**Comment by fgimenez** [comment]
@debuggor the problem as described in this issue (using a custom chainspec like the one attached and finding error message on logs at specific block heights) no longer happens from current master on a clean installation (no previous db). If you find it feel free to open a separate issue with details about how to reproduce.
