### ISSUE TITLE
I see a message in the logs that asks to report a bug.

### ISSUE THREAD

**Issue by sh-mikhail** [paritytech/polkadot#3284]
```
Thread 'txpool-verifier1' panicked at 'Failed to allocate memory: "Requested allocation size is too large"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/85fa0ab/primitives/io/src/lib.rs:1068

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new


====================

Version: 0.9.3-aa3867609-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: tracing::span::Span::in_scope
   8: <<sp_io::allocator::HostFunctions as sp_wasm_interface::HostFunctions>::host_functions::ExtAllocatorMallocVersion1 as sp_wasm_interface::Function>::execute
   9: scoped_tls::ScopedKey<T>::with
  10: sc_executor_wasmtime::state_holder::with_context
  11: sc_executor_wasmtime::imports::call_static
  12: wasmtime::func::Func::new::{{closure}}
  13: wasmtime::trampoline::func::stub_fn
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: RegisterSetjmp
  25: wasmtime_runtime::traphandlers::catch_traps
  26: wasmtime::func::Func::_call
  27: wasmtime::func::Func::call
  28: sc_executor_wasmtime::instance_wrapper::EntryPoint::call
  29: scoped_tls::ScopedKey<T>::set
  30: sc_executor_wasmtime::runtime::perform_call
  31: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call
  32: sc_executor_common::wasm_runtime::WasmInstance::call_export
  33: std::panicking::try
  34: std::thread::local::LocalKey<T>::with
  35: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  36: sc_executor::wasm_runtime::RuntimeCache::with_instance
  37: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  38: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  39: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  40: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  41: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  42: sp_api::runtime_decl_for_Core::initialize_block_call_api_at
  43: <polkadot_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl
  44: sp_api::Core::initialize_block
  45: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  46: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  47: <polkadot_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_transaction_pool::runtime_api::TaggedTransactionQueue<__SR_API_BLOCK__>>::TaggedTransactionQueue_validate_transaction_runtime_api_impl
  48: sp_transaction_pool::runtime_api::TaggedTransactionQueue::validate_transaction
  49: tracing::span::Span::in_scope
  50: sc_transaction_pool::api::validate_transaction_blocking
  51: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  52: futures_executor::thread_pool::PoolState::work
  53: std::sys_common::backtrace::__rust_begin_short_backtrace
  54: core::ops::function::FnOnce::call_once{{vtable.shim}}
  55: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  56: start_thread
  57: __clone
```

Node restart does not work.What can I do to bring the node back to life?

**Comment by NukeManDan** [comment]
To solve this, please downgrade to Polkadot 0.8.30 and run with the following flags added or changed to the correct option:
```
polkadot --execution native --wasm-execution Compiled`
```

The easiest path is to download (and verify) the `polkadot` binary and run it:
- https://github.com/paritytech/polkadot/releases/tag/v0.8.30

If you choose to build from source, you must [use the rust 1.51.0 release](https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html#managing-versions) of the stable and nightly toolchain: 
```bash
# Run in the top level of the Polkadot source working directory
git checkout v0.8.30
rustup override set 1.51.0
cargo build --release
```

## NOTE: There will be a 0.9.5 release very soon

You will be encouraged to use when available. Please join [Polkadot Validator Lounge](https://matrix.to/#/#polkadotvalidatorlounge:web3.foundation)  and monitor for the latest information and questions. 🙏🏼
