### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /home/luca/.cargo/git/checkouts/substrate-7e08433d4c370a21/3655f9b/frame/executive/src/lib.rs:455

### ISSUE THREAD

**Issue by lucamarrocco** [paritytech/polkadot#3286]
polkadot v0.8.30
polkadot --pruning=archive --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --validator

2021-06-17 18:02:31  ⚙️  Syncing  0.0 bps, target=#5547200 (10 peers), best: #5546967 (0x3c66…7fbd), finalized #5546960 (0xe806…c186), ⬇ 108.3kiB/s ⬆ 27.4kiB/s    
Hash: given=8dd9ed8787e16374d963b5e07cfdf160f0e99a7f4c9ed14e12039aaa25da1209, expected=d694140691628dfe6adf1f7795de3a15ad983f7d4608628fad43f1f4e3b62ac9

====================

Version: 0.8.30-4b86755c3-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::final_checks
   6: tracing::span::Span::in_scope
   7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block
   8: <polkadot_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,polkadot_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<polkadot_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<polkadot_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<polkadot_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<polkadot_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<polkadot_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<polkadot_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<polkadot_runtime::Runtime>,polkadot_runtime_common::claims::PrevalidateAttests<polkadot_runtime::Runtime>)>>>>::execute_block
   9: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
  10: std::panicking::try
  11: std::thread::local::LocalKey<T>::with
  12: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  13: sc_executor::wasm_runtime::RuntimeCache::with_instance
  14: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  16: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  17: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  18: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  19: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  20: sp_api::Core::execute_block_with_context
  21: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  22: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  23: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  24: <alloc::boxed::Box<dyn sp_consensus::block_import::BlockImport<B>+Error = sp_consensus::error::Error+Transaction = Transaction+core::marker::Send+core::marker::Sync> as sp_consensus::block_import::BlockImport<B>>::import_block
  25: sp_consensus::import_queue::import_single_block_metered
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  28: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  29: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  30: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  32: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  33: std::thread::local::LocalKey<T>::with
  34: futures_executor::local_pool::block_on
  35: tokio::runtime::task::core::Core<T,S>::poll
  36: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  37: tokio::runtime::task::raw::poll
  38: tokio::runtime::blocking::pool::Inner::run
  39: tokio::runtime::context::enter
  40: std::sys_common::backtrace::__rust_begin_short_backtrace
  41: core::ops::function::FnOnce::call_once{{vtable.shim}}
  42: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys/unix/thread.rs:71:17
  43: start_thread
  44: clone

Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /home/luca/.cargo/git/checkouts/substrate-7e08433d4c370a21/3655f9b/frame/executive/src/lib.rs:455

**Comment by lucamarrocco** [comment]
It is possibile that this error is generated because I used a more recent version 0.9 and then I start version 0.8.3 on same database?

**Comment by NukeManDan** [comment]
To solve this, please downgrade to Polkadot 0.8.30 and run with the following flags added or changed to the correct option:
```
polkadot --execution native --wasm-execution Compiled`
```

The easiest path is to download (and verify) the `polkadot` binary and run it:
- https://github.com/paritytech/polkadot/releases/tag/v0.8.30

If you choose to build from source, you must [use the rust 1.51.0 release](https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html#managing-versions) of the stable and nightly toolchain: 
```bash
# Run in the top level of the Polkadot source working directory
git checkout v0.8.30
rustup override set 1.51.0
cargo build --release
```

## NOTE: There will be a 0.9.5 release very soon

You will be encouraged to use when available. Please join [Polkadot Validator Lounge](https://matrix.to/#/#polkadotvalidatorlounge:web3.foundation)  and monitor for the latest information and questions. 🙏🏼

**Comment by lucamarrocco** [comment]
Dan, Thank you for your help and support. I still have same issue, even after completely remove all polkadot files, cleaned up and rebuild 0.8.30 from scratch.. I also removed .cargo directory befoew these operation, to be sure to have a clean install.

Is there anything else that I can do to be double sure that there isn't anything wrong with my polkadot version?

2021-06-18 13:07:48  ⚙️  Syncing  0.0 bps, target=#5558539 (41 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 1.8kiB/s ⬆ 0.2kiB/s    
2021-06-18 13:07:52  updated 127 (updated) + 0 (correct) + 42 (skipped) voter's deposit.    
2021-06-18 13:07:52  ✅ no migration for ElectionProviderMultiPhase, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Tips, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Bounties, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Multisig, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Proxy, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Identity, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Utility, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Vesting, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Claims, setting storage version to PalletVersion { major: 0, minor: 8, patch: 30 }    
2021-06-18 13:07:52  ✅ no migration for Treasury, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for TechnicalMembership, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for ElectionsPhragmen, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for TechnicalCommittee, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Council, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Democracy, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for AuthorityDiscovery, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for ImOnline, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Grandpa, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Session, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Historical, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Offences, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ⚠️ Staking declares internal migrations (which *might* execute), setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  [4876134] 💸 Migrating staking to Releases::V6_0_0    
2021-06-18 13:07:52  [4876134] 💸 Done.    
2021-06-18 13:07:52  ✅ no migration for Authorship, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for TransactionPayment, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Balances, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Indices, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Timestamp, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Babe, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for Scheduler, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:52  ✅ no migration for RandomnessCollectiveFlip, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:53  ⚙️  Syncing  0.0 bps, target=#5558539 (41 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 6.5kiB/s ⬆ 0.6kiB/s    
2021-06-18 13:07:53  ⚠️ System declares internal migrations (which *might* execute), setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:07:57  🔍 Discovered new external address for our node: /ip4/10.0.1.30/tcp/30333/p2p/12D3KooWDL7j3iSYyn9w9SRQPNf1msRMkRqAsWzu7VJrEDK1YHxE    
2021-06-18 13:07:58  ⚙️  Syncing  0.0 bps, target=#5558540 (41 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 168.5kiB/s ⬆ 43.8kiB/s    
2021-06-18 13:07:58  🔍 Discovered new external address for our node: /ip4/192.168.26.0/tcp/30333/p2p/12D3KooWDL7j3iSYyn9w9SRQPNf1msRMkRqAsWzu7VJrEDK1YHxE    
2021-06-18 13:08:03  ⚙️  Syncing  0.0 bps, target=#5558541 (45 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 573.0kiB/s ⬆ 86.2kiB/s    
2021-06-18 13:08:08  ⚙️  Syncing  0.0 bps, target=#5558542 (47 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 201.2kiB/s ⬆ 13.9kiB/s    
2021-06-18 13:08:13  ⚙️  Syncing  0.0 bps, target=#5558543 (49 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 760.9kiB/s ⬆ 82.8kiB/s    
2021-06-18 13:08:18  ⚙️  Syncing  0.0 bps, target=#5558543 (49 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 34.2kiB/s ⬆ 12.1kiB/s    
2021-06-18 13:08:23  ⚙️  Syncing  0.0 bps, target=#5558544 (49 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 64.9kiB/s ⬆ 17.9kiB/s    
2021-06-18 13:08:28  ⚙️  Syncing  0.0 bps, target=#5558545 (49 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 5.6kiB/s ⬆ 2.6kiB/s    
2021-06-18 13:08:33  ⚙️  Syncing  0.0 bps, target=#5558546 (49 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 8.5kiB/s ⬆ 9.5kiB/s    
2021-06-18 13:08:36  updated 127 (updated) + 0 (correct) + 42 (skipped) voter's deposit.    
2021-06-18 13:08:36  ✅ no migration for ElectionProviderMultiPhase, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Tips, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Bounties, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Multisig, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Proxy, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Identity, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Utility, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Vesting, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Claims, setting storage version to PalletVersion { major: 0, minor: 8, patch: 30 }    
2021-06-18 13:08:36  ✅ no migration for Treasury, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for TechnicalMembership, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for ElectionsPhragmen, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for TechnicalCommittee, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Council, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Democracy, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for AuthorityDiscovery, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for ImOnline, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Grandpa, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Session, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Historical, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Offences, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ⚠️ Staking declares internal migrations (which *might* execute), setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  [4876134] 💸 Migrating staking to Releases::V6_0_0    
2021-06-18 13:08:36  [4876134] 💸 Done.    
2021-06-18 13:08:36  ✅ no migration for Authorship, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for TransactionPayment, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Balances, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Indices, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Timestamp, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Babe, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for Scheduler, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:36  ✅ no migration for RandomnessCollectiveFlip, setting storage version to PalletVersion { major: 3, minor: 0, patch: 0 }    
2021-06-18 13:08:38  ⚙️  Syncing  0.0 bps, target=#5558547 (49 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 5.8kiB/s ⬆ 4.0kiB/s    
2021-06-18 13:08:43  ⚙️  Syncing  0.0 bps, target=#5558548 (49 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 6.2kiB/s ⬆ 5.5kiB/s    
2021-06-18 13:08:48  ⚙️  Syncing  0.0 bps, target=#5558548 (49 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 6.2kiB/s ⬆ 5.2kiB/s    
2021-06-18 13:08:53  ⚙️  Syncing  0.0 bps, target=#5558549 (50 peers), best: #4876134 (0x89b9…466e), finalized #4875776 (0xf4af…e837), ⬇ 3.7kiB/s ⬆ 1.4kiB/s    
2021-06-18 13:08:58  ⚙️  Syncing 96.3 bps, target=#5558550 (50 peers), best: #4876616 (0x1464…ebee), finalized #4876288 (0xbcd5…04e1), ⬇ 699.8kiB/s ⬆ 1.5kiB/s    
Hash: given=40dece14ba46c79de9339f70805d3729e61d22d06ac53364f3954d05ac672709, expected=af4d5d05fb0e911f637999f556574159f4ef63ef88b4262784e7aff5ef0e11e6

====================

Version: 0.8.30-4b86755c3-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::final_checks
   6: tracing::span::Span::in_scope
   7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block
   8: <polkadot_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,polkadot_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<polkadot_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<polkadot_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<polkadot_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<polkadot_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<polkadot_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<polkadot_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<polkadot_runtime::Runtime>,polkadot_runtime_common::claims::PrevalidateAttests<polkadot_runtime::Runtime>)>>>>::execute_block
   9: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
  10: std::thread::local::LocalKey<T>::with
  11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  12: sc_executor::wasm_runtime::RuntimeCache::with_instance
  13: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  16: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  17: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  18: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  19: sp_api::Core::execute_block_with_context
  20: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  21: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  22: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  23: <alloc::boxed::Box<dyn sp_consensus::block_import::BlockImport<B>+Error = sp_consensus::error::Error+Transaction = Transaction+core::marker::Send+core::marker::Sync> as sp_consensus::block_import::BlockImport<B>>::import_block
  24: sp_consensus::import_queue::import_single_block_metered
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  28: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  30: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  31: std::thread::local::LocalKey<T>::with
  32: futures_executor::local_pool::block_on
  33: tokio::runtime::task::core::Core<T,S>::poll
  34: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  35: tokio::runtime::task::harness::Harness<T,S>::poll
  36: tokio::runtime::blocking::pool::Inner::run
  37: tokio::runtime::context::enter
  38: std::sys_common::backtrace::__rust_begin_short_backtrace
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}
  40: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  41: start_thread
  42: clone


Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /home/luca/.cargo/git/checkouts/substrate-7e08433d4c370a21/3655f9b/frame/executive/src/lib.rs:455

**Comment by lucamarrocco** [comment]
What I did now, is to completely clean rust / cargo, remove it from my ubuntu system, and then reinstall from scratch, using v0.8.30 version, with this exact commands

   curl https://sh.rustup.rs -sSf | sh
   source $HOME/.cargo/env
   rustup update
   sudo apt install build-essential git clang libclang-dev pkg-config libssl-dev
   ./scripts/init.sh
   cargo build --release

this is my rustup show

luca@node1:~/polkadot-0.8.30$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/luca/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.53.0 (53cb7b09b 2021-06-17)

./target/release/polkadot --pruning=archive --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --execution native --wasm-execution Compiled --ws-port=9944 --ws-external --rpc-cors=all

it seams that with these configuration, sync is proceeding.. 

I will confirm if this configuration, previous issue is solved when I reach a full sync node.

Thank you.
Best regards :)

**Comment by NukeManDan** [comment]
Ah you must use 1.51.0, as mentioned above @lucamarrocco

**Comment by lucamarrocco** [comment]
Hello Dan, Thank you for your anwer. I don't think so that this solve. Infact I tried with 1.51.0, 1.53.0 toolchains with same error results. 

Btw I also tried to download and install polkadot binary (0.8.30) from release page, with same error results. I wonder if there is something related to operating system that my cause this error. I'm using Ubuntu 20. 
At this point I prefer to spend time to use new 0.9.5 version. 

Is there a technical channel for 0.9.5-rc5 (and above) to provide feedbacks?

Thank you :)

**Comment by NukeManDan** [comment]
Bummer! #3289 seems to report the same. The technical channel to join was mentioned, the validator lounge: https://matrix.to/#/#polkadotvalidatorlounge:web3.foundation

0.9.5 is not quite there, but I know it will be very (very) soon. If you want to use the rcX versions, please do give it a try, I know Parity has a few nodes testing this pre-release that _seem_ to be working just fine, but we also have many 0.8.30 nodes running just fine too. 

With 0.8.30 you are starting with a clean DB and using the proper flags mentioned?

**Comment by lucamarrocco** [comment]
yes, from scratch with mentioned above params native compiled etc both with compiled / downloaded binary. problem around 4.8M block. ubuntu 20. 0.9.5-rc5 proceed from that node and is now fully synced, again both compiled / downloaded binary. in this case without native / compiled flag

Luca

**Comment by NukeManDan** [comment]
I know there are changes in the specific toolchain used between the release builds, so I suggest trying https://github.com/paritytech/polkadot/releases/tag/v0.9.5 binary, or https://github.com/paritytech/polkadot/releases/tag/v0.9.6-rc6 binary if you want updates to the node host (runtime is unchanged)

**Comment by NukeManDan** [comment]
Reports are https://github.com/paritytech/polkadot/releases/tag/v0.9.6 should resolve your issue. Please let me know if not 🙏🏼
