### ISSUE TITLE
Failed to allocate memory: "Requested allocation size is too large" @ block 5545118

### ISSUE THREAD

**Issue by iverc** [paritytech/polkadot#3297]
## Error when trying to start a full node / sync it with the current state.

After several attempts to fetch block #5545118 it crashes with the following error:**

```
Thread 'tokio-runtime-worker' panicked at 'Failed to allocate memory: "Requested allocation size is too large"', ./.cargo/git/checkouts/substrate-7e08433d4c370a21/85fa0ab/primitives/io/src/lib.rs:1068
```
Clearly it fails to allocate memory when calling `malloc`, but there's not enough data to find the root cause and fix it. Please help.

### Full error log:

```
Version: 0.9.3-aa3867609-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/149f4836dd6d9e789a26dca16dc034588866894e/library/std/src/panicking.rs:626:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/149f4836dd6d9e789a26dca16dc034588866894e/library/std/src/panicking.rs:519:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/149f4836dd6d9e789a26dca16dc034588866894e/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/149f4836dd6d9e789a26dca16dc034588866894e/library/std/src/panicking.rs:515:5
   5: core::panicking::panic_fmt
             at /rustc/149f4836dd6d9e789a26dca16dc034588866894e/library/core/src/panicking.rs:92:14
   6: core::result::unwrap_failed
             at /rustc/149f4836dd6d9e789a26dca16dc034588866894e/library/core/src/result.rs:1355:5
   7: tracing::span::Span::in_scope
   8: <<sp_io::allocator::HostFunctions as sp_wasm_interface::HostFunctions>::host_functions::ExtAllocatorMallocVersion1 as sp_wasm_interface::Function>::execute
   9: scoped_tls::ScopedKey<T>::with
  10: sc_executor_wasmtime::state_holder::with_context
  11: sc_executor_wasmtime::imports::call_static
  12: wasmtime::func::Func::new::{{closure}}
  13: wasmtime::trampoline::func::stub_fn
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: RegisterSetjmp
  25: wasmtime_runtime::traphandlers::catch_traps
  26: wasmtime::func::Func::_call
  27: wasmtime::func::Func::call
  28: sc_executor_wasmtime::instance_wrapper::EntryPoint::call
  29: scoped_tls::ScopedKey<T>::set
  30: sc_executor_wasmtime::runtime::perform_call
  31: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call
  32: sc_executor_common::wasm_runtime::WasmInstance::call_export
  33: std::panicking::try
  34: std::thread::local::LocalKey<T>::with
  35: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  36: sc_executor::wasm_runtime::RuntimeCache::with_instance
  37: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  38: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  39: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  40: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  41: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  42: sp_api::runtime_decl_for_Core::initialize_block_call_api_at
  43: <polkadot_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl
  44: sp_api::Core::initialize_block
  45: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  46: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  47: sp_block_builder::runtime_decl_for_BlockBuilder::check_inherents_call_api_at
  48: sp_block_builder::BlockBuilder::check_inherents
  49: <sc_consensus_babe::BabeVerifier<Block,Client,SelectChain,CAW,CIDP> as sp_consensus::import_queue::Verifier<Block>>::verify::{{closure}}
  50: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  51: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  52: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  53: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  54: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  55: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  56: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  57: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  58: std::thread::local::LocalKey<T>::with
  59: futures_executor::local_pool::block_on
  60: tokio::runtime::task::core::Core<T,S>::poll
  61: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  62: tokio::runtime::task::harness::Harness<T,S>::poll
  63: tokio::runtime::blocking::pool::Inner::run
  64: tokio::runtime::context::enter
  65: std::sys_common::backtrace::__rust_begin_short_backtrace
  66: core::ops::function::FnOnce::call_once{{vtable.shim}}
  67: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/149f4836dd6d9e789a26dca16dc034588866894e/library/alloc/src/boxed.rs:1575:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/149f4836dd6d9e789a26dca16dc034588866894e/library/alloc/src/boxed.rs:1575:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/149f4836dd6d9e789a26dca16dc034588866894e/library/std/src/sys/unix/thread.rs:71:17
  68: start_thread
  69: __clone


Thread 'tokio-runtime-worker' panicked at 'Failed to allocate memory: "Requested allocation size is too large"', /home/dotval/.cargo/git/checkouts/substrate-7e08433d4c370a21/85fa0ab/primitives/io/src/lib.rs:1068

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
```

**Comment by tdmm** [comment]
same error

**Comment by harryweiyongjie** [comment]
same error

**Comment by iverc** [comment]
@rphmeier @gavofyork please take a look when you have a chance. thanks.

**Comment by NukeManDan** [comment]
To solve this, please downgrade to Polkadot 0.8.30 and run with the following flags added or changed to the correct option:
```
polkadot --execution native --wasm-execution Compiled`
```

The easiest path is to download (and verify) the `polkadot` binary and run it:
- https://github.com/paritytech/polkadot/releases/tag/v0.8.30

If you choose to build from source, you must [use the rust 1.51.0 release](https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html#managing-versions) of the stable and nightly toolchain: 
```bash
# Run in the top level of the Polkadot source working directory
git checkout v0.8.30
rustup override set 1.51.0
cargo build --release
```

## NOTE: There will be a 0.9.5 release very soon

You will be encouraged to use when available. Please join [Polkadot Validator Lounge](https://matrix.to/#/#polkadotvalidatorlounge:web3.foundation)  and monitor for the latest information and questions. 🙏🏼
