### ISSUE TITLE
v0.9.5 Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by pkrasam** [paritytech/polkadot#3332]
```
Jun 21 10:20:30 polkadot[35739]:    9: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
Jun 21 10:20:30 polkadot[35739]:   10: std::thread::local::LocalKey<T>::with
Jun 21 10:20:30 polkadot[35739]:   11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Jun 21 10:20:30 polkadot[35739]:   12: sc_executor::wasm_runtime::RuntimeCache::with_instance
Jun 21 10:20:30 polkadot[35739]:   13: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Jun 21 10:20:30 polkadot[35739]:   14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
Jun 21 10:20:30 polkadot[35739]:   15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Jun 21 10:20:30 polkadot[35739]:   16: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Jun 21 10:20:30 polkadot[35739]:   17: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Jun 21 10:20:30 polkadot[35739]:   18: sp_api::runtime_decl_for_Core::execute_block_call_api_at
Jun 21 10:20:30 polkadot[35739]:   19: <westend_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_execute_block_runtime_api_impl
Jun 21 10:20:30 polkadot[35739]:   20: sp_api::Core::execute_block_with_context
Jun 21 10:20:30 polkadot[35739]:   21: sc_service::client::client::Client<B,E,Block,RA>::prepare_block_storage_changes
Jun 21 10:20:30 polkadot[35739]:   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jun 21 10:20:30 polkadot[35739]:   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jun 21 10:20:30 polkadot[35739]:   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jun 21 10:20:30 polkadot[35739]:   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jun 21 10:20:30 polkadot[35739]:   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jun 21 10:20:30 polkadot[35739]:   27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jun 21 10:20:30 polkadot[35739]:   28: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Jun 21 10:20:30 polkadot[35739]:   29: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Jun 21 10:20:30 polkadot[35739]:   30: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Jun 21 10:20:30 polkadot[35739]:   31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jun 21 10:20:30 polkadot[35739]:   32: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Jun 21 10:20:30 polkadot[35739]:   33: std::thread::local::LocalKey<T>::with
Jun 21 10:20:30 polkadot[35739]:   34: futures_executor::local_pool::block_on
Jun 21 10:20:30 polkadot[35739]:   35: tokio::runtime::task::core::Core<T,S>::poll
Jun 21 10:20:30 polkadot[35739]:   36: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Jun 21 10:20:30 polkadot[35739]:   37: tokio::runtime::task::harness::Harness<T,S>::poll
Jun 21 10:20:30 polkadot[35739]:   38: tokio::runtime::blocking::pool::Inner::run
Jun 21 10:20:30 polkadot[35739]:   39: tokio::runtime::context::enter
Jun 21 10:20:30 polkadot[35739]:   40: std::sys_common::backtrace::__rust_begin_short_backtrace
Jun 21 10:20:30 polkadot[35739]:   41: core::ops::function::FnOnce::call_once{{vtable.shim}}
Jun 21 10:20:30 polkadot[35739]:   42: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jun 21 10:20:30 polkadot[35739]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
Jun 21 10:20:30 polkadot[35739]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jun 21 10:20:30 polkadot[35739]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
Jun 21 10:20:30 polkadot[35739]:       std::sys::unix::thread::Thread::new::thread_start
Jun 21 10:20:30 polkadot[35739]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
Jun 21 10:20:30 polkadot[35739]:   43: start_thread
Jun 21 10:20:30 polkadot[35739]:   44: __clone
Jun 21 10:20:30 polkadot[35739]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /home/westend/.cargo/git/checkouts/substrate-7e08433d4c370a21/9c57262/frame/executive/src/lib.rs:462
Jun 21 10:20:30 polkadot[35739]: This is a bug. Please report it at:
Jun 21 10:20:30 polkadot[35739]:         https://github.com/paritytech/polkadot/issues/new
Jun 21 10:20:30 polkadot[35739]: 2021-06-21 10:20:30 ✨ Imported #6150924 (0xf7ce…3b64)
Jun 21 10:20:30 polkadot[35739]: 2021-06-21 10:20:30 💤 Idle (32 peers), best: #6150924 (0xc7e1…b312), finalized #6150921 (0x9061…c8df), ⬇ 12.6kiB/s ⬆ 9.3kiB/s
```

**Comment by bkchr** [comment]
Please run with `--execution wasm`

**Comment by pkrasam** [comment]
Thank you @bkchr that flag worked
