### ISSUE TITLE
Relaychain part of Karura node lagging on finality and eventually crashed

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#3414]
> Thread 'tokio-runtime-worker' panicked at 'Trying to pin pending state', /root/.cargo/git/checkouts/substrate-f4423eebfa0046a3/9c57262/client/state-db/src/noncanonical.rs:527

https://gist.github.com/xlc/db3317b5a4bb4736b1c6de4a1c5fccb9

It was experiencing lagging on finality 

```
2021-07-05 21:22:35 [Parachain] 💤 Idle (16 peers), best: #83693 (0xfe6f…88de), finalized #83271 (0x5410…ef4e), ⬇ 0.6kiB/s ⬆ 1.2kiB/s
2021-07-05 21:22:36 [Relaychain] 💤 Idle (224 peers), best: #8216070 (0x9009…c3d9), finalized #8216065 (0x0087…b2dc), ⬇ 2.2MiB/s ⬆ 16.8kiB/s
2021-07-05 21:22:40 [Parachain] 💤 Idle (16 peers), best: #83693 (0xfe6f…88de), finalized #83333 (0x8a53…0565), ⬇ 3.4kiB/s ⬆ 0.8kiB/s
2021-07-05 21:22:41 [Relaychain] 💤 Idle (225 peers), best: #8216078 (0x0c40…417f), finalized #8216065 (0x0087…b2dc), ⬇ 1.2MiB/s ⬆ 18.8kiB/s
2021-07-05 21:22:45 [Parachain] 💤 Idle (16 peers), best: #83693 (0xfe6f…88de), finalized #83355 (0x102e…481c), ⬇ 5.0kiB/s ⬆ 1.1kiB/s
2021-07-05 21:22:46 [Relaychain] 💤 Idle (225 peers), best: #8216107 (0x9db4…24d3), finalized #8216065 (0x0087…b2dc), ⬇ 3.7MiB/s ⬆ 16.1kiB/s
2021-07-05 21:22:50 [Parachain] 💤 Idle (16 peers), best: #83693 (0xfe6f…88de), finalized #83355 (0x102e…481c), ⬇ 0.9kiB/s ⬆ 0.3kiB/s
2021-07-05 21:22:51 [Relaychain] 💤 Idle (225 peers), best: #8216144 (0xf026…5b60), finalized #8216065 (0x0087…b2dc), ⬇ 1.2MiB/s ⬆ 2.8kiB/s
2021-07-05 21:22:55 [Parachain] 💤 Idle (16 peers), best: #83693 (0xfe6f…88de), finalized #83355 (0x102e…481c), ⬇ 2.8kiB/s ⬆ 0.6kiB/s
2021-07-05 21:22:56 [Relaychain] 💤 Idle (225 peers), best: #8216176 (0x8dec…afaa), finalized #8216065 (0x0087…b2dc), ⬇ 1.8MiB/s ⬆ 48.0kiB/s
2021-07-05 21:23:00 [Parachain] 💤 Idle (16 peers), best: #83693 (0xfe6f…88de), finalized #83355 (0x102e…481c), ⬇ 2.0kiB/s ⬆ 1.5kiB/s
2021-07-05 21:23:01 [Relaychain] 💤 Idle (225 peers), best: #8216212 (0x6d45…7cdd), finalized #8216065 (0x0087…b2dc), ⬇ 2.2MiB/s ⬆ 7.2kiB/s
```

It is running with Karura 1.1.0 which itself is using v0.9.7 of Polkadot.

**Comment by rphmeier** [comment]
cc @arkpar

**Comment by arkpar** [comment]
This is a debug assertion triggered only in debug build. Do you also have finality lagging when running in release mode?

**Comment by gangelop** [comment]
same crash here but no lagging or any other abnormal behavior.

```
Jul 08 01:50:06 birb-val1 polkadot[20263]: 2021-07-08 01:50:06 ✨ Imported #8248098 (0xbde1…9652)
Jul 08 01:50:09 birb-val1 polkadot[20263]: 2021-07-08 01:50:09 💤 Idle (47 peers), best: #8248098 (0xbde1…9652), finalized #8248095 (0xb934…b398), ⬇ 806.1kiB/s ⬆ 377.7kiB/s
Jul 08 01:50:12 birb-val1 polkadot[20263]: 2021-07-08 01:50:12 ✨ Imported #8248099 (0x5191…d4f7)
Jul 08 01:50:13 birb-val1 polkadot[20263]: 2021-07-08 01:50:13 ♻️  Reorg on #8248099,0x5191…d4f7 to #8248099,0x441a…4b59, common ancestor #8248098,0xbde1…9652
Jul 08 01:50:13 birb-val1 polkadot[20263]: 2021-07-08 01:50:13 ✨ Imported #8248099 (0x441a…4b59)
Jul 08 01:50:14 birb-val1 polkadot[20263]: 2021-07-08 01:50:14 💤 Idle (47 peers), best: #8248099 (0x441a…4b59), finalized #8248096 (0x6c47…08bd), ⬇ 1.0MiB/s ⬆ 708.5kiB/s
Jul 08 01:50:18 birb-val1 polkadot[20263]: 2021-07-08 01:50:18 ✨ Imported #8248100 (0xa5ac…6618)
Jul 08 01:50:19 birb-val1 polkadot[20263]: 2021-07-08 01:50:19 💤 Idle (47 peers), best: #8248100 (0xa5ac…6618), finalized #8248097 (0x96b6…79a2), ⬇ 1.1MiB/s ⬆ 567.0kiB/s
Jul 08 01:50:24 birb-val1 polkadot[20263]: 2021-07-08 01:50:24 ✨ Imported #8248101 (0x167c…7d07)
Jul 08 01:50:24 birb-val1 polkadot[20263]: ====================
Jul 08 01:50:24 birb-val1 polkadot[20263]: Version: 0.9.8-3a10ee63c-x86_64-linux-gnu
Jul 08 01:50:24 birb-val1 polkadot[20263]:    0: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:    1: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:    2: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:    3: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:    4: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:    5: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:    6: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:    7: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:    8: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:    9: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   10: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   11: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   12: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   13: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   14: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   15: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   16: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   17: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   18: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   19: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   20: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   21: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   22: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   23: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   24: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   25: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   26: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   27: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   28: <unknown>
Jul 08 01:50:24 birb-val1 polkadot[20263]:   29: start_thread
Jul 08 01:50:24 birb-val1 polkadot[20263]:   30: clone
Jul 08 01:50:24 birb-val1 polkadot[20263]: Thread 'tokio-runtime-worker' panicked at 'Trying to pin pending state', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/1b758b2/client/state-db/src/noncanonical.rs:527
Jul 08 01:50:24 birb-val1 polkadot[20263]: This is a bug. Please report it at:
Jul 08 01:50:24 birb-val1 polkadot[20263]:         https://github.com/paritytech/polkadot/issues/new
Jul 08 01:50:24 birb-val1 systemd[1]: polkadot.service: Main process exited, code=exited, status=1/FAILURE
Jul 08 01:50:24 birb-val1 systemd[1]: polkadot.service: Failed with result 'exit-code'.
Jul 08 01:52:24 birb-val1 systemd[1]: polkadot.service: Scheduled restart job, restart counter is at 1.
Jul 08 01:52:24 birb-val1 systemd[1]: Stopped Polkadot Node.
Jul 08 01:52:24 birb-val1 systemd[1]: Started Polkadot Node.
Jul 08 01:52:25 birb-val1 polkadot[28876]: 2021-07-08 01:52:25 ----------------------------
Jul 08 01:52:25 birb-val1 polkadot[28876]: 2021-07-08 01:52:25 This chain is not in any way
Jul 08 01:52:25 birb-val1 polkadot[28876]: 2021-07-08 01:52:25       endorsed by the
Jul 08 01:52:25 birb-val1 polkadot[28876]: 2021-07-08 01:52:25      KUSAMA FOUNDATION
Jul 08 01:52:25 birb-val1 polkadot[28876]: 2021-07-08 01:52:25 ----------------------------
Jul 08 01:52:25 birb-val1 polkadot[28876]: 2021-07-08 01:52:25 Parity Polkadot
Jul 08 01:52:25 birb-val1 polkadot[28876]: 2021-07-08 01:52:25 ✌️  version 0.9.8-3a10ee63c-x86_64-linux-gnu
Jul 08 01:52:25 birb-val1 polkadot[28876]: 2021-07-08 01:52:25 ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
```

command line options:

```
/usr/bin/polkadot --chain kusama --pruning=1000 --name=🐤 BIRB TECHNOLOGY 1 --validator --unsafe-pruning --prometheus-external
```

version:
```
$ polkadot --version
polkadot 0.9.8-3a10ee63c-x86_64-linux-gnu
```

**Comment by bkchr** [comment]
@gangelop please use a release build `cargo build --release`

**Comment by ktzee** [comment]
> @gangelop please use a release build `cargo build --release`
I'm working with @gangelop on birb.
We're not building ourselves. We're using the Ubuntu package, installed from https://releases.parity.io/deb

**Comment by bkchr** [comment]
Yeah, we have accidentally activated debug assertions. The only solution for now is to rebuild it on your own.
