### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'Trying to pin pending state'

### ISSUE THREAD

**Issue by TomaszWaszczyk** [paritytech/polkadot#3441]
```
> Version: 0.9.8-3a10ee63c-x86_64-linux-gnu
> 
>    0: sp_panic_handler::set::{{closure}}
>    1: std::panicking::rust_panic_with_hook
>              at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:595:17
>    2: std::panicking::begin_panic::{{closure}}
>    3: std::sys_common::backtrace::__rust_end_short_backtrace
>    4: std::panicking::begin_panic
>    5: sc_state_db::noncanonical::NonCanonicalOverlay<BlockHash,Key>::pin
>    6: sc_state_db::StateDb<BlockHash,Key>::pin
>    7: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::state_at
>    8: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::runtime_version
>    9: <kusama_runtime::RuntimeApiImpl<Block,C> as sp_api::ApiExt<Block>>::api_version
>   10: tracing::span::Span::in_scope
>   11: sc_transaction_pool::api::validate_transaction_blocking
>   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>   14: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
>   15: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
>   16: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
>   17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>   18: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
>   19: std::thread::local::LocalKey<T>::with
>   20: futures_executor::local_pool::block_on
>   21: tokio::runtime::task::core::Core<T,S>::poll
>   22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
>   23: tokio::runtime::task::raw::poll
>   24: tokio::runtime::blocking::pool::Inner::run
>   25: tokio::runtime::context::enter
>   26: std::sys_common::backtrace::__rust_begin_short_backtrace
>   27: core::ops::function::FnOnce::call_once{{vtable.shim}}
>   28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
>              at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
>       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
>              at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
>       std::sys::unix::thread::Thread::new::thread_start
>              at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
>   29: start_thread
>   30: clone
> 
> 
> Thread 'tokio-runtime-worker' panicked at 'Trying to pin pending state', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/1b758b2/client/state-db/src/noncanonical.rs:527
> 
> This is a bug. Please report it at:
> 
>         https://github.com/paritytech/polkadot/issues/new
```
and after trying to run once more time:
```
2021-07-08 05:59:19 Subsystem availability-store-subsystem appears unresponsive. signal=BlockFinalized(0xa43e24ecf7af13226eb891adcef265fe99485e6aab815603cd3419a8cd4ab7f7, 8250422) received=1196
2021-07-08 05:59:19 subsystem exited with error subsystem="candidate-validation-subsystem" err=FromOrigin { origin: "candidate-validation", source: Context("Signal channel is terminated and empty.") }
2021-07-08 05:59:19 error receiving message from subsystem context for job job="CandidateBackingJob" err=Context("Signal channel is terminated and empty.")
2021-07-08 05:59:19 subsystem exited with error subsystem="chain-api-subsystem" err=FromOrigin { origin: "chain-api", source: Context("Signal channel is terminated and empty.") }
2021-07-08 05:59:19 subsystem exited with error subsystem="statement-distribution-subsystem" err=FromOrigin { origin: "statement-distribution", source: SubsystemReceive(Context("Signal channel is terminated and empty.")) }
2021-07-08 05:59:19 Essential task `overseer` failed. Shutting down service.
2021-07-08 05:59:19 subsystem exited with error subsystem="availability-distribution-subsystem" err=FromOrigin { origin: "availability-distribution", source: IncomingMessageChannel(Context("Signal channel is terminated and empty.")) }
2021-07-08 05:59:19 error receiving message from subsystem context for job job="BitfieldSigningJob" err=Context("Signal channel is terminated and empty.")
2021-07-08 05:59:19 subsystem exited with error subsystem="availability-recovery-subsystem" err=FromOrigin { origin: "availability-recovery", source: Context("Signal channel is terminated and empty.") }
Error:
   0: Other: Essential task failed.
```
After second try to run seems to work.

**Comment by bkchr** [comment]
@TomaszWaszczyk please run a release build `cargo build --release`

**Comment by bkchr** [comment]
I see, it was accidentally enabled in our release builds...

When you want to make sure that the first error doesn't happen again, you need to recompile it yourself for now.
