### ISSUE TITLE
Error when starting dot service

### ISSUE THREAD

**Issue by 3461610003** [paritytech/polkadot#3512]
**start log info:**
```shell
Jul 22 22:23:49 usdt polkadot[11504]: Version: 0.9.8-3a10ee63c-x86_64-linux-gnu
Jul 22 22:23:49 usdt polkadot[11504]:    0: sp_panic_handler::set::{{closure}}
Jul 22 22:23:49 usdt polkadot[11504]:    1: std::panicking::rust_panic_with_hook
Jul 22 22:23:49 usdt polkadot[11504]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:595:17
Jul 22 22:23:49 usdt polkadot[11504]:    2: std::panicking::begin_panic_handler::{{closure}}
Jul 22 22:23:49 usdt polkadot[11504]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
Jul 22 22:23:49 usdt polkadot[11504]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Jul 22 22:23:49 usdt polkadot[11504]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
Jul 22 22:23:49 usdt polkadot[11504]:    4: rust_begin_unwind
Jul 22 22:23:49 usdt polkadot[11504]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
Jul 22 22:23:49 usdt polkadot[11504]:    5: core::panicking::panic_fmt
Jul 22 22:23:49 usdt polkadot[11504]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
Jul 22 22:23:49 usdt polkadot[11504]:    6: core::result::unwrap_failed
Jul 22 22:23:49 usdt polkadot[11504]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
Jul 22 22:23:49 usdt polkadot[11504]:    7: wasmtime_jit::code_memory::CodeMemory::publish
Jul 22 22:23:49 usdt polkadot[11504]:    8: wasmtime_jit::instantiate::CompiledModule::from_artifacts
Jul 22 22:23:49 usdt polkadot[11504]:    9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
Jul 22 22:23:49 usdt polkadot[11504]:   10: <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
Jul 22 22:23:49 usdt polkadot[11504]:   11: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter
Jul 22 22:23:49 usdt polkadot[11504]:   12: rayon::iter::plumbing::bridge_producer_consumer::helper
Jul 22 22:23:49 usdt polkadot[11504]:   13: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
Jul 22 22:23:49 usdt polkadot[11504]:   14: rayon::iter::plumbing::bridge
Jul 22 22:23:49 usdt polkadot[11504]:   15: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
Jul 22 22:23:49 usdt polkadot[11504]:   16: rayon::iter::ParallelIterator::collect
Jul 22 22:23:49 usdt polkadot[11504]:   17: wasmtime_jit::instantiate::CompiledModule::from_artifacts_list
Jul 22 22:23:49 usdt polkadot[11504]:   18: wasmtime::module::Module::from_binary
Jul 22 22:23:49 usdt polkadot[11504]:   19: wasmtime::module::Module::new
Jul 22 22:23:49 usdt polkadot[11504]:   20: sc_executor_wasmtime::runtime::do_create_runtime
polkadot[11504]:   21: sc_executor_wasmtime::runtime::create_runtime
polkadot[11504]:   22: sc_executor::wasm_runtime::create_wasm_runtime_with_code
polkadot[11504]:   23: sc_executor::wasm_runtime::create_versioned_wasm_runtime
polkadot[11504]:   24: sc_executor::wasm_runtime::RuntimeCache::with_instance
polkadot[11504]:   25: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
polkadot[11504]:   26: <hashbrown::map::HashMap<K,V,S,A> as core::iter::traits::collect::Extend<(K,V)>>::extend
polkadot[11504]:   27: core::iter::adapters::process_results
polkadot[11504]:   28: sc_service::client::wasm_substitutes::WasmSubstitutes<Block,Executor,Backend>::new
polkadot[11504]:   29: sc_service::client::call_executor::LocalCallExecutor<Block,B,E>::new
polkadot[11504]:   30: sc_service::builder::new_full_parts
polkadot[11504]:   31: polkadot_service::new_full
polkadot[11504]:   32: polkadot_service::build_full
polkadot[11504]:   33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
polkadot[11504]:   34: tokio::runtime::enter::Enter::block_on
polkadot[11504]:   35: tokio::runtime::context::enter
polkadot[11504]:   36: sc_cli::runner::Runner<C>::run_node_until_exit
polkadot[11504]:   37: polkadot_cli::command::run
polkadot[11504]:   38: polkadot::main
polkadot[11504]:   39: std::sys_common::backtrace::__rust_begin_short_backtrace
polkadot[11504]:   40: std::rt::lang_start::{{closure}}
polkadot[11504]:   41: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
polkadot[11504]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
polkadot[11504]:       std::panicking::try::do_call
polkadot[11504]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
polkadot[11504]:       std::panicking::try
polkadot[11504]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
polkadot[11504]:       std::panic::catch_unwind
polkadot[11504]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
polkadot[11504]:       std::rt::lang_start_internal
polkadot[11504]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
polkadot[11504]:   42: main
polkadot[11504]:   43: __libc_start_main
polkadot[11504]:   44: _start
polkadot[11504]: Thread 'main' panicked at 'unable to make memory readonly and executable: SystemCall(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-jit-0.27.0/src/code_memory.rs:151
polkadot[11504]: This is a bug. Please report it at:
polkadot[11504]: #011https://github.com/paritytech/polkadot/issues/new
systemd[1]: polkadot.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: polkadot.service: Failed with result 'exit-code'.
systemd[1]: polkadot.service: Service hold-off time over, scheduling restart.
systemd[1]: polkadot.service: Scheduled restart job, restart counter is at 3.
polkadot[11596]: 2021-07-22 22:23:49 Parity Polkadot
polkadot[11596]: 2021-07-22 22:23:49 ✌️  version 0.9.8-3a10ee63c-x86_64-linux-gnu
polkadot[11596]: 2021-07-22 22:23:49 ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
polkadot[11596]: 2021-07-22 22:23:49 📋 Chain specification: Polkadot
polkadot[11596]: 2021-07-22 22:23:49 🏷 Node name: wakeful-bomb-8152
polkadot[11596]: 2021-07-22 22:23:49 👤 Role: FULL
polkadot[11596]: 2021-07-22 22:23:49 💾 Database: RocksDb at /data/repo/polkadot/chains/polkadot/db
polkadot[11596]: 2021-07-22 22:23:49 ⛓  Native runtime: polkadot-9080 (parity-polkadot-0.tx7.au0)

```

**Comment by ordian** [comment]
> MemoryDenyWriteExecute=true

I'm not a systemd expert, but judging by the name, it doesn't seem to play well with JIT-compilers such as wasmtime.
FWIW, there is https://github.com/paritytech/polkadot/blob/master/scripts/packaging/polkadot.service
