### ISSUE TITLE
"Cannot poll Select twice" crash

### ISSUE THREAD

**Issue by kwingram25** [paritytech/polkadot#357]
Trying to run ```--dev``` on branch [gav-int-claims](https://github.com/paritytech/polkadot/tree/gav-int-claims) and master

```
2019-08-06 16:04:27 Running in --dev mode, RPC CORS has been disabled.
2019-08-06 16:04:27 Parity Polkadot
2019-08-06 16:04:27   version 0.5.0-8868c688-x86_64-linux-gnu
2019-08-06 16:04:27   by Parity Team <admin@parity.io>, 2017-2019
2019-08-06 16:04:27 Chain specification: Development
2019-08-06 16:04:27 Node name: successful-feast-5091
2019-08-06 16:04:27 Roles: AUTHORITY
2019-08-06 16:04:30 Initializing Genesis block/state (state: 0x9ea8…886b, header-hash: 0x7abe…02e1)
2019-08-06 16:04:35 Loaded block-time = 6 seconds from genesis on first-launch
2019-08-06 16:04:35 Loading GRANDPA authority set from genesis on what appears to be first startup.
2019-08-06 16:04:37 Highest known block at #0
2019-08-06 16:04:37 Local node identity is: QmPFcyAjskzGQbUnzGJ51twWxUUpv3tpTEPdrdyj6B4tRJ
2019-08-06 16:04:38 Using authority key 5FA9nQDVg267DEd8m1ZypXLBnvN7SFxYwV7ndqSYGiN9TTpu
2019-08-06 16:04:43 Idle (0 peers), best: #0 (0x7abe…02e1), finalized #0 (0x7abe…02e1), ⬇ 0 ⬆ 0
2019-08-06 16:04:48 Idle (0 peers), best: #0 (0x7abe…02e1), finalized #0 (0x7abe…02e1), ⬇ 0 ⬆ 0
2019-08-06 16:04:50 Starting parachain attestation session on top of parent 0x7abe65755933b71f5be6e8a10fcd60f3cc5d7e692b73e827ec31fe51cd6302e1. Local parachain duty is Relay
2019-08-06 16:04:51 Encountered consensus error: ClientImport("Timeout in the AuRa proposer")
2019-08-06 16:04:51 Authorship task terminated unexpectedly. Restarting

====================

stack backtrace:
   0: substrate_panic_handler::panic_hook::h1d13c723ce36219f (0x557aa6beee84)
             at /home/keith/.cargo/git/checkouts/substrate-7e08433d4c370a21/f9e5a37/core/panic-handler/src/lib.rs:82
   1: substrate_panic_handler::set::{{closure}}::hf9d573a8b06b004d (0x557aa6beea27)
             at /home/keith/.cargo/git/checkouts/substrate-7e08433d4c370a21/f9e5a37/core/panic-handler/src/lib.rs:31
   2: std::panicking::rust_panic_with_hook::h057ff03eb4c8000f (0x557aa70ee549)
             at src/libstd/panicking.rs:478
   3: std::panicking::continue_panic_fmt::ha6d6ae144369025b (0x557aa70edfe2)
             at src/libstd/panicking.rs:381
   4: rust_begin_unwind (0x557aa70edec6)
             at src/libstd/panicking.rs:308
   5: core::panicking::panic_fmt::hc4f83bfed80aeabd (0x557aa710be8d)
             at src/libcore/panicking.rs:85
   6: core::option::expect_failed::he602aa67d6d2d670 (0x557aa710bef7)
             at src/libcore/option.rs:1036
   7: core::option::Option<T>::expect::h29477bebeac1314e (0x557aa3a83ef3)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/option.rs:314
   8: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll::h7ecc0df6b32e4d36 (0x557aa4e35330)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/future/select.rs:57
   9: <futures_util::future::map::Map<Fut,F> as core::future::future::Future>::poll::h4bd93adb40e456d5 (0x557aa4c8d154)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/future/map.rs:37
  10: <F as futures_core::future::TryFuture>::try_poll::h82233fe8841507e5 (0x557aa4c8d0a5)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.17/src/future/mod.rs:78
  11: <futures_util::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll::he98eddfe70ccacd4 (0x557aa4a89c96)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/try_future/map_ok.rs:42
  12: <core::pin::Pin<P> as core::future::future::Future>::poll::h212ad0c0cd4081df (0x557aa4474e41)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/future/future.rs:117
  13: <F as futures_core::future::TryFuture>::try_poll::h3c12f624327636d6 (0x557aa4473e45)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.17/src/future/mod.rs:78
  14: <futures_util::try_future::map_err::MapErr<Fut,F> as core::future::future::Future>::poll::hf687c5f0589bf70a (0x557aa49697b4)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/try_future/map_err.rs:40
  15: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h4aaac981d256c4aa (0x557aa4e9ff11)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/future/either.rs:62
  16: <F as futures_core::future::TryFuture>::try_poll::hb2b96655889f9005 (0x557aa4e9fe65)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.17/src/future/mod.rs:78
  17: <futures_util::try_stream::try_for_each::TryForEach<St,Fut,F> as core::future::future::Future>::poll::he90f6c70f2e684d7 (0x557aa4e594ca)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/try_stream/try_for_each.rs:59
  18: substrate_consensus_slots::start_slot_worker::{{closure}}::{{closure}}::h81e621668945f0f8 (0x557aa45c06db)
             at /home/keith/.cargo/git/checkouts/substrate-7e08433d4c370a21/f9e5a37/core/consensus/slots/src/lib.rs:118
  19: core::ops::function::FnOnce::call_once::h483b396b192e27a2 (0x557aa4cc2ba4)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha1c7e2aacd4ca171 (0x557aa4d35dd5)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:315
  21: std::panicking::try::do_call::h8f8c068655e18739 (0x557aa4d83ccc)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:293
  22: __rust_maybe_catch_panic (0x557aa70f7a2a)
             at src/libpanic_unwind/lib.rs:85
  23: std::panicking::try::h18fa34a836e3cc05 (0x557aa4d7bb06)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
  24: std::panic::catch_unwind::hce2e4f3172ebf3c6 (0x557aa4d36825)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
  25: substrate_consensus_slots::start_slot_worker::{{closure}}::h509ba5b807e2e082 (0x557aa45bf1b5)
             at /home/keith/.cargo/git/checkouts/substrate-7e08433d4c370a21/f9e5a37/core/consensus/slots/src/lib.rs:118
  26: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h30c3550057db2539 (0x557aa41af1ae)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/future/poll_fn.rs:55
  27: <futures_util::future::map::Map<Fut,F> as core::future::future::Future>::poll::hf95e44cd681487c9 (0x557aa4c8d1ef)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/future/map.rs:37
  28: <F as futures_core::future::TryFuture>::try_poll::h7c27050c0453127a (0x557aa4c8d06e)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.17/src/future/mod.rs:78
  29: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::{{closure}}::heb8a49261e162527 (0x557aa41a86ee)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/compat/compat03as01.rs:106
  30: futures_util::compat::compat03as01::with_context::h8f43dbfc4b24fbc5 (0x557aa419fe12)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/compat/compat03as01.rs:209
  31: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::hd4eed86bb2c60deb (0x557aa41a8674)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/compat/compat03as01.rs:106
  32: <alloc::boxed::Box<F> as futures::future::Future>::poll::h4b188005d33e1235 (0x557aa6a59ef5)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/mod.rs:113
  33: <alloc::boxed::Box<F> as futures::future::Future>::poll::h4b188005d33e1235 (0x557aa6a59ef5)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/future/mod.rs:113
  34: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::h51c89b1dd9f1ccd9 (0x557aa64723a4)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:329
  35: futures::task_impl::Spawn<T>::enter::{{closure}}::h4cc06e662a2cfc99 (0x557aa6472681)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:399
  36: futures::task_impl::std::set::h9d9a8bafad088052 (0x557aa646b976)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/std/mod.rs:83
  37: futures::task_impl::Spawn<T>::enter::hf195ba4f9466f796 (0x557aa64725ef)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:399
  38: futures::task_impl::Spawn<T>::poll_fn_notify::h99634260985426f1 (0x557aa6472238)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:291
  39: futures::task_impl::Spawn<T>::poll_future_notify::hbf5977bc5e317082 (0x557aa6472378)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:329
  40: tokio_threadpool::task::Task::run::{{closure}}::h0a584b3838b23ab0 (0x557aa6474112)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/task/mod.rs:145
  41: core::ops::function::FnOnce::call_once::h47c43b45737e79f3 (0x557aa647f639)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  42: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3bb684dd2ea23bf9 (0x557aa64716f9)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:315
  43: std::panicking::try::do_call::hf1f2e5b06458ef90 (0x557aa6495433)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:293
  44: __rust_maybe_catch_panic (0x557aa70f7a2a)
             at src/libpanic_unwind/lib.rs:85
  45: std::panicking::try::hfa15cc5b6948ed45 (0x557aa64951f0)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
  46: std::panic::catch_unwind::h872f56d10d1c82d6 (0x557aa6471c81)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
  47: tokio_threadpool::task::Task::run::h255c3e4b81b17c97 (0x557aa647396e)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/task/mod.rs:130
  48: tokio_threadpool::worker::Worker::run_task2::h014da9cc7a3308bf (0x557aa648f5af)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:567
  49: tokio_threadpool::worker::Worker::run_task::hde0b7856744b98c3 (0x557aa648ee74)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:459
  50: tokio_threadpool::worker::Worker::try_run_owned_task::h91fa24b94acc521c (0x557aa648e4f3)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:390
  51: tokio_threadpool::worker::Worker::try_run_task::hc67c3c14eee73929 (0x557aa648df2d)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:297
  52: tokio_threadpool::worker::Worker::run::h3a47e0852cfaeb16 (0x557aa648dd86)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:241
  53: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h2addc8d0d99b2456 (0x557aa64227cc)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:390
  54: tokio_timer::timer::handle::with_default::{{closure}}::h2c82a81ec773a463 (0x557aa6418f2e)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:101
  55: std::thread::local::LocalKey<T>::try_with::h9c2cdb2fd65e9714 (0x557aa641a8a7)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:299
  56: std::thread::local::LocalKey<T>::with::h2a6fa36bf1faeea1 (0x557aa6419ad3)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:245
  57: tokio_timer::timer::handle::with_default::h3bf99c6eba0a7999 (0x557aa6418d73)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:84
  58: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::h8e84e539a601006e (0x557aa642282c)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:382
  59: tokio_timer::clock::clock::with_default::{{closure}}::h5ccbec523aaa18b6 (0x557aa641f851)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:137
  60: std::thread::local::LocalKey<T>::try_with::hb119688dd5477fd7 (0x557aa641ab1b)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:299
  61: std::thread::local::LocalKey<T>::with::hed2364d3a5347e35 (0x557aa6419c8d)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:245
  62: tokio_timer::clock::clock::with_default::h7a52ef238915ebef (0x557aa641f73e)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:117
  63: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::h3d19e0770615dd3b (0x557aa642287d)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:381
  64: tokio_reactor::with_default::{{closure}}::hba8da87efba55cae (0x557aa642425f)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:237
  65: std::thread::local::LocalKey<T>::try_with::hb3faecdde7535aff (0x557aa641ad83)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:299
  66: std::thread::local::LocalKey<T>::with::h6bc8d971a18ff986 (0x557aa6419c0d)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:245
  67: tokio_reactor::with_default::hfe83d367485e920b (0x557aa6424025)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:217
  68: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h57852bafce53fb0f (0x557aa6422920)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:380
  69: tokio_threadpool::callback::Callback::call::hcf2ecb0f220fe4d0 (0x557aa647bcf3)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/callback.rs:22
  70: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::h6fff310d88d852a1 (0x557aa648da0f)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:127
  71: tokio_executor::global::with_default::{{closure}}::h36685f913ae62048 (0x557aa646ac2b)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:209
  72: std::thread::local::LocalKey<T>::try_with::h4f8f279be1a44fe3 (0x557aa648aeef)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:299
  73: std::thread::local::LocalKey<T>::with::h11a0595368e7c294 (0x557aa648a6f3)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:245
  74: tokio_executor::global::with_default::h3631a1bf65b1db73 (0x557aa646ab06)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:178
  75: tokio_threadpool::worker::Worker::do_run::{{closure}}::hdb7c2f8a140b1923 (0x557aa648dacd)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:125
  76: std::thread::local::LocalKey<T>::try_with::hb85e6d6e389a5d5e (0x557aa648b62a)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:299
  77: std::thread::local::LocalKey<T>::with::h01415c0d459dcde0 (0x557aa648a67e)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/local.rs:245
  78: tokio_threadpool::worker::Worker::do_run::hd722958f6797e041 (0x557aa648d8e8)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:116
  79: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::h886849a5e37b3a07 (0x557aa6493b62)
             at /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/pool/mod.rs:344
  80: std::sys_common::backtrace::__rust_begin_short_backtrace::h32dad1877f46defe (0x557aa64895fe)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/sys_common/backtrace.rs:136
  81: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h61259e65156cd4b4 (0x557aa647eb92)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/mod.rs:470
  82: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfa08614e590d8214 (0x557aa6471742)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:315
  83: std::panicking::try::do_call::h84da9beaf1fce480 (0x557aa64953bc)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:293
  84: __rust_maybe_catch_panic (0x557aa70f7a2a)
             at src/libpanic_unwind/lib.rs:85
  85: std::panicking::try::h796683b233e2df2b (0x557aa6495022)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
  86: std::panic::catch_unwind::h531a2409e0f9f810 (0x557aa6471c32)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
  87: std::thread::Builder::spawn_unchecked::{{closure}}::h7d4664047f45e85b (0x557aa647e986)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/mod.rs:469
  88: core::ops::function::FnOnce::call_once{{vtable.shim}}::he38e33f99b9abcd3 (0x557aa647f594)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  89: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h805c3cc89d534c05 (0x557aa70daccf)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  90: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9ebda9db5f03daf3 (0x557aa70f6d40)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
      std::sys_common::thread::start_thread::ha32838ccbb8a8179
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h6f10b78f26c98dc6
             at src/libstd/sys/unix/thread.rs:79
  91: start_thread (0x7f2106fa06db)
  92: __clone (0x7f2106ab188f)
  93: <unknown> (0x0)

Thread 'tokio-runtime-worker-6' panicked at 'cannot poll Select twice', src/libcore/option.rs:1036

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
```

**Comment by jacogr** [comment]
Closing, solved by building/running with `--release`
