### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'Trying to pin pending state',

### ISSUE THREAD

**Issue by sclark007** [paritytech/polkadot#3663]
- It would help if you submit info about the system you are running, e.g.: operating system, kernel version, amount of available memory and swap, etc.
- Logs could be very helpful. If possible, submit the whole log. Please format it as ```code blocks```.
- Describe the role your node plays, e.g. validator, full node or light client.
- Any command-line options were passed?

node is a activate validator that was in rotation during this crash. 

root@kusama-0:~# uname -a
Linux kusama-0 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Size
4 vCPUs
8GB / 80GB Disk

```
Aug 19 00:53:30 kusama-0 polkadot[86645]: 2021-08-19 00:53:30 ✨ Imported #8849522 (0xda2b…affb)
Aug 19 00:53:30 kusama-0 polkadot[86645]: ====================
Aug 19 00:53:30 kusama-0 polkadot[86645]: Version: 0.9.8-3a10ee63c-x86_64-linux-gnu
Aug 19 00:53:30 kusama-0 polkadot[86645]:    0: sp_panic_handler::set::{{closure}}
Aug 19 00:53:30 kusama-0 polkadot[86645]:    1: std::panicking::rust_panic_with_hook
Aug 19 00:53:30 kusama-0 polkadot[86645]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:595:17
Aug 19 00:53:30 kusama-0 polkadot[86645]:    2: std::panicking::begin_panic::{{closure}}
Aug 19 00:53:30 kusama-0 polkadot[86645]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Aug 19 00:53:30 kusama-0 polkadot[86645]:    4: std::panicking::begin_panic
Aug 19 00:53:30 kusama-0 polkadot[86645]:    5: sc_state_db::noncanonical::NonCanonicalOverlay<BlockHash,Key>::pin
Aug 19 00:53:30 kusama-0 polkadot[86645]:    6: sc_state_db::StateDb<BlockHash,Key>::pin
Aug 19 00:53:30 kusama-0 polkadot[86645]:    7: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::state_at
Aug 19 00:53:30 kusama-0 polkadot[86645]:    8: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::runtime_version
Aug 19 00:53:30 kusama-0 polkadot[86645]:    9: <kusama_runtime::RuntimeApiImpl<Block,C> as sp_api::ApiExt<Block>>::api_version
Aug 19 00:53:30 kusama-0 polkadot[86645]:   10: tracing::span::Span::in_scope
Aug 19 00:53:30 kusama-0 polkadot[86645]:   11: sc_transaction_pool::api::validate_transaction_blocking
Aug 19 00:53:30 kusama-0 polkadot[86645]:   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 19 00:53:30 kusama-0 polkadot[86645]:   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 19 00:53:30 kusama-0 polkadot[86645]:   14: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Aug 19 00:53:30 kusama-0 polkadot[86645]:   15: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Aug 19 00:53:30 kusama-0 polkadot[86645]:   16: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Aug 19 00:53:30 kusama-0 polkadot[86645]:   17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 19 00:53:30 kusama-0 polkadot[86645]:   18: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Aug 19 00:53:30 kusama-0 polkadot[86645]:   19: std::thread::local::LocalKey<T>::with
Aug 19 00:53:30 kusama-0 polkadot[86645]:   20: futures_executor::local_pool::block_on
Aug 19 00:53:30 kusama-0 polkadot[86645]:   21: tokio::runtime::task::core::Core<T,S>::poll
Aug 19 00:53:30 kusama-0 polkadot[86645]:   22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Aug 19 00:53:30 kusama-0 polkadot[86645]:   23: tokio::runtime::task::raw::poll
Aug 19 00:53:30 kusama-0 polkadot[86645]:   24: tokio::runtime::blocking::pool::Inner::run
Aug 19 00:53:30 kusama-0 polkadot[86645]:   25: tokio::runtime::context::enter
Aug 19 00:53:30 kusama-0 polkadot[86645]:   26: std::sys_common::backtrace::__rust_begin_short_backtrace
Aug 19 00:53:30 kusama-0 polkadot[86645]:   27: core::ops::function::FnOnce::call_once{{vtable.shim}}
Aug 19 00:53:30 kusama-0 polkadot[86645]:   28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Aug 19 00:53:30 kusama-0 polkadot[86645]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
Aug 19 00:53:30 kusama-0 polkadot[86645]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Aug 19 00:53:30 kusama-0 polkadot[86645]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
Aug 19 00:53:30 kusama-0 polkadot[86645]:       std::sys::unix::thread::Thread::new::thread_start
Aug 19 00:53:30 kusama-0 polkadot[86645]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
Aug 19 00:53:30 kusama-0 polkadot[86645]:   29: start_thread
Aug 19 00:53:30 kusama-0 polkadot[86645]:   30: clone
Aug 19 00:53:30 kusama-0 polkadot[86645]: Thread 'tokio-runtime-worker' panicked at 'Trying to pin pending state', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/1b758b2/client/state-db/src/noncanonical.rs:527
```

**Comment by sclark007** [comment]
here is another crash. 

```
Aug 17 08:50:54 kusama-0 polkadot[84015]: Version: 0.9.8-3a10ee63c-x86_64-linux-gnu
Aug 17 08:50:54 kusama-0 polkadot[84015]:    0: sp_panic_handler::set::{{closure}}
Aug 17 08:50:54 kusama-0 polkadot[84015]:    1: std::panicking::rust_panic_with_hook
Aug 17 08:50:54 kusama-0 polkadot[84015]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:595:17
Aug 17 08:50:54 kusama-0 polkadot[84015]:    2: std::panicking::begin_panic::{{closure}}
Aug 17 08:50:54 kusama-0 polkadot[84015]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Aug 17 08:50:54 kusama-0 polkadot[84015]:    4: std::panicking::begin_panic
Aug 17 08:50:54 kusama-0 polkadot[84015]:    5: sc_state_db::noncanonical::NonCanonicalOverlay<BlockHash,Key>::pin
Aug 17 08:50:54 kusama-0 polkadot[84015]:    6: sc_state_db::StateDb<BlockHash,Key>::pin
Aug 17 08:50:54 kusama-0 polkadot[84015]:    7: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::state_at
Aug 17 08:50:54 kusama-0 polkadot[84015]:    8: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::runtime_ve
rsion
Aug 17 08:50:54 kusama-0 polkadot[84015]:    9: <kusama_runtime::RuntimeApiImpl<Block,C> as sp_api::ApiExt<Block>>::api_version
Aug 17 08:50:54 kusama-0 polkadot[84015]:   10: tracing::span::Span::in_scope
Aug 17 08:50:54 kusama-0 polkadot[84015]:   11: sc_transaction_pool::api::validate_transaction_blocking
Aug 17 08:50:54 kusama-0 polkadot[84015]:   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 17 08:50:54 kusama-0 polkadot[84015]:   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 17 08:50:54 kusama-0 polkadot[84015]:   14: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Aug 17 08:50:54 kusama-0 polkadot[84015]:   15: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Aug 17 08:50:54 kusama-0 polkadot[84015]:   16: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Aug 17 08:50:54 kusama-0 polkadot[84015]:   17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 17 08:50:54 kusama-0 polkadot[84015]:   18: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Aug 17 08:50:54 kusama-0 polkadot[84015]:   19: std::thread::local::LocalKey<T>::with
Aug 17 08:50:54 kusama-0 polkadot[84015]:   20: futures_executor::local_pool::block_on
Aug 17 08:50:54 kusama-0 polkadot[84015]:   21: tokio::runtime::task::core::Core<T,S>::poll
Aug 17 08:50:54 kusama-0 polkadot[84015]:   22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Aug 17 08:50:54 kusama-0 polkadot[84015]:   23: tokio::runtime::task::raw::poll
Aug 17 08:50:54 kusama-0 polkadot[84015]:   24: tokio::runtime::blocking::pool::Inner::run
Aug 17 08:50:54 kusama-0 polkadot[84015]:   25: tokio::runtime::context::enter
Aug 17 08:50:54 kusama-0 polkadot[84015]:   26: std::sys_common::backtrace::__rust_begin_short_backtrace
Aug 17 08:50:54 kusama-0 polkadot[84015]:   27: core::ops::function::FnOnce::call_once{{vtable.shim}}
Aug 17 08:50:54 kusama-0 polkadot[84015]:   28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Aug 17 08:50:54 kusama-0 polkadot[84015]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
Aug 17 08:50:54 kusama-0 polkadot[84015]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Aug 17 08:50:54 kusama-0 polkadot[84015]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
Aug 17 08:50:54 kusama-0 polkadot[84015]:       std::sys::unix::thread::Thread::new::thread_start
Aug 17 08:50:54 kusama-0 polkadot[84015]:              at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
Aug 17 08:50:54 kusama-0 polkadot[84015]:   29: start_thread
Aug 17 08:50:54 kusama-0 polkadot[84015]:   30: clone
Aug 17 08:50:54 kusama-0 polkadot[84015]: Thread 'tokio-runtime-worker' panicked at 'Trying to pin pending state', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/1b758
b2/client/state-db/src/noncanonical.rs:527
```

**Comment by bkchr** [comment]
You are using a debug build, please just use the 0.9.9 release.
