### ISSUE TITLE
Node crash

### ISSUE THREAD

**Issue by nschwermann** [paritytech/polkadot#3687]
I have been running a node with `polkadot --dev` and when making RPC call sometimes it will crash with this stacktrace and message:

```
Version: 0.9.0-c418fa807-x86_64-macos

   0: backtrace::backtrace::libunwind::trace
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/libunwind.rs:90:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:66:5
      backtrace::backtrace::trace
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:53:14
   1: backtrace::capture::Backtrace::create
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:176:9
      backtrace::capture::Backtrace::new
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:140:22
   2: sp_panic_handler::panic_hook
             at /Users/admin/.cargo/git/checkouts/substrate-7e08433d4c370a21/dc9acd2/primitives/panic-handler/src/lib.rs:150:18
   3: sp_panic_handler::set::{{closure}}
             at /Users/admin/.cargo/git/checkouts/substrate-7e08433d4c370a21/dc9acd2/primitives/panic-handler/src/lib.rs:60:4
   4: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   5: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:495:13
   6: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   7: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   8: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   9: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
  10: hyper::proto::h1::conn::State::prepare_upgrade
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h1/conn.rs:872:9
  11: hyper::proto::h1::conn::Conn<I,B,T>::on_upgrade
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h1/conn.rs:636:9
  12: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_read_head
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h1/dispatch.rs:237:41
  13: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_read
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h1/dispatch.rs:163:28
  14: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h1/dispatch.rs:129:13
  15: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h1/dispatch.rs:106:20
  16: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h1/dispatch.rs:93:9
  17: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as futures::future::Future>::poll
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h1/dispatch.rs:374:9
  18: <futures::future::either::Either<A,B> as futures::future::Future>::poll
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/either.rs:35:37
  19: futures::future::option::<impl futures::future::Future for core::option::Option<F>>::poll
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/option.rs:12:32
  20: <hyper::server::conn::Connection<I,S,E> as futures::future::Future>::poll
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/server/conn.rs:636:19
  21: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/map_err.rs:30:23
  22: futures::future::chain::Chain<A,B,C>::poll
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:26:23
  23: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/then.rs:32:9
  24: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113:13
  25: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329:45
  26: futures::task_impl::Spawn<T>::enter::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399:27
  27: futures::task_impl::std::set
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83:13
  28: futures::task_impl::Spawn<T>::enter
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399:9
  29: futures::task_impl::Spawn<T>::poll_fn_notify
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291:9
  30: futures::task_impl::Spawn<T>::poll_future_notify
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329:9
  31: tokio_threadpool::task::Task::run::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/task/mod.rs:145:17
  32: core::ops::function::FnOnce::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
  33: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:344:9
  34: std::panicking::try::do_call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
  35: ___rust_try
  36: std::panicking::try
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
  37: std::panic::catch_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
  38: tokio_threadpool::task::Task::run
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/task/mod.rs:130:19
  39: tokio_threadpool::worker::Worker::run_task2
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:567:9
  40: tokio_threadpool::worker::Worker::run_task
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:459:19
  41: tokio_threadpool::worker::Worker::try_run_owned_task
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:390:17
  42: tokio_threadpool::worker::Worker::try_run_task
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:297:12
  43: tokio_threadpool::worker::Worker::run
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:241:16
  44: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:390:29
  45: tokio_timer::timer::handle::with_default
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/timer/handle.rs:74:5
  46: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:382:25
  47: tokio_timer::clock::clock::with_default
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/clock/clock.rs:125:5
  48: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:381:21
  49: tokio_reactor::with_default
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.12/src/lib.rs:220:5
  50: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:380:17
  51: tokio_threadpool::callback::Callback::call
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/callback.rs:22:9
  52: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:127:21
  53: tokio_executor::global::with_default::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.10/src/global.rs:221:9
  54: std::thread::local::LocalKey<T>::try_with
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:272:16
  55: std::thread::local::LocalKey<T>::with
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:9
  56: tokio_executor::global::with_default
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.10/src/global.rs:190:5
  57: tokio_threadpool::worker::Worker::do_run::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:125:13
  58: std::thread::local::LocalKey<T>::try_with
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:272:16
  59: std::thread::local::LocalKey<T>::with
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:9
  60: tokio_threadpool::worker::Worker::do_run
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:116:9
  61: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/pool/mod.rs:345:21
  62: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:125:18
  63: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/mod.rs:474:17
  64: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:344:9
  65: std::panicking::try::do_call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
  66: ___rust_try
  67: std::panicking::try
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
  68: std::panic::catch_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
  69: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/mod.rs:473:30
  70: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
  71: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  72: __pthread_start


Thread 'http.worker30' panicked at 'assertion failed: self.upgrade.is_none()', /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h1/conn.rs:872

This is a bug. Please report it at:
```

**Comment by bkchr** [comment]
@nschwermann which RPC call did you used?

**Comment by bkchr** [comment]
Ahh and could you please test with master. We have updated the dependency that is failing, maybe it is resolved now.
