### ISSUE TITLE
Node crash when port taken

### ISSUE THREAD

**Issue by nschwermann** [paritytech/polkadot#3688]
Just running with ./polkadot --dev  when some zombie instance is using the port.

```
Error: 
   0: Backend error: IO error: While lock file: /Users/Admin/Library/Application Support/polkadot/chains/dev/db/LOCK: Resource temporarily unavailable

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
nschwermann@Nathans-iMac debug % rm /Users/Admin/Library/Application\ Support/polkadot/chains/dev/db/LOCK
nschwermann@Nathans-iMac debug % ./polkadot --dev                                                              
2021-08-22 14:29:05 Running in --dev mode, RPC CORS has been disabled.    
2021-08-22 14:29:05 Parity Polkadot    
2021-08-22 14:29:05 ✌️  version 0.9.9-a1b08f94f-x86_64-macos    
2021-08-22 14:29:05 ❤️  by Parity Technologies <admin@parity.io>, 2017-2021    
2021-08-22 14:29:05 📋 Chain specification: Development    
2021-08-22 14:29:05 🏷 Node name: alleged-grade-6465    
2021-08-22 14:29:05 👤 Role: AUTHORITY    
2021-08-22 14:29:05 💾 Database: RocksDb at /Users/Admin/Library/Application Support/polkadot/chains/dev/db    
2021-08-22 14:29:05 ⛓  Native runtime: polkadot-9090 (parity-polkadot-0.tx7.au0)    
2021-08-22 14:29:05 🏷 Local node identity is: 12D3KooWQu39YzpPZxqFe3JN5tdSHBiKWuKrvL6JYw8KL4KzY8q1    
2021-08-22 14:29:05 Can't listen on /ip6/::/tcp/30333 because: Other(Custom { kind: Other, error: Other(A(A(A(A(Transport(B(Os { code: 48, kind: AddrInUse, message: "Address already in use" }))))))) })    
2021-08-22 14:29:05 Can't listen on /ip4/0.0.0.0/tcp/30333 because: Other(Custom { kind: Other, error: Other(A(A(A(A(Transport(B(Os { code: 48, kind: AddrInUse, message: "Address already in use" }))))))) })    

====================

Version: 0.9.9-a1b08f94f-x86_64-macos

   0: backtrace::backtrace::libunwind::trace
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/libunwind.rs:90:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:66:5
      backtrace::backtrace::trace
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/backtrace/mod.rs:53:14
   1: backtrace::capture::Backtrace::create
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:176:9
      backtrace::capture::Backtrace::new
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.56/src/capture.rs:140:22
   2: sp_panic_handler::panic_hook
             at /Users/Admin/.cargo/git/checkouts/substrate-7e08433d4c370a21/74e839b/primitives/panic-handler/src/lib.rs:145:18
   3: sp_panic_handler::set::{{closure}}
             at /Users/Admin/.cargo/git/checkouts/substrate-7e08433d4c370a21/74e839b/primitives/panic-handler/src/lib.rs:61:12
   4: std::panicking::rust_panic_with_hook
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:626:17
   5: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:517:13
   6: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
   7: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   8: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   9: core::panicking::panic
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
  10: sc_service::builder::build_network::{{closure}}
             at /Users/Admin/.cargo/git/checkouts/substrate-7e08433d4c370a21/74e839b/client/service/src/builder.rs:1029:4
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
  12: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
             at /Users/Admin/.cargo/git/checkouts/substrate-7e08433d4c370a21/74e839b/client/service/src/task_manager/prometheus_future.rs:61:3
  13: <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:364:9
  14: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.16/src/future/future/catch_unwind.rs:36:42
  15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  16: std::panicking::try::do_call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  17: ___rust_try
  18: std::panicking::try
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  19: std::panic::catch_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  20: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.16/src/future/future/catch_unwind.rs:36:9
  21: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/future.rs:119:9
  22: futures_util::future::future::FutureExt::poll_unpin
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.16/src/future/future/mod.rs:562:9
  23: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.16/src/future/select.rs:105:36
  24: sc_service::task_manager::SpawnTaskHandle::spawn_inner::{{closure}}
             at /Users/Admin/.cargo/git/checkouts/substrate-7e08433d4c370a21/74e839b/client/service/src/task_manager/mod.rs:112:11
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
  26: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.4/src/lib.rs:258:9
  27: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/future.rs:119:9
  28: futures_executor::local_pool::block_on::{{closure}}
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.16/src/local_pool.rs:315:23
  29: futures_executor::local_pool::run_executor::{{closure}}
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.16/src/local_pool.rs:90:37
  30: std::thread::local::LocalKey<T>::try_with
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:400:16
  31: std::thread::local::LocalKey<T>::with
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:376:9
  32: futures_executor::local_pool::run_executor
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.16/src/local_pool.rs:86:5
  33: futures_executor::local_pool::block_on
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.16/src/local_pool.rs:315:5
  34: sc_cli::runner::Runner<C>::new::{{closure}}::{{closure}}
             at /Users/Admin/.cargo/git/checkouts/substrate-7e08433d4c370a21/74e839b/client/cli/src/runner.rs:123:29
  35: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/task.rs:38:21
  36: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:173:17
  37: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/loom/std/unsafe_cell.rs:14:9
  38: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:158:13
  39: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:107:27
  40: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  41: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  42: std::panicking::try::do_call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  43: ___rust_try
  44: std::panicking::try
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  45: std::panic::catch_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  46: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:89:19
  47: tokio::runtime::task::raw::poll
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:104:5
  48: tokio::runtime::task::raw::RawTask::poll
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:66:18
  49: tokio::runtime::task::Notified<S>::run
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/mod.rs:169:9
  50: tokio::runtime::blocking::pool::Inner::run
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/pool.rs:230:17
  51: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/pool.rs:210:21
  52: tokio::runtime::context::enter
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/context.rs:72:5
  53: tokio::runtime::handle::Handle::enter
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/handle.rs:76:9
  54: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/Admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/pool.rs:209:17
  55: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  56: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:481:17
  57: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  58: std::panicking::try::do_call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  59: ___rust_try
  60: std::panicking::try
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  61: std::panic::catch_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  62: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:480:30
  63: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  64: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys/unix/thread.rs:71:17
  65: __pthread_start


Thread 'tokio-runtime-worker' panicked at 'assertion failed: false', /Users/Admin/.cargo/git/checkouts/substrate-7e08433d4c370a21/74e839b/client/service/src/builder.rs:1029

```

**Comment by bkchr** [comment]
@tomaka we should probably remove the debug_assert? Or at least not let it trigger when a port could not be bound.

**Comment by tomaka** [comment]
I don't think it's related to the port being in use. This assertion can only be reached if the networking initialized properly. However it could indeed happen if an error happens between the moment `build_network` returns and when `network_starter.start_network();` is called.

So yeah, we could remove the assertion.
