### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by i5possible** [paritytech/polkadot#3829]
./target/release/polkadot --chain ./rococo_local.json -d cumulus_relay1 --validator --bob --port 50556 \
        --bootnodes /ip4/127.0.0.1/tcp/50555/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
2021-09-11 14:46:04 Parity Polkadot
2021-09-11 14:46:04 ✌️  version 0.9.9-4c8dda20a-x86_64-macos
2021-09-11 14:46:04 ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
2021-09-11 14:46:04 📋 Chain specification: Rococo Local Testnet
2021-09-11 14:46:04 🏷 Node name: Bob
2021-09-11 14:46:04 👤 Role: AUTHORITY
2021-09-11 14:46:04 💾 Database: RocksDb at cumulus_relay1/chains/rococo_local_testnet/db/full
2021-09-11 14:46:04 ⛓  Native runtime: rococo-9102 (parity-rococo-v1.7-0.tx0.au0)
2021-09-11 14:46:05 🔨 Initializing Genesis block/state (state: 0x50e3…2d86, header-hash: 0xa937…9821)
2021-09-11 14:46:05 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
2021-09-11 14:46:06 ⏱  Loaded block-time = 6s from block 0xa93748593640e4fb1efc423475777319240c481d95a445df466acadf53e19821
2021-09-11 14:46:06 👶 Creating empty BABE epoch changes on what appears to be first startup.
2021-09-11 14:46:06 🏷 Local node identity is: 12D3KooWG6C75sqK4UfxTHT7FqZ6rhGYMJKHH5fkQjoR3RJqAAMZ
2021-09-11 14:46:07 📦 Highest known block at #0
2021-09-11 14:46:07 Unable to listen on 127.0.0.1:9944

====================

Version: 0.9.9-4c8dda20a-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:626:17
   4: std::panicking::begin_panic::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: std::panicking::begin_panic
   7: tokio::runtime::blocking::shutdown::Receiver::wait
   8: tokio::runtime::blocking::pool::BlockingPool::shutdown
   9: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
  10: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
  11: jsonrpc_ws_server::server::Server::start
  12: sc_rpc_server::inner::start_ws
  13: sc_service::start_rpc_servers::{{closure}}
  14: sc_service::start_rpc_servers
  15: sc_service::builder::spawn_tasks
  16: polkadot_service::new_full
  17: polkadot_service::build_full
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: tokio::park::thread::CachedParkThread::block_on
  20: tokio::runtime::thread_pool::ThreadPool::block_on
  21: tokio::runtime::Runtime::block_on
  22: sc_cli::runner::Runner<C>::run_node_until_exit
  23: polkadot_cli::command::run
  24: polkadot::main
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: std::rt::lang_start::{{closure}}
  27: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
      std::panicking::try
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
      std::panic::catch_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
      std::rt::lang_start_internal
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  28: _main

Thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /Users/hong.liang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/blocking/shutdown.rs:51

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

**Comment by bkchr** [comment]
Will be fixed by: https://github.com/paritytech/substrate/pull/9737

**Comment by ordian** [comment]
Use can specify a different `--ws-port` in the meantime
> Unable to listen on 127.0.0.1:9944
