### ISSUE TITLE
Offchain workers fail in wasm

### ISSUE THREAD

**Issue by lsaether** [paritytech/polkadot#385]
I am trying to do a runtime upgrade from [this branch](https://github.com/lsaether/polkadot/tree/ls-sane) to a runtime with sudo removed ([diff](https://github.com/lsaether/polkadot/commit/7c902774c09d6418c8e45e4148287b3dce412d5d)) it causes the node to crash with the following crash report:

```
<snip>
2019-08-18 19:02:48 Idle (0 peers), best: #6 (0x6a93…edf9), finalized #5 (0x69eb…8a76), ⬇ 0 ⬆ 0
2019-08-18 19:02:53 Idle (0 peers), best: #6 (0x6a93…edf9), finalized #6 (0x6a93…edf9), ⬇ 0 ⬆ 0
2019-08-18 19:02:56 Prepared block for proposing at 7 [hash: 0x03b84e3151c921bbbff5a99a4768381560d985afb4b2df08c8c21dcfc45387d9; parent_hash: 0x6a93…edf9; extri
nsics: [0xefc3…d54c, 0xeea1…8c48, 0xd267…0c81, 0x64a9…f515]]                                                                                                    
2019-08-18 19:02:56 Pre-sealed block for proposal at 7. Hash now 0x1b961cee7f843cb53922db91b53c63975fa563045e700a49b0553e5fd42c651f, previously 0x03b84e3151c921
bbbff5a99a4768381560d985afb4b2df08c8c21dcfc45387d9.                                                                                                             
2019-08-18 19:02:56 Imported #7 (0x1b96…651f)
2019-08-18 19:02:56 Starting parachain attestation session on top of parent 0x1b961cee7f843cb53922db91b53c63975fa563045e700a49b0553e5fd42c651f. Local parachain 
duty is None                            

====================

stack backtrace:                        
   0: substrate_panic_handler::set::{{closure}}::h603937a06fbb712c (0x55c77f9c74a0)
   1: std::panicking::rust_panic_with_hook::h82bdf4febc3f633b (0x55c77fafedd6)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::h99715f77bbc635a8 (0x55c77fafe872)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x55c77fafe756) 
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h0362d379eb2a6704 (0x55c77fb206dd)
             at src/libcore/panicking.rs:85
   5: core::option::expect_failed::h843e70e3ee4a2fe7 (0x55c77fb20747)
             at src/libcore/option.rs:1166
   6: sr_io::is_validator::hb7e03eaee05f994f (0x55c77f9a0c07)                                                                                                   
   7: <substrate_executor::wasm_executor::FunctionExecutor<E> as wasmi::host::Externals>::invoke_index::he237a98b5c8b98df (0x55c77ea27903)                      
   8: wasmi::func::FuncInstance::invoke::hf768fa121c5a8cb1 (0x55c77e8bd60a)                                                                                     
   9: wasmi::runner::Interpreter::start_execution::h70fce8232bdd2e5d (0x55c77ec416ca)                                                                           
  10: wasmi::func::FuncInstance::invoke::hf768fa121c5a8cb1 (0x55c77e8bd69c)                                                                                     
  11: substrate_executor::wasm_executor::WasmExecutor::call_in_wasm_module::h8e8df21f067ef3b6 (0x55c77ea34d87)                                                  
  12: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::cal
l::h35897eb15a0ff8d2 (0x55c77eca0577)                                                                                                                           
  13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::hcef4e142da35ed40 (0x55c77ed9cf3e)                                                    
  14: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h21a0e9914660799c (0x55c77eda7f4b)                        
  15: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blak
e2Hasher>>::contextual_call::h5f542689ad443d32 (0x55c77ece0009)                                                                                                 
  16: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::he0b167caba4a8374 (0x55c77ea53a44)  
  17: substrate_offchain_primitives::runtime_decl_for_OffchainWorkerApi::offchain_worker_call_api_at::h39c8aa5dc83b6eeb (0x55c77eb67733)                        
  18: substrate_offchain_primitives::OffchainWorkerApi::offchain_worker_with_context::hc292ec876e5a97c8 (0x55c77e895834)                                        
  19: std::sys_common::backtrace::__rust_begin_short_backtrace::hb7b544465c3635a8 (0x55c77ec03c9c)                                                              
  20: std::panicking::try::do_call::h59b17355c141d559 (0x55c77eee8dd6)                                                                                          
  21: __rust_maybe_catch_panic (0x55c77fb07eca)                                                                                                                 
             at src/libpanic_unwind/lib.rs:80                                                                                                                   
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d0f41c923b9bdb5 (0x55c77e89f136)  
  23: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h056a88eff3af7b93 (0x55c77faecfef)
             at /rustc/f7af19c279b8b7ea3d2c21fcbd67164af8d5d968/src/liballoc/boxed.rs:787
  24: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h494acbd958f0dea7 (0x55c77fb071f0)
             at /rustc/f7af19c279b8b7ea3d2c21fcbd67164af8d5d968/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread::hf214fb2e7cfb2066
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::hb7253c7ce40568ec
             at src/libstd/sys/unix/thread.rs:79                                                                                         
  25: start_thread (0x7f565b98757f)
  26: __clone (0x7f565b89d0e3)
  27: <unknown> (0x0)

Thread '<unnamed>' panicked at 'offchain-worker functions cannot be called outside of an Externalities-provided environment.', src/libcore/option.rs:1166

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new
```

Exported block 7
[block_7.txt](https://github.com/paritytech/polkadot/files/3513363/block_7.txt)
[block_7.bin.txt](https://github.com/paritytech/polkadot/files/3513364/block_7.bin.txt)

**Comment by gavofyork** [comment]
Actually, it's not the runtime upgrade that has failed, but rather the off-chain worker apparatus when the version has been bumped and there's now a mismatch (and thus it's forced to use the wasm environment). Attempting a substantial version upgrade *without* bumping the runtime spec_version doesn't do this, yet bumping the runtime version alone without any other changes does.
