### ISSUE TITLE
ParityDb issue

### ISSUE THREAD

**Issue by kogeler** [paritytech/polkadot#3894]
The `0.9.9-8b8d4c8c-x86_64-linux-gnu` has an issue:
```
====================
Version: 0.9.9-8b8d4c8c-x86_64-linux-gnu
   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:495:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   6: core::panicking::panic
             at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
   7: parity_db::table::ValueTable::next_free
   8: parity_db::table::ValueTable::overwrite_chain
   9: parity_db::column::Column::write_plan
  10: parity_db::db::DbInner::process_commits
  11: parity_db::db::Db::log_worker
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
  15: start_thread
  16: clone
Thread '<unnamed>' panicked at 'attempt to multiply with overflow', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/parity-db-0.3.1/src/table.rs:601
This is a bug. Please report it at:
        https://github.com/paritytech/polkadot/issues/new
```

The node uses ParityDb. Last block is #6524424.
Flags: `-name kusama-bootnode-0 --base-path /home/parity/.local/share/polkadot --listen-addr=/ip4/0.0.0.0/tcp/30334/ws --node-key-file /keys/kusamay --chain kusama --listen-addr=/ip4/0.0.0.0/tcp/30333 --public-addr=/ip4/51.77.66.187/tcp/30333 --in-peers 25 --out-peers 25 --database paritydb-experimental --db-cache 512 --pruning=1000 --unsafe-pruning --prometheus-external --prometheus-port 9615 --ws-port 9944 --ws-max-connections 100 --rpc-port 9933 --listen-addr /ip6/::/tcp/30333`

After restart with latest version (`0.9.9-07d1830-x86_64-linux-gnu`) from the master node can't start. There aren't any error messages.

**Comment by arkpar** [comment]
Could you provide a copy of the database?

**Comment by kogeler** [comment]
https://storage.googleapis.com/debug-releases/share/paritydb_20210920.tar

**Comment by kogeler** [comment]
It works with the `v0.9.10-rc2` version.
