### ISSUE TITLE
Flaky test `approval_undoes_stagnant_unlocking_subtree`

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot#3947]
```
test tests::approval_undoes_stagnant_unlocking_subtree ... FAILED
failures:
---- tests::approval_undoes_stagnant_unlocking_subtree stdout ----
thread 'tests::approval_undoes_stagnant_unlocking_subtree' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', node/core/chain-selection/src/tests.rs:112:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: polkadot_node_core_chain_selection::tests::TestBackend::assert_stagnant_at_state
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
   7: <futures_util::future::join::Join<Fut1,Fut2> as core::future::future::Future>::poll
   8: std::thread::local::LocalKey<T>::with
   9: futures_executor::local_pool::block_on
  10: polkadot_node_core_chain_selection::tests::approval_undoes_stagnant_unlocking_subtree
  11: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failures:
    tests::approval_undoes_stagnant_unlocking_subtree
```

**Comment by rphmeier** [comment]
I can't reproduce locally. But I have seen these in CI recently - this code hasn't been touched in a while so there must have been a dormant race condition activated by some recent change.
