### ISSUE TITLE
Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by phillux** [paritytech/polkadot#409]
Polkadot: 0.60
Rust: stable-x86_64-unknown-linux-gnu unchanged - rustc 1.37.0 (eae3437df 2019-08-13)
OS: Manjaro/Arch

Getting this massive error at every block import during sync. The node still syncs, but gives me errors like the following:

```
Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /home/XXX/.cargo/git/checkouts/substrate-7e08433d4c370a21/46b63af/srml/executive/src/lib.rs:319

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

Hash: given=9b81d1703ba3a64e75673456000d8f19ad57d35c9db319f2e12f4e0e74e80bd0, expected=dda19ec30eea5fb73b673e3bdcc2562c9bb3c5d681cbfffb2980881a3b623d79

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h8ef9805321ae0167 (0x55df028720fe)
   1: std::panicking::rust_panic_with_hook::h185be11cf56dd6c5 (0x55df029a432c)
             at src/libstd/panicking.rs:481
   2: std::panicking::begin_panic::h0af98245bc73df8a (0x55df024d63e5)
   3: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block::h6d824eb5319dc77e (0x55df024d2d13)
   4: polkadot_runtime::api::dispatch::ha22fce10fe3bf38e (0x55df0242021f)
   5: std::panicking::try::do_call::h5dae2bc32587baa0 (0x55df01e441f2)
   6: __rust_maybe_catch_panic (0x55df029ad38a)
             at src/libpanic_unwind/lib.rs:80
   7: substrate_executor::native_executor::safe_call::ha225fc57928c3f3c (0x55df01e44098)
   8: std::thread::local::LocalKey<T>::with::h980c81e745cd262a (0x55df01e43bf1)
   9: <polkadot_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h81ad77dcf75ebf88 (0x55df01e437fd)
  10: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::h627d5ecb1a4b1e1e (0x55df01bae789)
  11: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h8e3a02e1eedd541f (0x55df01ceff0d)
  12: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_call_with_native_else_wasm_strategy::hec5b8a4ba71b71b0 (0x55df01d51632)
  13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h9f5267640c973bce (0x55df01d2d3d1)
  14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h96543cf0330b4240 (0x55df01bddea0)
  15: substrate_client::client::Client<B,E,Block,RA>::lock_import_and_run::{{closure}}::h8d68f39cf9002ec2 (0x55df01903d8c)
  16: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,PRA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hc7084307945c1901 (0x55df0190ea1d)
  17: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h299ce6c54a0c4a5a (0x55df01de6baf)
  18: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::he3245db3034e6414 (0x55df01a58ffb)
  19: futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll::h2791526c8b5fe9e8 (0x55df016fbf0b)
  20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h64b9d974c37f1858 (0x55df01a56b10)
  21: futures_executor::thread_pool::PoolState::work::h4aeac3da1b561c3e (0x55df027fc186)
  22: std::sys_common::backtrace::__rust_begin_short_backtrace::ha0f3512a812668bc (0x55df027fb244)
  23: std::panicking::try::do_call::hd9f86864662bc9e0 (0x55df027f9b15)
  24: __rust_maybe_catch_panic (0x55df029ad38a)
             at src/libpanic_unwind/lib.rs:80
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}::h595475e1b00c5583 (0x55df027f9baa)
  26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h007a3b027456a6a9 (0x55df0299221f)
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/liballoc/boxed.rs:922
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h3b5231ca6bdd7b3c (0x55df029ac6d0)
             at /rustc/9eae1fc0ea9b00341b8fe191582c4decb5cb86a3/src/liballoc/boxed.rs:922
      std::sys_common::thread::start_thread::hb32caa9dd2aeb43f
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::ha037b97c352bfa07
             at src/libstd/sys/unix/thread.rs:79
  28: start_thread (0x7f83daaee57f)
  29: __clone (0x7f83daa020e3)
  30: <unknown> (0x0)
```

**Comment by phillux** [comment]
Running Kusama on v0.6.0 was the issue. Rolled back to branch v0.5
