### ISSUE TITLE
ApplySnapshotFailed: Stack backtrace while syncing chainstate while running as a validator on Kusama

### ISSUE THREAD

**Issue by chrishobcroft** [paritytech/polkadot#421]
I was running `./target/release/polkadot --validator --name "name on telemetry"` and syncing chainstate, when this happened:

```
2019-09-07 13:12:55 Syncing 19.4 bps, target=#215901 (30 peers), best: #56673 (0xc5ec…649a), finalized #55093 (0xb0af…fb9d), ⬇ 26.7kiB/s ⬆ 15.0kiB/s

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h82cae3535dcc52cb (0x556fb270a1c0)
   1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x556fb28488a9)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::hc0f142c930c846fc (0x556fb2848342)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x556fb2848226)
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h2daf88b2616ca2b2 (0x556fb286a0dd)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::hf856130588d15816 (0x556fb1a5f01e)
   6: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::heef7ff72239b90f2 (0x556fb18b9d68)
   7: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h40e0fef5aad580f3 (0x556fb19e1ad0)
   8: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h260d5fc78a88d573 (0x556fb19ffe30)
   9: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::hc9d14c9a3c6e6a24 (0x556fb18d7dab)
  10: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::hbf93113da3de111a (0x556fb15379aa)
  11: <polkadot_runtime::RuntimeApiImpl<RuntimeApiImplCall> as substrate_client::runtime_api::Core<<polkadot_runtime::Runtime as sr_primitives::traits::GetNodeBlockType>::NodeBlock>>::Core_initialize_block_runtime_api_impl::hb7bdde40663ba0bc (0x556fb1492379)
  12: substrate_client::runtime_api::Core::initialize_block::hb74ada721fa5e557 (0x556fb1457817)
  13: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::h180d95583b4cd831 (0x556fb18c7eec)
  14: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h4dea38609a1d170a (0x556fb15335ca)
  15: substrate_finality_grandpa_primitives::runtime_decl_for_GrandpaApi::grandpa_forced_change_call_api_at::h128a6f6bad74f660 (0x556fb168563c)
  16: substrate_finality_grandpa_primitives::GrandpaApi::grandpa_forced_change::hf2e70e3f90edd85c (0x556fb149bfa6)
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,PRA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h2d35b5d0e7705ebc (0x556fb155096f)
  18: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hc383e7d0219380a2 (0x556fb1ac249d)
  19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h15b1bf4308561aed (0x556fb16b1c03)
  20: futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll::hdccb2aaee4481bf3 (0x556fb14369f6)
  21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h226e8f2f31f1b7ca (0x556fb16b2088)
  22: futures_executor::thread_pool::PoolState::work::hd688b0071aa4ee53 (0x556fb2690886)
  23: std::sys_common::backtrace::__rust_begin_short_backtrace::h5fc8c451d41996f4 (0x556fb26927d4)
  24: std::panicking::try::do_call::hf88b2158e06ba665 (0x556fb268dbb5)
  25: __rust_maybe_catch_panic (0x556fb28517ca)
             at src/libpanic_unwind/lib.rs:82
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}::h55ccedf7c03b1dfd (0x556fb268f81a)
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x556fb283664f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x556fb2850b50)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  29: start_thread (0x7f7bd2d4f6db)
  30: __clone (0x7f7bd286088f)
  31: <unknown> (0x0)

Thread 'import-queue-worker-0' panicked at 'applying the snapshot can only fail if the passed instance is different
                        from the one that was used for creation of the snapshot;
                        we use the snapshot that is directly associated with the instance;
                        thus the snapshot was created using the instance;
                        qed: ApplySnapshotFailed', src/libcore/result.rs:999

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

```

**Comment by chrishobcroft** [comment]
Happened again at 2019-09-07 13:55:20

**Comment by chrishobcroft** [comment]
And again

**Comment by gregzaitsev** [comment]
And again :)

**Comment by bkchr** [comment]
Hey, if one of you have more insights, could you please comment here: https://github.com/paritytech/substrate/issues/3780

(I will close this, as this is basically a duplicate and belongs to the Substrate repo anyway)

Ty!
