### ISSUE TITLE
import-queue-worker-0 panicked at applying the snapshot

### ISSUE THREAD

**Issue by gregzaitsev** [paritytech/polkadot#427]
2019-09-10 14:00:19 Syncing 11.1 bps, target=#259339 (25 peers), best: #259009 (0x81bd…9362), finalized #258940 (0xfec6…4554), ⬇ 6.1kiB/s ⬆ 6.0kiB/s
2019-09-10 14:00:20 Syncing 11.1 bps, target=#259339 (25 peers), best: #259021 (0xb3b3…7644), finalized #258941 (0xe70d…6cec), ⬇ 10.6kiB/s ⬆ 6.0kiB/s
2019-09-10 14:00:25 Syncing 10.6 bps, target=#259341 (25 peers), best: #259074 (0x9bb6…a482), finalized #259009 (0x81bd…9362), ⬇ 17.0kiB/s ⬆ 22.1kiB/s
2019-09-10 14:00:30 Syncing 13.4 bps, target=#259342 (25 peers), best: #259141 (0x0f5b…3c81), finalized #259124 (0x22c4…e11c), ⬇ 15.4kiB/s ⬆ 6.9kiB/s
2019-09-10 14:00:31 cannot create a runtime: Instantiation(Runtime)
2019-09-10 14:00:31 Failed to fetch runtime: InvalidCode("Instantiation(Runtime)")
2019-09-10 14:00:31 Unable to start parachain validation on top of 0x1207495766b846d709eb719a492e1b22888f787cee4f46c38662b4155deb2f48: On-chain runtime does not specify version
2019-09-10 14:00:31 cannot create a runtime: Instantiation(Runtime)
2019-09-10 14:00:31 Failed to fetch runtime: InvalidCode("Instantiation(Runtime)")
2019-09-10 14:00:32 Error running offchain workers at Number(259170): VersionInvalid
2019-09-10 14:00:32 Imported #259170 (0x1207…2f48)

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h82cae3535dcc52cb (0x5622b9104a50)
   1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x5622b9240199)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::hc0f142c930c846fc (0x5622b923fc32)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x5622b923fb16)
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h2daf88b2616ca2b2 (0x5622b92619cd)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::he633b5e36b624218 (0x5622b84415fe)
   6: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::h386b4dd0f3cdde70 (0x5622b83a643c)
   7: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h81ff6aec886e1da2 (0x5622b84f6fe0)
   8: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h1ad7c4c76a606e6a (0x5622b8509412)
   9: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::hffb5021b6b64b883 (0x5622b83f17ab)
  10: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h0194d1157b7f28d0 (0x5622b81b20f0)
  11: substrate_client::runtime_api::runtime_decl_for_Core::initialize_block_call_api_at::ha6d4eb7beadbebc6 (0x5622b82ccf05)
  12: substrate_client::runtime_api::Core::initialize_block::h5cb1d1aac79dd77b (0x5622b7f7501a)
  13: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::hcb34288f5cf6ae5a (0x5622b83e9834)
  14: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h775e15d1c21447c1 (0x5622b81b4497)
  15: substrate_consensus_babe_primitives::runtime_decl_for_BabeApi::epoch_call_api_at::hf47a9bfcc1bf3f53 (0x5622b8271649)
  16: substrate_consensus_babe_primitives::BabeApi::epoch::h05bf941c12cfcaf9 (0x5622b7faebae)
  17: substrate_consensus_babe::epoch_from_runtime::h13eec199cfe99ecd (0x5622b85ea9ba)
  18: <substrate_consensus_babe::BabeVerifier<B,E,Block,RA,PRA,T> as substrate_consensus_common::import_queue::Verifier<Block>>::verify::h04a0f8e2a4d62b48 (0x5622b85c63e2)
  19: substrate_consensus_common::import_queue::import_single_block::h48473fca4a0b74dc (0x5622b80669b9)
  20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::hf26444ed7a9b2ac7 (0x5622b821e802)
  21: futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll::h1c083e90e32318c9 (0x5622b7f59d3b)
  22: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::hb39785e92c80ef1e (0x5622b821dc08)
  23: futures_executor::thread_pool::PoolState::work::hd688b0071aa4ee53 (0x5622b908c646)
  24: std::sys_common::backtrace::__rust_begin_short_backtrace::h5fc8c451d41996f4 (0x5622b908e594)
  25: std::panicking::try::do_call::hf88b2158e06ba665 (0x5622b9089975)
  26: __rust_maybe_catch_panic (0x5622b92490ba)
             at src/libpanic_unwind/lib.rs:82
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}::h55ccedf7c03b1dfd (0x5622b908b5da)
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x5622b922e27f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  29: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x5622b9248440)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  30: start_thread (0x7f471fead4a4)
  31: __clone (0x7f471f9d8d0f)
  32: <unknown> (0x0)

Thread 'import-queue-worker-0' panicked at 'applying the snapshot can only fail if the passed instance is different
			from the one that was used for creation of the snapshot;
			we use the snapshot that is directly associated with the instance;
			thus the snapshot was created using the instance;
			qed: ApplySnapshotFailed', src/libcore/result.rs:999

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

**Comment by gregzaitsev** [comment]
Duplicate
