### ISSUE TITLE
Panic while syncing

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#433]
```
2019-09-11 16:37:56 Syncing  8.6 bps, target=#275215 (44 peers), best: #249608 (0x2420…c5af), finalized #242438 (0xd47b…9aab), ⬇ 31.0kiB/s ⬆ 18.8kiB/s

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h82cae3535dcc52cb (0x560d1ff401c0)
   1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x560d2007e8a9)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::hc0f142c930c846fc (0x560d2007e342)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x560d2007e226)
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h2daf88b2616ca2b2 (0x560d200a00dd)
             at src/libcore/panicking.rs:85
   5: core::option::expect_failed::h4b77ebe6e62ec3a1 (0x560d200a0147)
             at src/libcore/option.rs:1034
   6: futures_channel::mpsc::Receiver<T>::next_message::h404aa95477bcb813 (0x560d1efe7ad4)
   7: <futures_channel::mpsc::UnboundedReceiver<T> as futures_core::stream::Stream>::poll_next::hf6848a4bcd611ef7 (0x560d1f09554f)
   8: substrate_consensus_common::import_queue::buffered_link::BufferedLinkReceiver<B>::poll_actions::hf8ca5ee0414628ac (0x560d1ed9a573)
   9: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::h1b1ff0fd444d8ca8 (0x560d1f412a48)
  10: <substrate_network::service::NetworkWorker<B,S,H> as futures::future::Future>::poll::hc7414aa26f434e8d (0x560d1f099724)
  11: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll::h6a6037d6ae9c9f2c (0x560d1f083ce3)
  12: <futures::future::select::Select<A,B> as futures::future::Future>::poll::h2afb7324a6f537a5 (0x560d1f08a2f9)
  13: futures::future::chain::Chain<A,B,C>::poll::hc6991cdf6b6697a0 (0x560d1f3ec897)
  14: futures::task_impl::std::set::he0bb14a5ff759b91 (0x560d1fd85d72)
  15: std::panicking::try::do_call::hb2635057988b3a79 (0x560d1fd855e2)
  16: __rust_maybe_catch_panic (0x560d200877ca)
             at src/libpanic_unwind/lib.rs:82
  17: tokio_threadpool::task::Task::run::hb2b8bdad56fe2c2e (0x560d1fd836f9)
  18: tokio_threadpool::worker::Worker::run_task::he55082c6755b820e (0x560d1fd7cf49)
  19: tokio_threadpool::worker::Worker::run::ha7cb5223fa924fae (0x560d1fd7c6c7)
  20: std::thread::local::LocalKey<T>::with::ha3a56cc3c56dc813 (0x560d1fd62d1f)
  21: std::thread::local::LocalKey<T>::with::hd135e2ccab1169a1 (0x560d1fd62e58)
  22: tokio_reactor::with_default::h162c3a4462962eb6 (0x560d1fd62b0f)
  23: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h42d09999b4641b8c (0x560d1fd64fff)
  24: std::thread::local::LocalKey<T>::with::hc2acd9b3893e5800 (0x560d1fd85116)
  25: std::thread::local::LocalKey<T>::with::h9836ff45121f2560 (0x560d1fd84f1f)
  26: std::sys_common::backtrace::__rust_begin_short_backtrace::h6c0fcb1f481a5c17 (0x560d1fd7ec31)
  27: std::panicking::try::do_call::h25e91e5569d2531c (0x560d1fd8553c)
  28: __rust_maybe_catch_panic (0x560d200877ca)
             at src/libpanic_unwind/lib.rs:82
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}::h641c8840fc3a9399 (0x560d1fd80910)
  30: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x560d2006c64f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  31: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x560d20086b50)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  32: start_thread (0x7f61ab7eb6db)
  33: __clone (0x7f61ab2fc88f)
  34: <unknown> (0x0)

Thread 'tokio-runtime-worker-0' panicked at 'Receiver::next_message called after `None`', src/libcore/option.rs:1034
```

version 0.5.1-60155e89-x86_64-linux-gnu

**Comment by rphmeier** [comment]
outdated
