### ISSUE TITLE
Thread 'import-queue-worker-0' panicked at 'Externalities not allowed to fail within runtime: 

### ISSUE THREAD

**Issue by iammelea** [paritytech/polkadot#436]
Hello
here
```
2019-09-17 07:05:29 Parity Polkadot
2019-09-17 07:05:29   version 0.5.1-645baf1-x86_64-linux-gnu
2019-09-17 07:05:29   by Parity Team <admin@parity.io>, 2017-2019
2019-09-17 07:05:29 Chain specification: Kusama CC1
```
Sentry stop working. This was the last logs. this is one full-node and Is working in VPN (wireguard) .
Node A Private VPN to Node B and Node C
Node B is VPN and open
node C is VPN too lets said is this, start like his

```polkadot --name melea-◮👁◭-W3F-I-Trust --listen-addr=/ip4/10.0.0.2/tcp/30333```

Then meanwhile was running this=

```
2019-09-16 22:42:36 Imported #349205 (0x3bcb…1caf)
2019-09-16 22:42:37 Reorg from #349205,0x3bcb…1caf to #349205,0x465e…0ce7, common ancestor #349204,0x24a8…2521
2019-09-16 22:42:37 Imported #349205 (0x465e…0ce7)
2019-09-16 22:42:40 Idle (24 peers), best: #349205 (0x465e…0ce7), finalized #349199 (0xc87a…3bbd), ⬇ 26.2kiB/s ⬆ 15.4kiB/s
2019-09-16 22:42:42 Imported #349206 (0x73d4…9fe8)
2019-09-16 22:42:44 Imported #349206 (0x747a…c669)
2019-09-16 22:42:46 Idle (24 peers), best: #349206 (0x73d4…9fe8), finalized #349199 (0xc87a…3bbd), ⬇ 8.9kiB/s ⬆ 8.7kiB/s
2019-09-16 22:42:49 Imported #349207 (0xfcca…5287)
2019-09-16 22:42:50 Idle (24 peers), best: #349207 (0xfcca…5287), finalized #349199 (0xc87a…3bbd), ⬇ 9.8kiB/s ⬆ 7.5kiB/s
2019-09-16 22:42:50 Imported #349201 (0xfb34…88e2)

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h74fc0ce542015ca1 (0x55b8a1cf8650)
   1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x55b8a1e36df9)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::hc0f142c930c846fc (0x55b8a1e36892)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x55b8a1e36776)
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h2daf88b2616ca2b2 (0x55b8a1e5862d)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h6f9c7c679d86d946 (0x55b8a10695fe)
   6: <substrate_state_machine::ext::Ext<H,N,B,T,O> as substrate_state_machine::Externalities<H>>::storage::h3ee68f3930c2d043 (0x55b8a0d3c550)
   7: substrate_executor::wasm_runtimes_cache::RuntimesCache::fetch_runtime::h3f8ed3f2c2d3e041 (0x55b8a1218814)
   8: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::runtime_version::h89d832b0f676a2da (0x55b8a0efc66e)
   9: substrate_finality_grandpa_primitives::runtime_decl_for_GrandpaApi::grandpa_forced_change_call_api_at::h44bf58a58d4a8665 (0x55b8a0b92612)
  10: substrate_finality_grandpa_primitives::GrandpaApi::grandpa_forced_change::h1633a6691b743578 (0x55b8a0abeb0d)
  11: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,PRA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h368b676d1abaa22b (0x55b8a0b5f6f6)
  12: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::he87d7eca13f79067 (0x55b8a10dcea4)
  13: substrate_consensus_common::import_queue::import_single_block::h7917ae91be4c6266 (0x55b8a0b74f5f)
  14: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h8fd12c27dfd0d8d7 (0x55b8a0d277f2)
  15: futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll::h9af4b73b8a20ac57 (0x55b8a0a629f6)
  16: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::hb13c9bbf1c7aa6b5 (0x55b8a0d27cf8)
  17: futures_executor::thread_pool::PoolState::work::h128efd25449415f6 (0x55b8a1c7ef16)
  18: std::sys_common::backtrace::__rust_begin_short_backtrace::h009b6dccb9e1ba20 (0x55b8a1c80e64)
  19: std::panicking::try::do_call::h944d2744c24a8faf (0x55b8a1c7c245)
  20: __rust_maybe_catch_panic (0x55b8a1e3fd1a)
             at src/libpanic_unwind/lib.rs:82
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}::h1b530351a40c2059 (0x55b8a1c7deaa)
  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x55b8a1e24b9f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  23: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x55b8a1e3f0a0)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  24: start_thread (0x7fb020b696db)
  25: __clone (0x7fb02067a88f)
  26: <unknown> (0x0)

Thread 'import-queue-worker-0' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x085e1968fff74bcc139be8e5f357a1e74f3f0defa6e990543e3c85caacd88f83"', src/libcore/result.rs:999

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

```
then start the node again like this

```
~/.local/share/polkadot/chains/ksma$ polkadot --name melea-◮👁◭-W3F-I-Trust --listen-addr=/ip4/10.0.0.2/tcp/30333
2019-09-17 07:05:29 Parity Polkadot
2019-09-17 07:05:29   version 0.5.1-645baf1-x86_64-linux-gnu
2019-09-17 07:05:29   by Parity Team <admin@parity.io>, 2017-2019
2019-09-17 07:05:29 Chain specification: Kusama CC1
2019-09-17 07:05:29 Node name: melea-◮👁◭-W3F-I-Trust
2019-09-17 07:05:29 Roles: FULL
2019-09-17 07:05:33 Highest known block at #349201
2019-09-17 07:05:33 Local node identity is: QmSmt
2019-09-17 07:05:34 Discovered new external address for our node: /ip4/10.0.1.252/tcp/30333/p2p/QmSmti75b7R
2019-09-17 07:05:34 Discovered new external address for our node: /ip4/REAL-IP-HERE/tcp/30333/p2p/QmSmti7
```

**Comment by bkchr** [comment]
This should now be fixed in `0.6.7`.
