### ISSUE TITLE
Assertion failure in sync

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#440]
```
====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h065718a031318422 (0x5601f8b84a80)
   1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x5601f8cd02a9)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::hc0f142c930c846fc (0x5601f8ccfd42)
             at src/libstd/panicking.rs:384
   3: std::panicking::begin_panic_fmt::ha6acf0ffd6d7f80d (0x5601f8ccfc8f)
             at src/libstd/panicking.rs:339
   4: substrate_network::protocol::sync::ChainSync<B>::on_block_justification::h883478e2708d5ce6 (0x5601f78b3cdc)
   5: substrate_network::protocol::Protocol<B,S,H>::on_custom_message::h314f1fd8660ebeb7 (0x5601f805efb5)
   6: <substrate_network::protocol::Protocol<B,S,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll::hc648743124b5bff1 (0x5601f804bb7c)
   7: <substrate_network::behaviour::Behaviour<B,S,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll::h091b13c488204d52 (0x5601f7eed1d8)
   8: <libp2p_swarm::ExpandedSwarm<TTransport,TBehaviour,TInEvent,TOutEvent,THandler,THandlerErr,TConnInfo> as futures::stream::Stream>::poll::h73e9ee6bb71ec1e9 (0x5601f7faf5ad)
   9: <substrate_network::service::NetworkWorker<B,S,H> as futures::future::Future>::poll::h6e2b97f3fc75bc46 (0x5601f7cbebe8)
  10: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll::h701e07235767d1e0 (0x5601f7ca7003)
  11: <futures::future::select::Select<A,B> as futures::future::Future>::poll::h50fdc272c20e32b0 (0x5601f7cb0e79)
  12: futures::future::chain::Chain<A,B,C>::poll::hbfff990c47dbbe21 (0x5601f8011517)
  13: futures::task_impl::std::set::hf848796b4e6c86ed (0x5601f89bf6b2)
  14: std::panicking::try::do_call::hc199bb0b3e57a2e9 (0x5601f89beeb2)
  15: __rust_maybe_catch_panic (0x5601f8cd91ca)
             at src/libpanic_unwind/lib.rs:82
  16: tokio_threadpool::task::Task::run::h44801e46cd39f2e9 (0x5601f89bc9d3)
  17: tokio_threadpool::worker::Worker::run_task::hac4d49dbafca38bf (0x5601f89b4f64)
  18: tokio_threadpool::worker::Worker::run::hb2708f9b6b65935f (0x5601f89b44a1)
  19: std::thread::local::LocalKey<T>::with::h0faa0a9a15934e76 (0x5601f899a34f)
  20: std::thread::local::LocalKey<T>::with::h99d5e2b3290748ec (0x5601f899a488)
  21: tokio_reactor::with_default::he541d7723094fc98 (0x5601f899a13f)
  22: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h5bfae82686a39045 (0x5601f899f63f)
  23: std::thread::local::LocalKey<T>::with::h8034dde0fcdb6455 (0x5601f89be736)
  24: std::thread::local::LocalKey<T>::with::hdf35c23edd514c63 (0x5601f89bea8f)
  25: std::sys_common::backtrace::__rust_begin_short_backtrace::hc4cd5392287bfec5 (0x5601f89b708d)
  26: std::panicking::try::do_call::h03ef254f3a95d0a0 (0x5601f89bee0c)
  27: __rust_maybe_catch_panic (0x5601f8cd91ca)
             at src/libpanic_unwind/lib.rs:82
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}::h98f4d8dd769e83df (0x5601f89b9420)
  29: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x5601f8cbe04f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  30: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x5601f8cd8550)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  31: start_thread (0x7f8ede5c16db)
  32: __clone (0x7f8ede0d288f)
  33: <unknown> (0x0)

Thread 'tokio-runtime-worker-0' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/3ba0f2a/core/network/src/protocol/sync.rs:662

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new
```

Here is the log: [truncated_log.txt.gz](https://github.com/paritytech/polkadot/files/3639055/truncated_log.txt.gz)

git-blame points out that @twittner might know something about this.

**Comment by tomaka** [comment]
That seems to be fixed!
