### ISSUE TITLE
Thread 'import-queue-worker-0' panicked at 'applying the snapshot can only fail if the passed instance is different

### ISSUE THREAD

**Issue by UbikCapital** [paritytech/polkadot#447]
27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x55715114364f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x55715115db50)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  29: start_thread (0x7f076624e6db)
  30: __clone (0x7f0765d5f88f)
  31: <unknown> (0x0)

Thread 'import-queue-worker-0' panicked at 'applying the snapshot can only fail
if the passed instance is different
                        from the one that was used for creation of the snapshot;
                        we use the snapshot that is directly associated with the instance;
                        thus the snapshot was created using the instance;
                        qed: ApplySnapshotFailed', src/libcore/result.rs:999

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

**Comment by foodaka** [comment]
I also had this issue or something similar

```
stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h2f2c56a8acc50455 (0x5599ba65e870)
   1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x5599ba79d449)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::hc0f142c930c846fc (0x5599ba79cee2)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x5599ba79cdc6)
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h2daf88b2616ca2b2 (0x5599ba7bec7d)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h9022d890227ee50b (0x5599b99ab47e)
   6: <substrate_state_machine::ext::Ext<H,N,B,T,O> as substrate_primitives::traits::Externalities<H>>::storage::h46d1e806401f4753 (0x5599b9963933)
   7: std::thread::local::LocalKey<T>::with::h8aef0a1ac0f368d2 (0x5599ba638d3e)
   8: sr_io::storage::hd7f5003779f93a45 (0x5599ba6363a5)
   9: std::panicking::try::do_call::h4ad02352ad61ed42 (0x5599ba3511c1)
  10: __rust_maybe_catch_panic (0x5599ba7a636a)
             at src/libpanic_unwind/lib.rs:82
  11: <<substrate_executor::wasm_executor::SubstrateExternals as substrate_wasm_interface::HostFunctions>::functions::ext_get_allocated_storage as substrate_wasm_interface::Function>::execute::h683d1a5f3be4bd0d (0x5599ba3219b1)
  12: <substrate_executor::wasm_executor::FunctionExecutor as wasmi::host::Externals>::invoke_index::h3fa4f141f2697de1 (0x5599ba31bb8f)
  13: wasmi::func::FuncInstance::invoke::hdde5400695de7ca8 (0x5599b95772cb)
  14: wasmi::runner::Interpreter::start_execution::hd7a732321cc9ba02 (0x5599b94e4f4a)
  15: wasmi::func::FuncInstance::invoke::hdde5400695de7ca8 (0x5599b957735d)
  16: std::thread::local::LocalKey<T>::with::h53ec9be26384f0a3 (0x5599b9610a36)
  17: substrate_executor::wasm_executor::WasmExecutor::call_in_wasm_module::h532545bf98712159 (0x5599b9438996)
  18: std::thread::local::LocalKey<T>::with::h1658768f4a2ce19a (0x5599b960b24f)
  19: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_aux::haa5b688f570cab1b (0x5599b97f55b1)
  20: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_using_consensus_failure_handler::hd9d70a59a3aed9f5 (0x5599b98496bd)
  21: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::h44ded498740007d5 (0x5599b9720d7d)
  22: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h4bfeb7b516317e03 (0x5599b9ac3cb9)
  23: substrate_client::block_builder::api::runtime_decl_for_BlockBuilder::check_inherents_call_api_at::ha3841b01c2367a10 (0x5599b95c4a00)
  24: substrate_client::block_builder::api::BlockBuilder::check_inherents::hfe7d237d60621748 (0x5599b9520d49)
  25: <substrate_consensus_babe::BabeVerifier<B,E,Block,RA,PRA,T> as substrate_consensus_common::import_queue::Verifier<Block>>::verify::h3fc445f6b07e15ed (0x5599b98bb8f8)
  26: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::hb9a71a7b06fa96fb (0x5599b9b375ac)
  27: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll::h4c8b75b20aa9ba6c (0x5599b9595dc6)
  28: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::he5c885e403c9bd38 (0x5599b9b38568)
  29: futures_executor::thread_pool::PoolState::work::hd688b0071aa4ee53 (0x5599ba5e34c6)
  30: std::sys_common::backtrace::__rust_begin_short_backtrace::h5fc8c451d41996f4 (0x5599ba5e5414)
  31: std::panicking::try::do_call::hf88b2158e06ba665 (0x5599ba5e07f5)
  32: __rust_maybe_catch_panic (0x5599ba7a636a)
             at src/libpanic_unwind/lib.rs:82
  33: core::ops::function::FnOnce::call_once{{vtable.shim}}::h55ccedf7c03b1dfd (0x5599ba5e245a)
  34: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x5599ba78b1ef)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  35: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x5599ba7a56f0)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  36: start_thread (0x7f1fbf15b6db)
  37: __clone (0x7f1fbec6c88f)
  38: <unknown> (0x0)


Thread 'import-queue-worker-0' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x1d559ad26eb7f25d01bab2d4b1176139541abbed30924f269fafc94bffa3230d"', src/libcore/result.rs:999

This is a bug. Please report it at:

```

**Comment by gavofyork** [comment]
Should be fixed now.
