### ISSUE TITLE
When running polkadot with westend testnet, it has crash. 

### ISSUE THREAD

**Issue by johndoe0x** [paritytech/polkadot#4587]
- It would help if you submit info about the system you are running, e.g.: operating system, kernel version, amount of available memory and swap, etc.
 - ENV : 
 - Macbook air M1 8GB ram, 256 GB storage 
 - OS : Monterey ver 12.0.1
 - Rustup version : rustup 1.24.3 (ce5817a94 2021-05-31)
 - Rustc version : rustc 1.57.0 (f1edd0429 2021-11-29)
 - Polkadot ver : polkadot 0.9.14-80dfb926f4-aarch64-macos
 
- Logs could be very helpful. If possible, submit the whole log. Please format it as ```code blocks```.
```
2021-12-22 16:13:25.798  INFO main sc_cli::runner: Parity Polkadot    
2021-12-22 16:13:25.799  INFO main sc_cli::runner: ✌️  version 0.9.14-80dfb926f4-aarch64-macos    
2021-12-22 16:13:25.799  INFO main sc_cli::runner: ❤️  by Parity Technologies <admin@parity.io>, 2017-2021    
2021-12-22 16:13:25.799  INFO main sc_cli::runner: 📋 Chain specification: Westend    
2021-12-22 16:13:25.799  INFO main sc_cli::runner: 🏷 Node name: johnishere    
2021-12-22 16:13:25.799  INFO main sc_cli::runner: 👤 Role: FULL    
2021-12-22 16:13:25.799  INFO main sc_cli::runner: 💾 Database: RocksDb at /Users/john/parity/westend/chains/westend2/db/full    
2021-12-22 16:13:25.799  INFO main sc_cli::runner: ⛓  Native runtime: westend-9140 (parity-westend-0.tx8.au2)    
2021-12-22 16:13:27.041  INFO main sub-libp2p: 🏷 Local node identity is: 12D3KooWG5LbnNuA5sbcNRWmWq3qQLGcJeudJowEvnQp1BuCKZMf    
2021-12-22 16:13:27.041  WARN main sync: Can't use fast sync mode with a partially synced database. Reverting to full sync mode.    
2021-12-22 16:13:27.051  INFO main sc_service::builder: 📦 Highest known block at #8783248    
2021-12-22 16:13:27.053  INFO main parity_ws: Listening for new connections on 127.0.0.1:9944.    
2021-12-22 16:13:28.334  INFO tokio-runtime-worker sub-libp2p: 🔍 Discovered new external address for our node: /ip4/125.130.243.205/tcp/30333/ws/p2p/12D3KooWG5LbnNuA5sbcNRWmWq3qQLGcJeudJowEvnQp1BuCKZMf    
2021-12-22 16:13:32.056  INFO tokio-runtime-worker substrate: ⚙️  Syncing, target=#8783391 (4 peers), best: #8783248 (0xde17…72cb), finalized #8783245 (0x3898…548d), ⬇ 11.5kiB/s ⬆ 8.8kiB/s    
2021-12-22 16:13:36.471  INFO tokio-runtime-worker substrate: ✨ Imported #8783392 (0xd681…136e)    
2021-12-22 16:13:37.059  INFO tokio-runtime-worker substrate: 💤 Idle (4 peers), best: #8783392 (0xd681…136e), finalized #8783361 (0xb2f8…4947), ⬇ 93.3kiB/s ⬆ 5.0kiB/s    
2021-12-22 16:13:42.066  INFO tokio-runtime-worker substrate: 💤 Idle (4 peers), best: #8783392 (0xd681…136e), finalized #8783389 (0x6593…9272), ⬇ 6.5kiB/s ⬆ 3.6kiB/s    
2021-12-22 16:13:43.600  INFO tokio-runtime-worker substrate: ✨ Imported #8783393 (0x2cf5…66e4)    
2021-12-22 16:13:47.070  INFO tokio-runtime-worker substrate: 💤 Idle (4 peers), best: #8783393 (0x2cf5…66e4), finalized #8783390 (0x8797…f178), ⬇ 12.4kiB/s ⬆ 7.6kiB/s    
2021-12-22 16:13:48.660  INFO tokio-runtime-worker substrate: ✨ Imported #8783394 (0xae71…681b)    
2021-12-22 16:13:52.075  INFO tokio-runtime-worker substrate: 💤 Idle (5 peers), best: #8783394 (0xae71…681b), finalized #8783390 (0x8797…f178), ⬇ 7.6kiB/s ⬆ 4.4kiB/s    
2021-12-22 16:13:54.389  INFO tokio-runtime-worker substrate: ✨ Imported #8783395 (0x9a64…48e2)    
2021-12-22 16:13:57.076  INFO tokio-runtime-worker substrate: 💤 Idle (7 peers), best: #8783395 (0x9a64…48e2), finalized #8783393 (0x2cf5…66e4), ⬇ 13.6kiB/s ⬆ 5.7kiB/s    
2021-12-22 16:14:00.460  INFO tokio-runtime-worker substrate: ✨ Imported #8783396 (0x5845…54a6)    
2021-12-22 16:14:02.086  INFO tokio-runtime-worker substrate: 💤 Idle (6 peers), best: #8783396 (0x5845…54a6), finalized #8783393 (0x2cf5…66e4), ⬇ 10.9kiB/s ⬆ 5.9kiB/s    
2021-12-22 16:14:06.384  INFO tokio-runtime-worker substrate: ✨ Imported #8783397 (0xbe3e…45ea)    
2021-12-22 16:14:07.089  INFO tokio-runtime-worker substrate: 💤 Idle (7 peers), best: #8783397 (0xbe3e…45ea), finalized #8783393 (0x2cf5…66e4), ⬇ 10.0kiB/s ⬆ 4.3kiB/s    

====================

Version: 0.9.14-80dfb926f4-aarch64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
   6: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   7: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   8: core::panicking::panic_display
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:64:5
   9: core::option::expect_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:1638:5
  10: sc_state_db::noncanonical::discard_descendants
  11: sc_state_db::noncanonical::discard_descendants
  12: sc_state_db::noncanonical::discard_descendants
  13: sc_state_db::noncanonical::NonCanonicalOverlay<BlockHash,Key>::apply_pending
  14: sc_state_db::StateDb<BlockHash,Key>::apply_pending
  15: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::commit_operation
  16: <sc_service::client::client::Client<B,E,Block,RA> as sc_client_api::backend::LockImportRun<Block,B>>::lock_import_and_run
  17: sc_finality_grandpa::environment::finalize_block
  18: <sc_finality_grandpa::environment::Environment<B,Block,C,N,SC,VR> as finality_grandpa::voter::Environment<<Block as sp_runtime::traits::Block>::Hash,<<Block as sp_runtime::traits::Block>::Header as sp_runtime::traits::Header>::Number>>::finalize_block
  19: <finality_grandpa::voter::Voter<H,N,E,GlobalIn,GlobalOut> as core::future::future::Future>::poll
  20: <sc_finality_grandpa::VoterWork<B,Block,C,N,SC,VR> as core::future::future::Future>::poll
  21: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  22: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  23: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  24: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  25: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: std::thread::local::LocalKey<T>::with
  28: tokio::park::thread::CachedParkThread::block_on
  29: tokio::runtime::handle::Handle::block_on
  30: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  31: tokio::runtime::task::harness::Harness<T,S>::poll
  32: tokio::runtime::blocking::pool::Inner::run
  33: std::sys_common::backtrace::__rust_begin_short_backtrace
  34: core::ops::function::FnOnce::call_once{{vtable.shim}}
  35: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  36: _pthread_from_mach_thread_np


Thread 'tokio-runtime-worker' panicked at 'there is a parent entry for each entry in levels; qed', /Users/john/.cargo/git/checkouts/substrate-7e08433d4c370a21/de6033a/client/state-db/src/noncanonical.rs:150

```

```
2021-12-22 16:51:43.433  INFO tokio-runtime-worker substrate: 💤 Idle (7 peers), best: #8783773 (0x0581…49f5), finalized #8783770 (0x6c8e…266c), ⬇ 17.2kiB/s ⬆ 8.0kiB/s    
2021-12-22 16:51:48.434  INFO tokio-runtime-worker substrate: 💤 Idle (8 peers), best: #8783773 (0x0581…49f5), finalized #8783771 (0x760f…49f7), ⬇ 10.7kiB/s ⬆ 4.6kiB/s    
2021-12-22 16:51:48.438  INFO tokio-runtime-worker substrate: ✨ Imported #8783774 (0x3e58…6a32)    

====================

Version: 0.9.14-80dfb926f4-aarch64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
   6: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   7: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   8: core::panicking::panic_display
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:64:5
   9: core::option::expect_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:1638:5
  10: sc_state_db::noncanonical::discard_descendants
  11: sc_state_db::noncanonical::discard_descendants
  12: sc_state_db::noncanonical::NonCanonicalOverlay<BlockHash,Key>::apply_pending
  13: sc_state_db::StateDb<BlockHash,Key>::apply_pending
  14: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::commit_operation
  15: <sc_service::client::client::Client<B,E,Block,RA> as sc_client_api::backend::LockImportRun<Block,B>>::lock_import_and_run
  16: sc_finality_grandpa::environment::finalize_block
  17: <sc_finality_grandpa::environment::Environment<B,Block,C,N,SC,VR> as finality_grandpa::voter::Environment<<Block as sp_runtime::traits::Block>::Hash,<<Block as sp_runtime::traits::Block>::Header as sp_runtime::traits::Header>::Number>>::finalize_block
  18: <finality_grandpa::voter::Voter<H,N,E,GlobalIn,GlobalOut> as core::future::future::Future>::poll
  19: <sc_finality_grandpa::VoterWork<B,Block,C,N,SC,VR> as core::future::future::Future>::poll
  20: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  21: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  22: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  23: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  24: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  26: std::thread::local::LocalKey<T>::with
  27: tokio::park::thread::CachedParkThread::block_on
  28: tokio::runtime::handle::Handle::block_on
  29: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  30: tokio::runtime::task::harness::Harness<T,S>::poll
  31: tokio::runtime::blocking::pool::Inner::run
  32: std::sys_common::backtrace::__rust_begin_short_backtrace
  33: core::ops::function::FnOnce::call_once{{vtable.shim}}
  34: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  35: _pthread_from_mach_thread_np


Thread 'tokio-runtime-worker' panicked at 'there is a parent entry for each entry in levels; qed', /Users/john/.cargo/git/checkouts/substrate-7e08433d4c370a21/de6033a/client/state-db/src/noncanonical.rs:150
```

- Describe the role your node plays, e.g. validator, full node or light client.

- Any command-line options were passed?
Starting command : 
 `./polkadot --chain westend --ws-port 9944 --detailed-log-output  --no-prometheus --base-path /Users/john/parity/westend --force-westend --storage-chain  --sync Fast --database rocksdb --name johnishere --rpc-methods unsafe`

**Comment by johndoe0x** [comment]
@arkpar Please check this issue.
