### ISSUE TITLE
Inserted Beefy keys and crashed 2/3 validators

### ISSUE THREAD

**Issue by decentration** [paritytech/polkadot#4725]
I'm setting up a Rococo staging network
~18,000 blocks, was trying to debug a validator so it starts working, because only 2 validators were preparing blocks.
I was submitting all the keys as mentioned here: https://github.com/Kabocha-Network/polkadot/blob/1a299b53bbdaaec6587c850ca3bc2dcd58eae99f/node/service/src/chain_spec.rs#L782

In my attempt to debug i submitted the Beefy keys like this:

```
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", 
"method": "author_insertKey", "params":["beef", "my 12 word key", "0x322803d283792a0e753379257d3a532d75e750f72ca8057a45d149387d17c402"] }' http://localhost:9933
```

_(note i used "beef" as the tag, guessing this is correct for beefy?)_

After submitting the keys and restarting the nodes, 2 out of the 3 validators crashed with this report:

```
2022-01-15 15:31:04 Parity Polkadot    
2022-01-15 15:31:04 ✌️  version 0.9.13-unknown-x86_64-linux-gnu    
2022-01-15 15:31:04 ❤️  by Parity Technologies <admin@parity.io>, 2017-2022    
2022-01-15 15:31:04 📋 Chain specification: Pop-Art Staging Testnet    
2022-01-15 15:31:04 🏷 Node name: Decentration01    
2022-01-15 15:31:04 👤 Role: AUTHORITY    
2022-01-15 15:31:04 💾 Database: RocksDb at /polkadot/.local/share/polkadot/chains/rococo_pop_art_staging_testnet/db/full    
2022-01-15 15:31:04 ⛓  Native runtime: rococo-9130 (parity-rococo-v2.0-0.tx0.au0)    
2022-01-15 15:31:04 🏷 Local node identity is: 12D3KooWDHAB5GLbVBgHgvv1yuKbPKTmd8ZxEa5PUsAhDY1VYRW9    
2022-01-15 15:31:04 📦 Highest known block at #18977    
2022-01-15 15:31:04 〽️ Prometheus exporter started at 127.0.0.1:9615    
2022-01-15 15:31:04 Listening for new connections on 0.0.0.0:9944.    
2022-01-15 15:31:04 👶 Starting BABE Authorship worker    
2022-01-15 15:31:09 🔍 Discovered new external address for our node: /ip4/134.122.101.173/tcp/30333/p2p/12D3KooWDHAB5GLbVBgHgvv1yuKbPKTmd8ZxEa5PUsAhDY1VYRW9    
2022-01-15 15:31:09 💤 Idle (2 peers), best: #18977 (0x81ef…6a53), finalized #18838 (0xbb2e…a996), ⬇ 2.5kiB/s ⬆ 2.2kiB/s    
2022-01-15 15:31:14 💤 Idle (3 peers), best: #18977 (0x81ef…6a53), finalized #18838 (0xbb2e…a996), ⬇ 3.9kiB/s ⬆ 3.3kiB/s    
2022-01-15 15:31:19 Detected prevote equivocation in the finality worker: Equivocation { round_number: 103, identity: Public(9705184808e321b2a30246cb63976e703fec4f2f7551b2b0dbc7cd7bb144a13d (14R1kA5J...)), first: (Prevote { target_hash: 0x5507d85c07b33a65e275d3ab2fcb446c5214388b7437e6b53fa11a8d37387949, target_number: 18839 }, Signature(180ce3daa4e38fc5860f5ea86d89434467b08a630e3a061163e24b1a3b5ba9095d4bda641354896ab98d94a26cd6576d595236a93d30a297252a670c5c5c1400)), second: (Prevote { target_hash: 0x0e7cfc1936ad518f5b4d6dffafbda2875cbf0e49608f313a31cd13b5a0babac3, target_number: 18855 }, Signature(bdc761972f76c3433780d7ba0f2ee0f4c77cb3f98fd7a526212a8a407240cb855c149a27cebd09d3d397d294d166a28c028d9800e7fda264046ed8d856553503)) }    
2022-01-15 15:31:19 Submitted GRANDPA equivocation report.    

====================

Version: 0.9.13-unknown-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:628:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   5: core::panicking::panic_fmt
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   6: core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/slice/mod.rs:3049:13
   7: <sp_core::ecdsa::Public as sp_core::crypto::Public>::from_slice
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   9: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  10: <sc_keystore::local::LocalKeystore as sp_keystore::SyncCryptoStore>::ecdsa_public_keys
  11: beefy_gadget::keystore::BeefyKeystore::public_keys
  12: beefy_gadget::worker::BeefyWorker<B,C,BE>::handle_finality_notification
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: std::thread::local::LocalKey<T>::with
  18: tokio::park::thread::CachedParkThread::block_on
  19: tokio::runtime::handle::Handle::block_on
  20: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  21: tokio::runtime::task::harness::Harness<T,S>::poll
  22: tokio::runtime::blocking::pool::Inner::run
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
  24: core::ops::function::FnOnce::call_once{{vtable.shim}}
  25: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/thread.rs:106:17
  26: start_thread
  27: clone


Thread 'tokio-runtime-worker' panicked at 'source slice length (32) does not match destination slice length (33)', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/slice/mod.rs:3056

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new
 ```

**Comment by bkchr** [comment]
Please use latest master, it is fixed there.

You are also not using a correct public key, because it needs to be 33 bytes as you see.

**Comment by decentration** [comment]
@bkchr, thanks, a couple quick questions…

- do you always recommend using master branch?

- Also beefy key is the ecsda scheme, which is 33 bytes, is it not? 

- is “beef” the correct parameter for beefy? And is it essential for general function of the chain?

**Comment by decentration** [comment]
> You are also not using a correct public key, because it needs to be 33 bytes as you see.

Sorry i just understood your point! my second point above is void.
