### ISSUE TITLE
Validator exits unexpectedly

### ISSUE THREAD

**Issue by jack-kearney** [paritytech/polkadot#478]
I'm operating a local testnet with 6 validators. With some regularity, several of my validators will exit unexpectedly with the following stack trace:

```
Version: 0.6.2-9c72bfdb-x86_64-linux-gnu

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed
   6: <substrate_state_machine::ext::Ext<H,N,B,T,O> as substrate_primitives::traits::Externalities<H>>::storage
   7: std::thread::local::LocalKey<T>::with
   8: sr_io::storage
   9: srml_support::storage::unhashed::get
  10: srml_system::Module<T>::initialize
  11: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::initialize_block
  12: substrate_client::runtime_api::runtime_decl_for_Core::initialize_block_native_call_generator::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  15: substrate_executor::native_executor::safe_call
  16: std::thread::local::LocalKey<T>::with
  17: std::thread::local::LocalKey<T>::with
  18: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_aux
  19: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_using_consensus_failure_handler
  20: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hashe
r>>::contextual_call
  21: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at
  22: substrate_client::runtime_api::runtime_decl_for_Core::initialize_block_call_api_at
  23: substrate_client::runtime_api::Core::initialize_block
  24: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hashe
r>>::contextual_call
  25: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at
  26: polkadot_primitives::parachain::runtime_decl_for_ParachainHost::duty_roster_call_api_at
  27: polkadot_primitives::parachain::ParachainHost::duty_roster
  28: polkadot_validation::ParachainValidation<C,N,P>::get_or_instantiate
  29: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
  30: <futures::future::select::Select<A,B> as futures::future::Future>::poll
  31: futures::future::chain::Chain<A,B,C>::poll
  32: futures::task_impl::std::set
  33: tokio_current_thread::CurrentRunner::set_spawn
  34: tokio_current_thread::scheduler::Scheduler<U>::tick
  35: tokio_current_thread::Entered<P>::block_on
  36: std::thread::local::LocalKey<T>::with
  37: std::thread::local::LocalKey<T>::with
  38: std::thread::local::LocalKey<T>::with
  39: std::thread::local::LocalKey<T>::with
  40: tokio::runtime::current_thread::runtime::Runtime::block_on
  41: std::sys_common::backtrace::__rust_begin_short_backtrace
  42: std::panicking::try::do_call
  43: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  44: core::ops::function::FnOnce::call_once{{vtable.shim}}
  45: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  46: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  47: start_thread
  48: __clone


Thread '<unnamed>' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x4aafaea006fbbcff6db8d841af66552867b67868e1f0d404e2fc0b24dd2b924f"', src/libcore/result.rs:999
```

I should note that I have modified the `v0.6.2` client to:
1) Enable transactions
2) Change the block time to 1 second
3) Change the epoch time to 10 minutes

Please let me know if I can provide more information on the setup

**Comment by iammelea** [comment]
1 sec is very short, maybe try test 6 sec block

**Comment by joepetrowski** [comment]
Just got the same error running a normal node on `v0.6.5` on Kusama (not local net). Only param was `--name`.

Full stack trace:
```
2019-11-03 14:45:11 Idle (23 peers), best: #524039 (0x23bd…60e3), finalized #524037 (0xa984…1184), ⬇ 116.4kiB/s ⬆ 239.3kiB/s
2019-11-03 14:45:12 Imported #524040 (0x56f8…7c17)
2019-11-03 14:45:12 Imported #524040 (0x9b04…f7a2)
2019-11-03 14:45:13 Applying authority set change scheduled at block #524038
2019-11-03 14:45:13 Applying GRANDPA set change to new set with 75 authorities

====================

Version: 0.6.5-39397abb-x86_64-linux-gnu

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed
             at src/libcore/result.rs:1084
   6: <substrate_state_machine::ext::Ext<H,N,B,T> as substrate_externalities::Externalities>::storage
   7: std::thread::local::LocalKey<T>::with
   8: sr_io::storage
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  11: <<substrate_executor::host_interface::SubstrateExternals as substrate_wasm_interface::HostFunctions>::functions::ext_get_allocated_storage as substrate_wasm_interface::Function>::execute
  12: <substrate_executor::wasmi_execution::FunctionExecutor as wasmi::host::Externals>::invoke_index
  13: wasmi::func::FuncInstance::invoke
  14: wasmi::runner::Interpreter::start_execution
  15: wasmi::func::FuncInstance::invoke
  16: std::thread::local::LocalKey<T>::with
  17: substrate_executor::wasmi_execution::call_in_wasm_module
  18: <substrate_executor::wasmi_execution::WasmiRuntime as substrate_executor::wasm_runtime::WasmRuntime>::call
  19: std::thread::local::LocalKey<T>::with
  20: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
  21: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
  22: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call
  23: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at
  24: <polkadot_runtime::RuntimeApiImpl<RuntimeApiImplCall> as substrate_client::runtime_api::Core<<polkadot_runtime::Runtime as sr_primitives::traits::GetNodeBlockType>::NodeBlock>>::Core_initialize_block_runtime_api_impl
  25: substrate_client::runtime_api::Core::initialize_block
  26: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call
  27: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at
  28: substrate_client::runtime_api::runtime_decl_for_TaggedTransactionQueue::validate_transaction_call_api_at
  29: <substrate_transaction_pool::api::FullChainApi<T,Block> as substrate_transaction_graph::pool::ChainApi>::validate_transaction
  30: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  31: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  32: substrate_transaction_graph::pool::Pool<B>::prune
  33: substrate_service::builder::maintain_transaction_pool
  34: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
  35: <futures::future::select::Select<A,B> as futures::future::Future>::poll
  36: futures::future::chain::Chain<A,B,C>::poll
  37: futures::task_impl::std::set
  38: std::panicking::try::do_call
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  40: tokio_threadpool::task::Task::run
  41: tokio_threadpool::worker::Worker::run_task
  42: tokio_threadpool::worker::Worker::run
  43: std::thread::local::LocalKey<T>::with
  44: std::thread::local::LocalKey<T>::with
  45: std::thread::local::LocalKey<T>::with
  46: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  47: std::thread::local::LocalKey<T>::with
  48: std::thread::local::LocalKey<T>::with
  49: std::sys_common::backtrace::__rust_begin_short_backtrace
  50: std::panicking::try::do_call
  51: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  52: core::ops::function::FnOnce::call_once{{vtable.shim}}
  53: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  54: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  55: start_thread
  56: clone


Thread 'tokio-runtime-worker-2' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0xb6e5841078e737e86e68770c2f698b1d07ef3be18a14538959ca76f9843ad7f5"', src/libcore/result.rs:1084
```

**Comment by gavofyork** [comment]
Should be fixed now.
