### ISSUE TITLE
Bug:  Thread '<unnamed>' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x7544…764f"'

### ISSUE THREAD

**Issue by shenzhun** [paritytech/polkadot#498]
polkadot: 0.2.2
account: 5F7jDKPE19CS5zDsj66kizaQ9SKPpZ261Un2JAdiruSqRF1o
Balance: 26, 673 DOTs

`
2018-08-05 08:38:20 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:21 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:21 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:22 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:22 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:23 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:23 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:24 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:24 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:25 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:25 Syncing, target=#946804 (2 peers), best: #95434 (3d8f…11a9)
2018-08-05 08:38:25 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:26 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:26 Node PeerId(Qmac3mBxTQLLJi5Z6sdkkA3GLP3RMhSQiwCoeXZ8Xrb8Aj) with peer ID 371 through protocol [100, 111, 116] disconnected
2018-08-05 08:38:26 Node PeerId(QmSfiHsBRq1U8su2Edv8RgVvFHx3mm52j94eEuhPTM6GR5) with peer ID 419 through protocol [100, 111, 116] disconnected
2018-08-05 08:38:26 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:27 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:27 BFT agreement error: Authoring for current runtime is not supported since it has no version.
2018-08-05 08:38:28 BFT agreement error: Authoring for current runtime is not supported since it has no version.

====================

stack backtrace:
   0:     0x55a1aec0369c - backtrace::backtrace::trace::h4230e4e801d84578
   1:     0x55a1aec02672 - <backtrace::capture::Backtrace as core::default::Default>::default::h7d906cf62bcc73c8
   2:     0x55a1aec026e8 - backtrace::capture::Backtrace::new::hdba378c25aad811e
   3:     0x55a1ae4908d0 - substrate_cli::panic_hook::panic_hook::h24d21dd82563e55e
   4:     0x55a1ae4905e8 - core::ops::function::Fn::call::h4a2c77645edff6d0
   5:     0x55a1aed35123 - std::panicking::rust_panic_with_hook::he4c3a67f6258a8f9
                        at libstd/panicking.rs:515
   6:     0x55a1aed34e79 - std::panicking::continue_panic_fmt::h156c04b2aea348c7
                        at libstd/panicking.rs:426
   7:     0x55a1aed34b95 - rust_begin_unwind
                        at libstd/panicking.rs:337
   8:     0x55a1aed916ab - core::panicking::panic_fmt::h0e6d5c6fb2a34dd6
                        at libcore/panicking.rs:92
   9:     0x55a1ae2751f8 - core::result::unwrap_failed::h0469309e2289725d
  10:     0x55a1ae34ccb1 - <substrate_state_machine::ext::Ext<'a, B> as substrate_state_machine::Externalities>::storage::hee1bd8871c0bb40f
  11:     0x55a1ae3aae19 - <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block>>::runtime_version::h7987e4ac15899881
  12:     0x55a1ae34cdf9 - <substrate_client::client::Client<B, E, Block> as substrate_bft::Authorities<Block>>::authorities::ha0eb42f9864db393
  13:     0x55a1ae23d082 - <substrate_bft::BftService<B, P, I>>::build_upon::he8ea6e48adf6c608
  14:     0x55a1ae33a59e - <futures::future::chain::Chain<A, B, C>>::poll::hfd6fd18c05d28033
  15:     0x55a1ae3c1038 - <futures::future::map::Map<A, F> as futures::future::Future>::poll::hd72c1eb4cfd79b45
  16:     0x55a1ae24495f - futures::task_impl::std::set::heddc0cd3a4aa342d
  17:     0x55a1ae36dce9 - tokio::executor::current_thread::CurrentRunner::set_spawn::he1b9928b32fb7200
  18:     0x55a1ae24186c - <tokio::executor::current_thread::scheduler::Scheduler<U>>::tick::h434476b15a96744a
  19:     0x55a1ae374f33 - <tokio::executor::current_thread::Entered<'a, P>>::block_on::hcbdc55c8b9fa6b4f
  20:     0x55a1ae2126d8 - <std::thread::local::LocalKey<T>>::with::h762a1571a1e67438
  21:     0x55a1ae214417 - <std::thread::local::LocalKey<T>>::with::hd7e50e9d94403b89
  22:     0x55a1ae213e35 - <std::thread::local::LocalKey<T>>::with::hb81efa07322ad645
  23:     0x55a1ae21129b - <std::thread::local::LocalKey<T>>::with::h281b6097d1131fe3
  24:     0x55a1ae23c367 - tokio::runtime::current_thread::runtime::Runtime::block_on::ha3f0a03bf3ad4065
  25:     0x55a1ae252d4c - std::sys_common::backtrace::__rust_begin_short_backtrace::h8d4f038f12a8fcbf
  26:     0x55a1ae1f7b05 - std::panicking::try::do_call::h23b8e215a1ef5cd6
  27:     0x55a1aed58559 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  28:     0x55a1ae276030 - <F as alloc::boxed::FnBox<A>>::call_box::h41be3ec64104b0bd
  29:     0x55a1aed326fa - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h75e539106a648d39
                        at /checkout/src/liballoc/boxed.rs:650
                         - std::sys_common::thread::start_thread::h88a639c99862a9f5
                        at libstd/sys_common/thread.rs:24
  30:     0x55a1aed35c95 - std::sys::unix::thread::Thread::new::thread_start::h7d7a420a78cfa84d
                        at libstd/sys/unix/thread.rs:90
  31:     0x7fb7c27b16b9 - start_thread
  32:     0x7fb7c22d141c - clone
  33:                0x0 - <unknown>

Thread '<unnamed>' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x7544…764f"', libcore/result.rs:945
`

**Comment by shenzhun** [comment]
same bug https://github.com/paritytech/polkadot/issues/487
