### ISSUE TITLE
polkadot node crashed when start with polkadot-v0.9.17

### ISSUE THREAD

**Issue by VegeBun-csj** [paritytech/polkadot#4994]
my linux kernal is arch.
when execute with command: `./target/release/polkadot --chain rococo-local-cfde.json --alice --tmp --port 30333 --ws-port 9944` which i want to start a validator.
the log is :
```
2022-02-26 23:00:01 Parity Polkadot    
2022-02-26 23:00:01 ✌️  version 0.9.17-b567c8bfa7-x86_64-linux-gnu    
2022-02-26 23:00:01 ❤️  by Parity Technologies <admin@parity.io>, 2017-2022    
2022-02-26 23:00:01 📋 Chain specification: Rococo Local Testnet    
2022-02-26 23:00:01 🏷  Node name: Alice    
2022-02-26 23:00:01 👤 Role: AUTHORITY    
2022-02-26 23:00:01 💾 Database: RocksDb at /tmp/substrateQ5QFyg/chains/rococo_local_testnet/db/full    
2022-02-26 23:00:01 ⛓  Native runtime: rococo-9140 (parity-rococo-v2.0-0.tx0.au0)    

====================

Version: 0.9.17-b567c8bfa7-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:502:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:498:5
   5: core::panicking::panic_fmt
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panicking.rs:106:14
   6: polkadot_runtime_parachains::configuration::HostConfiguration<BlockNumber>::panic_if_not_consistent
   7: std::thread::local::LocalKey<T>::with
   8: sp_state_machine::basic::BasicExternalities::execute_with_storage
   9: <rococo_runtime::GenesisConfig as sp_runtime::BuildStorage>::assimilate_storage
  10: <polkadot_service::chain_spec::RococoGenesisExt as sp_runtime::BuildStorage>::assimilate_storage
  11: sp_runtime::BuildStorage::build_storage
  12: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sp_runtime::BuildStorage>::build_storage
  13: sc_service::client::client::Client<B,E,Block,RA>::new
  14: sc_service::builder::new_full_parts
  15: polkadot_service::new_full
  16: polkadot_service::build_full
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: std::thread::local::LocalKey<T>::with
  19: tokio::park::thread::CachedParkThread::block_on
  20: tokio::runtime::thread_pool::ThreadPool::block_on
  21: tokio::runtime::Runtime::block_on
  22: polkadot_cli::command::run
  23: polkadot::main
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: std::rt::lang_start::{{closure}}
  26: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:406:40
      std::panicking::try
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:370:19
      std::panic::catch_unwind
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:406:40
      std::panicking::try
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:370:19
      std::panic::catch_unwind
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal
             at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/rt.rs:128:20
  27: main
  28: __libc_start_main
  29: _start


Thread 'main' panicked at 'Host configuration is inconsistent: MaxUpwardMessageSizeExceeded { max_message_size: 1048576 }', /home/bun/polkadot/runtime/parachains/src/configuration.rs:418

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

2022-02-26 23:00:03 Took active validators from set with wrong size    
2022-02-26 23:00:03 Took active validators from set with wrong size.    
2022-02-26 23:00:03 Took active validators from set with wrong size    
```

**Comment by bkchr** [comment]
When have you generated `rococo-local-cfde.json`? Looks like you are using an invalid chain spec.
