### ISSUE TITLE
sentry crashed

### ISSUE THREAD

**Issue by awrelll** [paritytech/polkadot#518]
```
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]: ====================
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]: Version: 0.6.5-x86_64-linux-gnu
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]: stack backtrace:
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:    0: substrate_panic_handler::panic_hook
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/panic-handler/src/lib.rs:148
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:    1: substrate_panic_handler::set::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/panic-handler/src/lib.rs:58
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:    2: std::panicking::rust_panic_with_hook
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at src/libstd/panicking.rs:481
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:    3: std::panicking::continue_panic_fmt
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at src/libstd/panicking.rs:384
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:    4: rust_begin_unwind
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at src/libstd/panicking.rs:311
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:    5: core::panicking::panic_fmt
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at src/libcore/panicking.rs:85
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:    6: core::panicking::panic
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at src/libcore/panicking.rs:49
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:    7: <u32 as core::ops::arith::Sub>::sub
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/arith.rs:198
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:    8: substrate_network::protocol::sync::fork_sync_request
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/network/src/protocol/sync.rs:1290
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:    9: substrate_network::protocol::sync::ChainSync<B>::block_requests::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/network/src/protocol/sync.rs:583
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   10: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:859
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   11: core::iter::traits::iterator::Iterator::try_fold
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/traits/iterator.rs:1671
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   12: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::try_fold
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:859
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   13: core::iter::traits::iterator::Iterator::try_for_each
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/traits/iterator.rs:1708
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   14: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:845
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   15: <either::Either<L,R> as core::iter::traits::iterator::Iterator>::next
Oct 30 05:33:13 gc

-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/either-1.5.3/src/lib.rs:643
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   16: <substrate_network::protocol::Protocol<B,S,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/network/src/protocol.rs:1667
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   17: <substrate_network::behaviour::Behaviour<B,S,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/network/src/behaviour.rs:35
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   18: <libp2p_swarm::ExpandedSwarm<TTransport,TBehaviour,TInEvent,TOutEvent,THandler,THandlerErr,TConnInfo> as futures::stream::Stream>::poll
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.2.0/src/lib.rs:426
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   19: <substrate_network::service::NetworkWorker<B,S,H> as futures::stream::Stream>::poll
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/network/src/service.rs:716
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   20: substrate_service::build_network_future::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/service/src/lib.rs:442
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   21: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/poll_fn.rs:43
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   22: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/map_err.rs:30
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   23: <futures::future::select::Select<A,B> as futures::future::Future>::poll
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/select.rs:48
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   24: futures::future::chain::Chain<A,B,C>::poll
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:26
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   25: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/then.rs:32
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   26: <alloc::boxed::Box<F> as futures::future::Future>::poll
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   27: <alloc::boxed::Box<F> as futures::future::Future>::poll
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   28: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   29: futures::task_impl::Spawn<T>::enter::{{closure}}
Oct 30 05:33:13 gc-polkadot-

sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   30: futures::task_impl::std::set
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   31: futures::task_impl::Spawn<T>::enter
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   32: futures::task_impl::Spawn<T>::poll_fn_notify
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   33: futures::task_impl::Spawn<T>::poll_future_notify
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   34: tokio_threadpool::task::Task::run::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/task/mod.rs:145
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   35: core::ops::function::FnOnce::call_once
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/function.rs:235
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   36: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:315
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   37: std::panicking::try::do_call
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:296
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   38: __rust_maybe_catch_panic
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at src/libpanic_unwind/lib.rs:80
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   39: std::panicking::try
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:275
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   40: std::panic::catch_unwind
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:394
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   41: tokio_threadpool::task::Task::run
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/task/mod.rs:130
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   42: tokio_threadpool::worker::Worker::run_task2
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:567
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   43: tokio_threadpool::worker::Worker::run_task
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:459
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   44: tokio_threadpool::worker::Worker::try_run_owned_task
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:390
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   45: tokio_threadpool::worker::Worker::try_run_task
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at ro

ot/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:297
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   46: tokio_threadpool::worker::Worker::run
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:241
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   47: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:390
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   48: tokio_timer::timer::handle::with_default::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:101
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   49: std::thread::local::LocalKey<T>::try_with
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   50: std::thread::local::LocalKey<T>::with
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   51: tokio_timer::timer::handle::with_default
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:84
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   52: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:382
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   53: tokio_timer::clock::clock::with_default::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:137
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   54: std::thread::local::LocalKey<T>::try_with
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   55: std::thread::local::LocalKey<T>::with
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   56: tokio_timer::clock::clock::with_default
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:117
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   57: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:381
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   58: tokio_reactor::with_default::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:237
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   59: std::thread::local::LocalKey<T>::try_with
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   60: std::thread::local::LocalKey<T>::with
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc47

41caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   61: tokio_reactor::with_default
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:217
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   62: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:380
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   63: tokio_threadpool::callback::Callback::call
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/callback.rs:22
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   64: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:127
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   65: tokio_executor::global::with_default::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:209
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   66: std::thread::local::LocalKey<T>::try_with
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   67: std::thread::local::LocalKey<T>::with
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   68: tokio_executor::global::with_default
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:178
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   69: tokio_threadpool::worker::Worker::do_run::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:125
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   70: std::thread::local::LocalKey<T>::try_with
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   71: std::thread::local::LocalKey<T>::with
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   72: tokio_threadpool::worker::Worker::do_run
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:116
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   73: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/pool/mod.rs:345
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   74: std::sys_common::backtrace::__rust_begin_short_backtrace
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/sys_common/backtrace.rs:77
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   75: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/mod.rs:470
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   76: <std:

:panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:315
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   77: std::panicking::try::do_call
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:296
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   78: __rust_maybe_catch_panic
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at src/libpanic_unwind/lib.rs:80
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   79: std::panicking::try
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:275
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   80: std::panic::catch_unwind
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:394
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   81: std::thread::Builder::spawn_unchecked::{{closure}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/mod.rs:469
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   82: core::ops::function::FnOnce::call_once{{vtable.shim}}
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/function.rs:235
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   83: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   84: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:       std::sys_common::thread::start_thread
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at src/libstd/sys_common/thread.rs:13
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:       std::sys::unix::thread::Thread::new::thread_start
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:              at src/libstd/sys/unix/thread.rs:79
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   85: start_thread
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]:   86: __clone
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]: Thread 'tokio-runtime-worker-3' panicked at 'attempt to subtract with overflow', /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/arith.rs:198
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]: This is a bug. Please report it at:
Oct 30 05:33:13 gc-polkadot-sentry01 polkadot[2648]: #011https://github.com/paritytech/polkadot/issues/new
Oct 30 05:33:13 gc-polkadot-sentry01 systemd[1]: polkadot.service: Main process exited, code=exited, status=1/FAILURE
Oct 30 05:33:13 gc-polkadot-sentry01 systemd[1]: polkadot.service: Failed with result 'exit-code'.
Oct 30 05:33:24 gc-polkadot-sentry01 systemd[1]: polkadot.service: Service hold-off time over, scheduling restart.
Oct 30 05:33:24 gc-polkadot-sentry01 systemd[1]: polkadot.service: Scheduled restart job, restart counter is at 7.
Oct 30 05:33:24 gc-polkadot-sentry01 systemd[1]: Stopped Polkadot Node.
```

**Comment by bkchr** [comment]
Thank you, we will look into it. 
It seems that you are running your node in debug mode? Is this by intention? If not, you should use `cargo build --release` for building the node.

**Comment by arkpar** [comment]
Fixed in https://github.com/paritytech/substrate/pull/3942 (https://github.com/paritytech/substrate/pull/3942/files#diff-2296dbbf477c61a47a8de09e68b54002R1288-R1293)
