### ISSUE TITLE
sentry node crash and stops

### ISSUE THREAD

**Issue by wimel** [paritytech/polkadot#541]
```
Nov 05 17:47:52 KusamaSentry polkadot[15586]: ====================
Nov 05 17:47:52 KusamaSentry polkadot[15586]: Version: 0.6.8-d102bc53-x86_64-linux-gnu
Nov 05 17:47:52 KusamaSentry polkadot[15586]: stack backtrace:
Nov 05 17:47:52 KusamaSentry polkadot[15586]:    0: substrate_panic_handler::set::{{closure}}
Nov 05 17:47:52 KusamaSentry polkadot[15586]:    1: std::panicking::rust_panic_with_hook
Nov 05 17:47:52 KusamaSentry polkadot[15586]:              at src/libstd/panicking.rs:481
Nov 05 17:47:52 KusamaSentry polkadot[15586]:    2: std::panicking::continue_panic_fmt
Nov 05 17:47:52 KusamaSentry polkadot[15586]:              at src/libstd/panicking.rs:384
Nov 05 17:47:52 KusamaSentry polkadot[15586]:    3: rust_begin_unwind
Nov 05 17:47:52 KusamaSentry polkadot[15586]:              at src/libstd/panicking.rs:311
Nov 05 17:47:52 KusamaSentry polkadot[15586]:    4: core::panicking::panic_fmt
Nov 05 17:47:52 KusamaSentry polkadot[15586]:              at src/libcore/panicking.rs:85
Nov 05 17:47:52 KusamaSentry polkadot[15586]:    5: core::result::unwrap_failed
Nov 05 17:47:52 KusamaSentry polkadot[15586]:              at src/libcore/result.rs:1084
Nov 05 17:47:52 KusamaSentry polkadot[15586]:    6: <substrate_state_machine::ext::Ext<H,N,B,T> as substrate_externalities::Externalities>::original_storage_hash
Nov 05 17:47:52 KusamaSentry polkadot[15586]:    7: substrate_executor::wasm_runtime::RuntimesCache::fetch_runtime
Nov 05 17:47:52 KusamaSentry polkadot[15586]:    8: std::thread::local::LocalKey<T>::with
Nov 05 17:47:52 KusamaSentry polkadot[15586]:    9: <substrate_executor::native_executor::NativeExecutor<D> as substrate_executor::RuntimeInfo>::runtime_version
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   10: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::runtime_version
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   11: substrate_client::block_builder::api::runtime_decl_for_BlockBuilder::check_inherents_call_api_at
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   12: substrate_client::block_builder::api::BlockBuilder::check_inherents
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   13: <substrate_consensus_babe::BabeVerifier<B,E,Block,RA,PRA> as substrate_consensus_common::import_queue::Verifier<Block>>::verify
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   14: substrate_consensus_common::import_queue::import_single_block
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   15: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   16: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   17: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   18: futures_executor::thread_pool::PoolState::work
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   19: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   20: std::panicking::try::do_call
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   21: __rust_maybe_catch_panic
Nov 05 17:47:52 KusamaSentry polkadot[15586]:              at src/libpanic_unwind/lib.rs:80
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   22: core::ops::function::FnOnce::call_once{{vtable.shim}}
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   23: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 05 17:47:52 KusamaSentry polkadot[15586]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   24: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 05 17:47:52 KusamaSentry polkadot[15586]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
Nov 05 17:47:52 KusamaSentry polkadot[15586]:       std::sys_common::thread::start_thread
Nov 05 17:47:52 KusamaSentry polkadot[15586]:              at src/libstd/sys_common/thread.rs:13
Nov 05 17:47:52 KusamaSentry polkadot[15586]:       std::sys::unix::thread::Thread::new::thread_start
Nov 05 17:47:52 KusamaSentry polkadot[15586]:              at src/libstd/sys/unix/thread.rs:79
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   25: start_thread
Nov 05 17:47:52 KusamaSentry polkadot[15586]:   26: __clone
Nov 05 17:47:52 KusamaSentry polkadot[15586]: Thread 'import-queue-worker-0' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0xb5433c72c62fba34fba46e2c74933f6cf79ccf04b7291d5e02c6cbd0b6e43ff1"', src/libcore/result.rs:1084

Nov 05 17:47:52 KusamaSentry polkadot[15586]: This is a bug. Please report it at:
Nov 05 17:47:52 KusamaSentry polkadot[15586]: https://github.com/paritytech/polkadot/issues/new
```
>rustup -V:
`rustup 1.20.2 (13979c968 2019-10-16)`

**Comment by iammelea** [comment]
Update to the last v0.6.9
Closse this issue

**Comment by wimel** [comment]
Same issue with `v0.6.9` 
```
Nov 05 19:07:33 KusamaSentry polkadot[7866]: ====================
Nov 05 19:07:33 KusamaSentry polkadot[7866]: Version: 0.6.9-fffa22d4-x86_64-linux-gnu
Nov 05 19:07:33 KusamaSentry polkadot[7866]: stack backtrace:
Nov 05 19:07:33 KusamaSentry polkadot[7866]:    0: substrate_panic_handler::set::{{closure}}
Nov 05 19:07:33 KusamaSentry polkadot[7866]:    1: std::panicking::rust_panic_with_hook
Nov 05 19:07:33 KusamaSentry polkadot[7866]:              at src/libstd/panicking.rs:481
Nov 05 19:07:33 KusamaSentry polkadot[7866]:    2: std::panicking::continue_panic_fmt
Nov 05 19:07:33 KusamaSentry polkadot[7866]:              at src/libstd/panicking.rs:384
Nov 05 19:07:33 KusamaSentry polkadot[7866]:    3: rust_begin_unwind
Nov 05 19:07:33 KusamaSentry polkadot[7866]:              at src/libstd/panicking.rs:311
Nov 05 19:07:33 KusamaSentry polkadot[7866]:    4: core::panicking::panic_fmt
Nov 05 19:07:33 KusamaSentry polkadot[7866]:              at src/libcore/panicking.rs:85
Nov 05 19:07:33 KusamaSentry polkadot[7866]:    5: core::result::unwrap_failed
Nov 05 19:07:33 KusamaSentry polkadot[7866]:              at src/libcore/result.rs:1084
Nov 05 19:07:33 KusamaSentry polkadot[7866]:    6: <substrate_state_machine::ext::Ext<H,N,B,T> as substrate_externalities::Externalities>::original_storage_hash
Nov 05 19:07:33 KusamaSentry polkadot[7866]:    7: substrate_executor::wasm_runtime::RuntimesCache::fetch_runtime
Nov 05 19:07:33 KusamaSentry polkadot[7866]:    8: std::thread::local::LocalKey<T>::with
Nov 05 19:07:33 KusamaSentry polkadot[7866]:    9: <substrate_executor::native_executor::NativeExecutor<D> as substrate_executor::RuntimeInfo>::runtime_version
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   10: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::runtime_version
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   11: substrate_client::block_builder::api::runtime_decl_for_BlockBuilder::check_inherents_call_api_at
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   12: substrate_client::block_builder::api::BlockBuilder::check_inherents
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   13: <substrate_consensus_babe::BabeVerifier<B,E,Block,RA,PRA> as substrate_consensus_common::import_queue::Verifier<Block>>::verify
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   14: substrate_consensus_common::import_queue::import_single_block
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   15: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   16: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   17: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   18: futures_executor::thread_pool::PoolState::work
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   19: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   20: std::panicking::try::do_call
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   21: __rust_maybe_catch_panic
Nov 05 19:07:33 KusamaSentry polkadot[7866]:              at src/libpanic_unwind/lib.rs:80
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   22: core::ops::function::FnOnce::call_once{{vtable.shim}}
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   23: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 05 19:07:33 KusamaSentry polkadot[7866]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   24: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 05 19:07:33 KusamaSentry polkadot[7866]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
Nov 05 19:07:33 KusamaSentry polkadot[7866]:       std::sys_common::thread::start_thread
Nov 05 19:07:33 KusamaSentry polkadot[7866]:              at src/libstd/sys_common/thread.rs:13
Nov 05 19:07:33 KusamaSentry polkadot[7866]:       std::sys::unix::thread::Thread::new::thread_start
Nov 05 19:07:33 KusamaSentry polkadot[7866]:              at src/libstd/sys/unix/thread.rs:79
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   25: start_thread
Nov 05 19:07:33 KusamaSentry polkadot[7866]:   26: __clone
Nov 05 19:07:33 KusamaSentry polkadot[7866]: Thread 'import-queue-worker-0' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0xb5433c72c62fba34fba46e2c74933f6cf79ccf04b7291d5e02c6cbd0b6e43ff1"', src/libcore/result.rs:1084
Nov 05 19:07:33 KusamaSentry polkadot[7866]: This is a bug. Please report it at:
Nov 05 19:07:33 KusamaSentry polkadot[7866]: https://github.com/paritytech/polkadot/issues/new
```

**Comment by iammelea** [comment]
Purge chain and resync from scratch
