### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'index out of bounds on Kusama RocksDB full node

### ISSUE THREAD

**Issue by m-saxemberg** [paritytech/polkadot#5672]
Version: [v0.9.23](https://github.com/paritytech/polkadot/releases/tag/v0.9.23) 
RocksDb
1TB SSD 
Database available upon request
While running a simple Kusama full node (not a validator) this message appeared:

```
5041 (0xe42e_1ee0), finalized #444928 (0xe043_8ca6), _ 168.3kiB/s _ 8.5kiB/s    
2022-06-09 05:18:32 _  Syncing 371.7 bps, target=#13047701 (32 peers), best: #44
6901 (0x21e8_79ca), finalized #446464 (0xefca_98e6), _ 7.7kiB/s _ 4.6kiB/s      2022-06-09 05:18:37 _  Syncing 338.7 bps, target=#13047702 (32 peers), best: #44
8595 (0x89f2_6308), finalized #448513 (0x3777_6891), _ 270.5kiB/s _ 5.2kiB/s    
2022-06-09 05:18:42 _  Syncing 392.8 bps, target=#13047703 (32 peers), best: #45
0560 (0x12a5_6036), finalized #450048 (0xe5ca_f0f8), _ 4.3kiB/s _ 4.8kiB/s      
2022-06-09 05:18:47 _  Syncing 348.8 bps, target=#13047703 (32 peers), best: #45
2305 (0xebe8_aebb), finalized #452096 (0x52f9_7738), _ 498.6kiB/s _ 7.7kiB/s    2022-06-09 05:18:52 _  Syncing 372.8 bps, target=#13047704 (32 peers), best: #454169 (0xf327_63c1), finalized #454144 (0x86ea_2a74), _ 5.0kiB/s _ 5.7kiB/s      
                                                                                
====================                                                            
                                        
Version: 0.9.23-a7e188cd966   
   0: sp_panic_handler::set::{{closure}}                                      
   1: std::panicking::rust_panic_with_hook      
    at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17                                                              
   2: std::panicking::begin_panic_handler::{{closure}}                      
   at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13                                                              
   3: std::sys_common::backtrace::__rust_end_short_backtrace                   
   at zustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18           
   4: rust_begin_unwind                                                         
             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5                                                               
   5: core::panicking::panic_fmt               
    at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14                                                             
   6: core::panicking::panic_bounds_check                                       
             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:85:5                       
   7: kvdb_rocksdb::Database::write  
   8: <sp_database::kvdb::DbAdapter<D> as sp_database::Database<H>>::com[21/741]
   9: sc_client_db::Backend<Block>::try_commit_operation                      
  10: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::commit_operation                                                                
  11: sc_finality_grandpa::environment::finalize_block                          
  12: sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC>::import_justification                                                                 
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll       
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll                                
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Futur
e>::poll                                                                        
  16: sc_consensus::import_queue::basic_queue::block_import_process::{{closure}}
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll                                                                          18: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>
::poll                                                                          
  19: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll  
  20: tokio::runtime::task::raw::poll   
  21: std::sys_common::backtrace::__rust_begin_short_backtrace   
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  24: start_thread
  25: clone


Thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 13 but the index is 3170893825', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/kvdb-rocksdb-0.15.2/src/lib.rs:278

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new



```

**Comment by bkchr** [comment]
CC @arkpar

**Comment by arkpar** [comment]
Apparently column index was set to `0xBD000001` in the transaction batch. We should only be using consts for column indexes so I don't see how this is possible. 
@cheme maybe you have ideas?

@m-saxemberg Could you please run memtest on this machine and check that the hardware is OK?

**Comment by cheme** [comment]
No idea here, same observation, the column number is wrong but all column number in transaction should only be initialized from constant constant values in sc-client-db.

**Comment by m-saxemberg** [comment]
Yes, there was a physical memory issue confirmed by both the memtest linux package and memtest outside the linux kernel. The memories were changed and now the error is gone.
