### ISSUE TITLE
Thread 'import-queue-worker-0' panicked at 'Transaction will be valid in the future'

### ISSUE THREAD

**Issue by artkaseman** [paritytech/polkadot#583]
One of our sentries just stopped syncing and had the following repeated in the logs

```
Nov 14 04:14:00  polkadot[560]: Version: 0.6.17-0929fe24-x86_64-linux-gnu
Nov 14 04:14:00  polkadot[560]: stack backtrace:
Nov 14 04:14:00  polkadot[560]:    0: substrate_panic_handler::set::{{closure}}
Nov 14 04:14:00  polkadot[560]:    1: std::panicking::rust_panic_with_hook
Nov 14 04:14:00  polkadot[560]:              at src/libstd/panicking.rs:477
Nov 14 04:14:00  polkadot[560]:    2: std::panicking::begin_panic
Nov 14 04:14:00  polkadot[560]:    3: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
Nov 14 04:14:00  polkadot[560]:    4: polkadot_runtime::api::dispatch
Nov 14 04:14:00  polkadot[560]:    5: std::panicking::try::do_call
Nov 14 04:14:00  polkadot[560]:    6: __rust_maybe_catch_panic
Nov 14 04:14:00  polkadot[560]:              at src/libpanic_unwind/lib.rs:80
Nov 14 04:14:00  polkadot[560]:    7: substrate_executor::native_executor::safe_call
Nov 14 04:14:00  polkadot[560]:    8: std::thread::local::LocalKey<T>::with
Nov 14 04:14:00  polkadot[560]:    9: <polkadot_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
Nov 14 04:14:00  polkadot[560]:   10: std::thread::local::LocalKey<T>::with
Nov 14 04:14:00  polkadot[560]:   11: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
Nov 14 04:14:00  polkadot[560]:   12: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_call_with_native_else_wasm_strategy
Nov 14 04:14:00  polkadot[560]:   13: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
Nov 14 04:14:00  polkadot[560]:   14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block
Nov 14 04:14:00  polkadot[560]:   15: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block
Nov 14 04:14:00  polkadot[560]:   16: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as substrate_consensus_common::block_i
Nov 14 04:14:00  polkadot[560]:   17: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::Blo
Nov 14 04:14:00  polkadot[560]:   18: substrate_consensus_common::import_queue::import_single_block
Nov 14 04:14:00  polkadot[560]:   19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 14 04:14:00  polkadot[560]:   20: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
Nov 14 04:14:00  polkadot[560]:   21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 14 04:14:00  polkadot[560]:   22: futures_executor::thread_pool::PoolState::work
Nov 14 04:14:00  polkadot[560]:   23: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov 14 04:14:00  polkadot[560]:   24: std::panicking::try::do_call
Nov 14 04:14:00  polkadot[560]:   25: __rust_maybe_catch_panic
Nov 14 04:14:00  polkadot[560]:              at src/libpanic_unwind/lib.rs:80
Nov 14 04:14:00  polkadot[560]:   26: core::ops::function::FnOnce::call_once{{vtable.shim}}
Nov 14 04:14:00  polkadot[560]:   27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 14 04:14:00  polkadot[560]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Nov 14 04:14:00  polkadot[560]:   28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 14 04:14:00  polkadot[560]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Nov 14 04:14:00  polkadot[560]:       std::sys_common::thread::start_thread
Nov 14 04:14:00  polkadot[560]:              at src/libstd/sys_common/thread.rs:13
Nov 14 04:14:00  polkadot[560]:       std::sys::unix::thread::Thread::new::thread_start
Nov 14 04:14:00  polkadot[560]:              at src/libstd/sys/unix/thread.rs:79
Nov 14 04:14:00  polkadot[560]:   29: start_thread
Nov 14 04:14:00  polkadot[560]:   30: __clone
Nov 14 04:14:00  polkadot[560]: Thread 'import-queue-worker-0' panicked at 'Transaction will be valid in the future', /var/lib/polkadot/.cargo/git/ch
Nov 14 04:14:00  polkadot[560]: This is a bug. Please report it at:
Nov 14 04:14:00  polkadot[560]:         https://github.com/paritytech/polkadot/issues/new
Nov 14 04:14:00  polkadot[560]: 2019-11-14 04:14:00 Block import error:
Nov 14 04:14:00  polkadot[560]: Execution(Wasmi(Trap(Trap { kind: Unreachable })))
```

**Comment by culmore2015** [comment]
found same error

**Comment by gavofyork** [comment]
did a restart help?

**Comment by kwunyeung** [comment]
I got the same

```
Nov 14 19:25:27 validator-node polkadot[19876]: Thread 'import-queue-worker-0' panicked at 'Transaction will be valid in the future', /home/kwunyueng/.cargo/git/checkouts/substrate-7e08433d4c370a21/aa937d9/srml/executive/src/lib.rs:242
Nov 14 19:25:27 validator-node polkadot[19876]: This is a bug. Please report it at:
Nov 14 19:25:27 validator-node polkadot[19876]:         https://github.com/paritytech/polkadot/issues/new
Nov 14 19:25:27 validator-node polkadot[19876]: 2019-11-14 19:25:27 Block import error:
Nov 14 19:25:27 validator-node polkadot[19876]: Execution(Wasmi(Trap(Trap { kind: Unreachable })))
Nov 14 19:25:28 validator-node polkadot[19876]: ====================
Nov 14 19:25:28 validator-node polkadot[19876]: Version: 0.6.17-0929fe24-x86_64-linux-gnu
Nov 14 19:25:28 validator-node polkadot[19876]: stack backtrace:
Nov 14 19:25:28 validator-node polkadot[19876]:    0: substrate_panic_handler::set::{{closure}}
Nov 14 19:25:28 validator-node polkadot[19876]:    1: std::panicking::rust_panic_with_hook
Nov 14 19:25:28 validator-node polkadot[19876]:              at src/libstd/panicking.rs:477
Nov 14 19:25:28 validator-node polkadot[19876]:    2: std::panicking::begin_panic
Nov 14 19:25:28 validator-node polkadot[19876]:    3: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
Nov 14 19:25:28 validator-node polkadot[19876]:    4: polkadot_runtime::api::dispatch
Nov 14 19:25:28 validator-node polkadot[19876]:    5: std::panicking::try::do_call
Nov 14 19:25:28 validator-node polkadot[19876]:    6: __rust_maybe_catch_panic
Nov 14 19:25:28 validator-node polkadot[19876]:              at src/libpanic_unwind/lib.rs:80
Nov 14 19:25:28 validator-node polkadot[19876]:    7: substrate_executor::native_executor::safe_call
Nov 14 19:25:28 validator-node polkadot[19876]:    8: std::thread::local::LocalKey<T>::with
Nov 14 19:25:28 validator-node polkadot[19876]:    9: <polkadot_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
Nov 14 19:25:28 validator-node polkadot[19876]:   10: std::thread::local::LocalKey<T>::with
Nov 14 19:25:28 validator-node polkadot[19876]:   11: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
Nov 14 19:25:28 validator-node polkadot[19876]:   12: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_call_with_native_else_wasm_strategy
Nov 14 19:25:28 validator-node polkadot[19876]:   13: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
Nov 14 19:25:28 validator-node polkadot[19876]:   14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
Nov 14 19:25:28 validator-node polkadot[19876]:   15: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Nov 14 19:25:28 validator-node polkadot[19876]:   16: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Nov 14 19:25:28 validator-node polkadot[19876]:   17: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Nov 14 19:25:28 validator-node polkadot[19876]:   18: substrate_consensus_common::import_queue::import_single_block
Nov 14 19:25:28 validator-node polkadot[19876]:   19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 14 19:25:28 validator-node polkadot[19876]:   20: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
Nov 14 19:25:28 validator-node polkadot[19876]:   21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 14 19:25:28 validator-node polkadot[19876]:   22: futures_executor::thread_pool::PoolState::work
Nov 14 19:25:28 validator-node polkadot[19876]:   23: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov 14 19:25:28 validator-node polkadot[19876]:   24: std::panicking::try::do_call
Nov 14 19:25:28 validator-node polkadot[19876]:   25: __rust_maybe_catch_panic
Nov 14 19:25:28 validator-node polkadot[19876]:              at src/libpanic_unwind/lib.rs:80
Nov 14 19:25:28 validator-node polkadot[19876]:   26: core::ops::function::FnOnce::call_once{{vtable.shim}}
Nov 14 19:25:28 validator-node polkadot[19876]:   27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 14 19:25:28 validator-node polkadot[19876]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Nov 14 19:25:28 validator-node polkadot[19876]:   28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 14 19:25:28 validator-node polkadot[19876]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Nov 14 19:25:28 validator-node polkadot[19876]:       std::sys_common::thread::start_thread
Nov 14 19:25:28 validator-node polkadot[19876]:              at src/libstd/sys_common/thread.rs:13
Nov 14 19:25:28 validator-node polkadot[19876]:       std::sys::unix::thread::Thread::new::thread_start
Nov 14 19:25:28 validator-node polkadot[19876]:              at src/libstd/sys/unix/thread.rs:79
Nov 14 19:25:28 validator-node polkadot[19876]:   29: start_thread
Nov 14 19:25:28 validator-node polkadot[19876]:   30: __clone
Nov 14 19:25:28 validator-node polkadot[19876]: Thread 'import-queue-worker-0' panicked at 'Transaction will be valid in the future', /home/kwunyueng/.cargo/git/checkouts/substrate-7e08433d4c370a21/aa937d9/srml/executive/src/lib.rs:242
```

It works again after restart.

**Comment by mondrak** [comment]
It was spamming the logs like crazy before we restarted it.  After restart everything seems OK.

**Comment by artkaseman** [comment]
It was filling up the logs quickly before the restart.  After the restart it was back to normal.

**Comment by crsCR** [comment]
Same on sentry

**Comment by gavofyork** [comment]
Please confirm this has happened with v0.7 series
