### ISSUE TITLE
RPC-CORE failed on weight u64 for blocks 12427880 and 12427881 on westend

### ISSUE THREAD

**Issue by arias-m** [paritytech/polkadot#6048]
Hi, running a polkadot (westend) node, the RPC call to get the data for blocks 12427880 and 12427881 is returning this error in the sidecar api:

`2022-09-23 18:23:42 error: RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Assertion failed
2022-09-23 18:23:42 error: createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Assertion failed
 Error: createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Assertion failed
    at createTypeUnsafe (/app/node_modules/@polkadot/types-create/cjs/create/type.js:73:18)
    at TypeRegistry.createTypeUnsafe (/app/node_modules/@polkadot/types/cjs/create/registry.js:353:46)
    at RpcCore._formatOutput (/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:427:21)
    at RpcCore._formatResult (/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:232:27)
    at callWithRegistry (/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:260:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)`

These 2 blocks are the only ones showing this issue.
I am running polkadot:
2022-09-23 18:53:20 Parity Polkadot
2022-09-23 18:53:20 ✌️  version 0.9.29-94078b44fb6
and sidecar-api:
2022-09-23 18:45:29 info: Version: 13.0.0

**Comment by bkchr** [comment]
CC @jacogr

**Comment by jacogr** [comment]
There was an issue in older versions, the latest deps as included in sidecar 13.1.0 addresses this, see https://github.com/paritytech/substrate-api-sidecar/releases/tag/v13.1.0

**Comment by bkchr** [comment]
Ty @jacogr. Had overseen that it was sidecar.
