### ISSUE TITLE
panicked at 'Checking inherents failed'

### ISSUE THREAD

**Issue by tugytur** [paritytech/polkadot#6063]
One of our validator is occasionally logging the following error when being active as a paravalidator:

```
✨ Imported #14634536 (0x3ab1…2d44)
panicked at 'Checking inherents failed', /home/builder/cargo/git/checkouts/cumulus-59522f43471fa161/e43b8b8/pallets/parachain-system/src/validate_block/implementation.rs:146:13
Failed to validate candidate para_id=Id(2084) error=InvalidCandidate(WorkerReportedError("execute: execute error: AbortedDueToTrap(MessageWithBacktrace { message: \"wasm trap: wasm `unreachable` instruction executed\", backtrace: Some(Backtrace { backtrace_string: \"\\n    0: 0x3aec07 - <unknown>!rust_begin_unwind\\n    1: 0x3613eb - <unknown>!core::panicking::panic_fmt::h18b15be283411c65\\n    2: 0x2fec02 - <unknown>!environmental::local_key::LocalKey<T>::with::ha807ac9b318641bd\\n    3: 0x3049f8 - <unknown>!cumulus_pallet_parachain_system::validate_block::implementation::validate_block::h90f4473e3acd5cef\\n    4: 0x2f9ad4 - <unknown>!validate_block\\n    5: 0x480283 - <unknown>!<wasm function 5123>\\n\" }) })"))
💤 Idle (50 peers), best: #14634536 (0x3ab1…2d44), finalized #14634532 (0x7863…eef9), ⬇ 1.7MiB/s ⬆ 1.2MiB/s
panicked at 'Checking inherents failed', /home/builder/cargo/git/checkouts/cumulus-59522f43471fa161/e43b8b8/pallets/parachain-system/src/validate_block/implementation.rs:146:13
Failed to validate candidate para_id=Id(2084) error=InvalidCandidate(WorkerReportedError("execute: execute error: AbortedDueToTrap(MessageWithBacktrace { message: \"wasm trap: wasm `unreachable` instruction executed\", backtrace: Some(Backtrace { backtrace_string: \"\\n    0: 0x3aec07 - <unknown>!rust_begin_unwind\\n    1: 0x3613eb - <unknown>!core::panicking::panic_fmt::h18b15be283411c65\\n    2: 0x2fec02 - <unknown>!environmental::local_key::LocalKey<T>::with::ha807ac9b318641bd\\n    3: 0x3049f8 - <unknown>!cumulus_pallet_parachain_system::validate_block::implementation::validate_block::h90f4473e3acd5cef\\n    4: 0x2f9ad4 - <unknown>!validate_block\\n    5: 0x480283 - <unknown>!<wasm function 5123>\\n\" }) })"))
💤 Idle (50 peers), best: #14634536 (0x3ab1…2d44), finalized #14634533 (0x9dfc…dd03), ⬇ 1.2MiB/s ⬆ 1.1MiB/s

```

This error doesn't seem to have any performance implications, I checked for missed blocks with turboflakes dashboard and 0 blocks were missed.

Validator is running with 0.9.29
Database is rocksdb that was synced from scratch with version 0.9.28

Here is the relevant part from systemd service:

```
ExecStart=/usr/local/bin/polkadot \
        --name "XXXX" \
        --validator \
        --state-pruning 1000 \
        --no-mdns \
        --public-addr=/ip4/XXXX/tcp/30333 \
        --listen-addr=/ip4/XXXX/tcp/30333 \
        --chain=kusama \
        --database=rocksdb \
        --prometheus-port 9615 \
        --rpc-port 9933 \
        --ws-port 9944 \
        --no-telemetry \
        --keystore-path=/var/blockchain/keystore \
        --base-path=/var/blockchain/data
```

**Comment by bkchr** [comment]
This is not your fault. We really need to disable the logging of Parachains. This log line is coming from a Parachain runtime you are validating. So, nothing to worry about.
