### ISSUE TITLE
A validator panics in libp2p-swarm

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot#6079]
```
====================

Version: 0.9.29-94078b44fb6

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   6: core::panicking::panic_display
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:72:5
   7: core::panicking::panic_str
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:56:5
   8: core::option::expect_failed
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/option.rs:1854:5
   9: libp2p_swarm::connection::pool::Pool<THandler,TTrans>::poll
  10: libp2p_swarm::Swarm<TBehaviour>::poll_next_event
  11: <sc_network::service::NetworkWorker<B,H,Client> as core::future::future::Future>::poll
  12: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: tokio::runtime::task::raw::poll
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys/unix/thread.rs:108:17
  18: start_thread
  19: clone


Thread 'tokio-runtime-worker' panicked at 'Entry in `self.pending` for previously pending connection.', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.37.0/src/connection/pool.rs:618

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

2022-09-26 07:15:57 ----------------------------
2022-09-26 07:15:57 This chain is not in any way
```
Reported by @polkalegos. According to the reporter, this happens not on startup and the validator is running in Docker on a VPS.

cc @kpp @tomaka

**Comment by polkalegos** [comment]
- Running on Docker image `v0.9.29`
- Flags: "--validator", "--name=legos-x", "--chain=kusama", "--prometheus-external", "--prometheus-port=9615", "--pruning=1000", "--telemetry-url", "wss://telemetry-backend.w3f.community/submit 1"
- Role: validator

**Comment by thomaseizinger** [comment]
Do we have any information on the uptime of this node?
