### ISSUE TITLE
Range end index 199 out of range for slice of length 64

### ISSUE THREAD

**Issue by polkalegos** [paritytech/polkadot#6092]
```
====================

Version: 0.9.29-94078b44fb6

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   6: core::slice::index::slice_end_index_len_fail_rt
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:73:5
   7: core::ops::function::FnOnce::call_once
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
   8: core::intrinsics::const_eval_select
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/intrinsics.rs:2372:5
   9: core::slice::index::slice_end_index_len_fail
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:67:9
  10: core::hash::BuildHasher::hash_one
  11: <sc_network::protocol::notifications::behaviour::Notifications as libp2p_swarm::behaviour::NetworkBehaviour>::inject_event
  12: libp2p_swarm::Swarm<TBehaviour>::poll_next_event
  13: <sc_network::service::NetworkWorker<B,H,Client> as core::future::future::Future>::poll
  14: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: tokio::runtime::task::raw::poll
  17: std::sys_common::backtrace::__rust_begin_short_backtrace
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys/unix/thread.rs:108:17
  20: start_thread
  21: clone


Thread 'tokio-runtime-worker' panicked at 'range end index 199 out of range for slice of length 64', library/core/src/slice/index.rs:73

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
```

**Comment by bkchr** [comment]
CC @dmitry-markin @altonen @kpp could one of you guys take a look at this?

**Comment by kpp** [comment]
It is sad we don't have the line number where it failed.

**Comment by dmitry-markin** [comment]
@polkalegos was it a one-off error, or there is a way to reproduce it?

**Comment by polkalegos** [comment]
@dmitry-markin I don't know. I'll check if it happens again.
