### ISSUE TITLE
Docker build using Dockerfile fails in the middle of Cargo build

### ISSUE THREAD

**Issue by klestrong** [paritytech/polkadot#6154]
I'm trying to build a docker image from source using the Dockerfile provided in your repository in `./scripts/ci/dockerfiles/polkadot/polkadot_builder.Dockerfile`.  The build is failing in the middle of "cargo build --release".

Build fail output:
```
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[2]: *** [CMakeFiles/protoc.dir/build.make:86: protoc-3.19.4.0] Error 1
  make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/protoc.dir/all] Error 2
  make: *** [Makefile:130: all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2

  build script failed, must exit now', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/core/src/panicking.rs:65:14
     2: cmake::fail
     3: cmake::run
     4: cmake::Config::build
     5: build_script_build::compile
     6: core::ops::function::FnOnce::call_once
     7: core::option::Option<T>::or_else
     8: build_script_build::protoc
     9: build_script_build::main
    10: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
The command '/bin/sh -c cargo build --release' returned a non-zero code: 101
```

I've worked past several build failures by adding support software described in the repository README.md to the Dockerfile, and by adding updated rustc in `./scripts/init.sh`.  Unfortunately I can't seem to get past the above error.  The current iteration of the Dockerfile is below, as well as my change to `./scripts/init.sh`.

polka.repo.Dockerfile `docker build -f polka.repo.Dockerfile --tag polkadot:v0.9.29 .`:
```
# This is the build stage for Polkadot. Here we create the binary in a temporary image.
FROM docker.io/paritytech/ci-linux:production as builder

WORKDIR /polkadot
COPY . /polkadot

RUN apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y cmake build-essential libclang-dev pkg-config libssl-dev git clang llvm apt-utils
RUN git checkout v0.9.29
RUN ./scripts/init.sh
RUN cargo version
RUN cargo build --release


# This is the 2nd stage: a very small image where we copy the Polkadot binary."
FROM docker.io/library/ubuntu:20.04

LABEL description="Multistage Docker image for Polkadot: a platform for web3" \
        io.parity.image.type="builder" \
        io.parity.image.authors="chevdor@gmail.com, devops-team@parity.io" \
        io.parity.image.vendor="Parity Technologies" \
        io.parity.image.description="Polkadot: a platform for web3" \
        io.parity.image.source="https://github.com/paritytech/polkadot/blob/${VCS_REF}/scripts/dockerfiles/polkadot/polkadot_builder.Dockerfile" \
        io.parity.image.documentation="https://github.com/paritytech/polkadot/"

COPY --from=builder /polkadot/target/release/polkadot /usr/local/bin

RUN useradd -m -u 1000 -U -s /bin/sh -d /polkadot polkadot && \
        mkdir -p /data /polkadot/.local/share && \
        chown -R polkadot:polkadot /data && \
        ln -s /data /polkadot/.local/share/polkadot && \
# unclutter and minimize the attack surface
        rm -rf /usr/bin /usr/sbin && \
# check if executable works in this container
        /usr/local/bin/polkadot --version

USER polkadot

EXPOSE 30333 9933 9944 9615
VOLUME ["/data"]

ENTRYPOINT ["/usr/local/bin/polkadot"]
```
init.sh:
```
#!/usr/bin/env bash

set -e

echo "*** Initializing WASM build environment"

#if [ -z $CI_PROJECT_NAME ] ; then
#   rustup update nightly
#   rustup update stable
#fi

rustup default nightly-2022-10-13
rustc --version

rustup target add wasm32-unknown-unknown --toolchain nightly

# Install wasm-gc. It's useful for stripping slimming down wasm binaries.
command -v wasm-gc || cargo +nightly install --git https://github.com/alexcrichton/wasm-gc --force
```
In case rustc version and cargo versions are important for troubleshooting, please see the version output from the build below:
```
rustc 1.66.0-nightly (c0983a9aa 2022-10-12)
cargo 1.66.0-nightly (b8f30cb23 2022-10-10)
```
```
Setting up clang (1:7.0-47) ...
Setting up g++ (4:8.3.0-1) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Setting up build-essential (12.6) ...
Setting up libclang-dev (1:7.0-47) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for libc-bin (2.28-10+deb10u1) ...
Removing intermediate container d214fa052b92
 ---> e3d50a81e455
Step 5/16 : RUN git checkout v0.9.29
 ---> Running in 4b4739b4be52
D       doc/docker.md
D       doc/release-checklist.md
D       doc/shell-completion.md
D       doc/testing.md
M       scripts/init.sh
HEAD is now at 94078b44f update weights (#5988)
Removing intermediate container 4b4739b4be52
 ---> 4299ccbef15b
Step 6/16 : RUN ./scripts/init.sh
 ---> Running in 91128d530561
*** Initializing WASM build environment
info: syncing channel updates for 'nightly-2022-10-13-x86_64-unknown-linux-gnu'
info: latest update on 2022-10-13, rust version 1.66.0-nightly (c0983a9aa 2022-10-12)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
info: installing component 'rustc'
info: default toolchain set to 'nightly-2022-10-13-x86_64-unknown-linux-gnu'

  nightly-2022-10-13-x86_64-unknown-linux-gnu installed - rustc 1.66.0-nightly (c0983a9aa 2022-10-12)

rustc 1.66.0-nightly (c0983a9aa 2022-10-12)
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
/usr/local/cargo/bin/wasm-gc
Removing intermediate container 91128d530561
 ---> 5c27ba842807
Step 7/16 : RUN cargo version
 ---> Running in e01ebaff044e
cargo 1.66.0-nightly (b8f30cb23 2022-10-10)
Removing intermediate container e01ebaff044e
 ---> 2958dc73b6a3
Step 8/16 : RUN cargo build --release
 ---> Running in 12a12149c2ae
    Updating git repository `https://github.com/paritytech/substrate`
    Updating crates.io index
```
Any idea what I'm missing or doing wrong?

**Comment by bkchr** [comment]
@paritytech-ci do we use this image for anything?

**Comment by klestrong** [comment]
Yes.  I use it to launch my RPC.

**Comment by bkchr** [comment]
@klestrong I did not mean you. However, I see that probably `protoc` is missing as package. Add it to the package that are being installed.

**Comment by klestrong** [comment]
Haha... thanks for the help.  I figured that after my reply, but felt it was pointless to remove it.

I tried installing it as a package in the same way the other packages are installed with apt-get (error output below), but there doesn't seem to be a package available.  I'll try to figure it out and let you know how it goes.

Error output for `apt-get install -y protoc`:
```
Processing triggers for libc-bin (2.28-10+deb10u1) ...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package protoc
The command '/bin/sh -c apt-get update &&         apt-get upgrade -y &&         apt-get install -y cmake build-essential libclang-dev pkg-config libssl-dev git clang llvm apt-utils protoc' returned a non-zero code: 100
```

**Comment by klestrong** [comment]
Since the package is built on Paritytech's image (ci-linux), do you already know the command I would need to put into the Dockerfile for installing `protoc`?

**Comment by klestrong** [comment]
I added `protobuf-compiler` to the packages to be installed during the build on Dockerfile, but got a pretty bad fail on the build.

Added to Dockerfile:
```
RUN apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y cmake build-essential libclang-dev pkg-config libssl-dev git clang llvm apt-utils protobuf-compiler
RUN protoc --version
```

Output indicating `protoc` version:
```
Step 5/17 : RUN protoc --version
 ---> Running in 825f1e03717c
libprotoc 3.6.1
```
```
Processing triggers for mime-support (3.62) ...
Processing triggers for libc-bin (2.28-10+deb10u1) ...
Removing intermediate container 5d6dae16dc2d
 ---> 284234d0d6ef
Step 5/17 : RUN protoc --version
 ---> Running in 825f1e03717c
libprotoc 3.6.1
Removing intermediate container 825f1e03717c
 ---> d727ca7b9446
Step 6/17 : RUN git checkout v0.9.29
 ---> Running in dae26b8bb708
HEAD is now at 94078b44f update weights (#5988)
D       doc/docker.md
D       doc/release-checklist.md
D       doc/shell-completion.md
D       doc/testing.md
M       scripts/init.sh
Removing intermediate container dae26b8bb708
 ---> 8a740a4003e5
Step 7/17 : RUN ./scripts/init.sh
 ---> Running in e9c5e32e8b7a
*** Initializing WASM build environment
info: syncing channel updates for 'nightly-2022-10-13-x86_64-unknown-linux-gnu'
info: latest update on 2022-10-13, rust version 1.66.0-nightly (c0983a9aa 2022-10-12)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
```

Build fail error:
```
   Compiling kusama-runtime v0.9.29 (/polkadot/runtime/kusama)
   Compiling polkadot-runtime v0.9.29 (/polkadot/runtime/polkadot)
   Compiling westend-runtime v0.9.29 (/polkadot/runtime/westend)
   Compiling rococo-runtime v0.9.29 (/polkadot/runtime/rococo)
error: failed to run custom build command for `kusama-runtime v0.9.29 (/polkadot/runtime/kusama)`

Caused by:
  process didn't exit successfully: `/polkadot/target/release/build/kusama-runtime-51120bb8293669ae/build-script-build` (exit status: 1)
  --- stderr
  Rust WASM toolchain not installed, please install it!

  Further error information:
  ------------------------------------------------------------
     Compiling wasm-test v1.0.0 (/tmp/.tmpLLaCsP)
  error[E0463]: can't find crate for `std`
    |
    = note: the `wasm32-unknown-unknown` target may not be installed
    = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`
    = help: consider building the standard library from source with `cargo build -Zbuild-std`

  error: cannot find macro `println` in this scope
   --> src/main.rs:3:5
    |
  3 |                 println!("{}", env!("RUSTC_VERSION"));
    |                 ^^^^^^^

  error: requires `sized` lang_item

  For more information about this error, try `rustc --explain E0463`.
  error: could not compile `wasm-test` due to 3 previous errors
  ------------------------------------------------------------

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `westend-runtime v0.9.29 (/polkadot/runtime/westend)`

Caused by:
  process didn't exit successfully: `/polkadot/target/release/build/westend-runtime-edee3a52a1423dc0/build-script-build` (exit status: 1)
  --- stderr
  Rust WASM toolchain not installed, please install it!

  Further error information:
  ------------------------------------------------------------
     Compiling wasm-test v1.0.0 (/tmp/.tmpeZlVdO)
  error[E0463]: can't find crate for `std`
    |
    = note: the `wasm32-unknown-unknown` target may not be installed
    = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`
    = help: consider building the standard library from source with `cargo build -Zbuild-std`

  error: cannot find macro `println` in this scope
   --> src/main.rs:3:5
    |
  3 |                 println!("{}", env!("RUSTC_VERSION"));
    |                 ^^^^^^^

  error: requires `sized` lang_item

  For more information about this error, try `rustc --explain E0463`.
  error: could not compile `wasm-test` due to 3 previous errors
  ------------------------------------------------------------

error: failed to run custom build command for `rococo-runtime v0.9.29 (/polkadot/runtime/rococo)`

Caused by:
  process didn't exit successfully: `/polkadot/target/release/build/rococo-runtime-0a02125dcaaabdb9/build-script-build` (exit status: 1)
  --- stderr
  Rust WASM toolchain not installed, please install it!

  Further error information:
  ------------------------------------------------------------
     Compiling wasm-test v1.0.0 (/tmp/.tmpUNa1zd)
  error[E0463]: can't find crate for `std`
    |
    = note: the `wasm32-unknown-unknown` target may not be installed
    = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`
    = help: consider building the standard library from source with `cargo build -Zbuild-std`

  error: cannot find macro `println` in this scope
   --> src/main.rs:3:5
    |
  3 |                 println!("{}", env!("RUSTC_VERSION"));
    |                 ^^^^^^^

  error: requires `sized` lang_item

  For more information about this error, try `rustc --explain E0463`.
  error: could not compile `wasm-test` due to 3 previous errors
  ------------------------------------------------------------

The command '/bin/sh -c cargo build --release' returned a non-zero code: 101
```

**Comment by ordian** [comment]
> Rust WASM toolchain not installed, please install it!

`rustup target add wasm32-unknown-unknown --toolchain nightly`

**Comment by klestrong** [comment]
Thanks, but I don't think that's the issue.  I'm installing WASM using your script `./scripts/init.sh` described in your repo READ.me (https://github.com/paritytech/polkadot).  It's indicated as successfully initialized in the same comment (https://github.com/paritytech/polkadot/issues/6154#issuecomment-1278611823) with the error.

WASM installed:
```
Step 7/17 : RUN ./scripts/init.sh
 ---> Running in e9c5e32e8b7a
*** Initializing WASM build environment
info: syncing channel updates for 'nightly-2022-10-13-x86_64-unknown-linux-gnu'
info: latest update on 2022-10-13, rust version 1.66.0-nightly (c0983a9aa 2022-10-12)
```

**Comment by klestrong** [comment]
@bkchr Since you indicated I was missing protoc, could I get an updated list of packages that need to be installed for the build to work?  I included protoc and demonstrated WASM environment is installed, but cargo build still fails as indicated in my comment (https://github.com/paritytech/polkadot/issues/6154#issuecomment-1278611823).  Below are the packages I'm installing, the script for the WASM environment and my Dockerfile.

Packages installed:
```
RUN apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y cmake build-essential libclang-dev pkg-config libssl-dev git clang llvm apt-utils
RUN apt-get install -y protobuf-compiler
```

init.sh for WASM environment:
```
#!/usr/bin/env bash

set -e

echo "*** Initializing WASM build environment"

#if [ -z $CI_PROJECT_NAME ] ; then
#   rustup update nightly
#   rustup update stable
#fi

rustup default nightly-2022-10-13
rustc --version

rustup target add wasm32-unknown-unknown --toolchain nightly

# Install wasm-gc. It's useful for stripping slimming down wasm binaries.
command -v wasm-gc || cargo +nightly install --git https://github.com/alexcrichton/wasm-gc --force
```

Dockerfile:
```
# This is the build stage for Polkadot. Here we create the binary in a temporary image.
FROM docker.io/paritytech/ci-linux:production as builder

WORKDIR /polkadot
COPY . /polkadot

RUN apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y cmake build-essential libclang-dev pkg-config libssl-dev git clang llvm apt-utils
RUN apt-get install -y protobuf-compiler
RUN protoc --version
RUN git checkout v0.9.29
RUN ./scripts/init.sh
RUN cargo version
RUN cargo build --release


# This is the 2nd stage: a very small image where we copy the Polkadot binary."
FROM docker.io/library/ubuntu:20.04

LABEL description="Multistage Docker image for Polkadot: a platform for web3" \
        io.parity.image.type="builder" \
        io.parity.image.authors="chevdor@gmail.com, devops-team@parity.io" \
        io.parity.image.vendor="Parity Technologies" \
        io.parity.image.description="Polkadot: a platform for web3" \
        io.parity.image.source="https://github.com/paritytech/polkadot/blob/${VCS_REF}/scripts/dockerfiles/polkadot/polkadot_builder.Dockerfile" \
        io.parity.image.documentation="https://github.com/paritytech/polkadot/"

COPY --from=builder /polkadot/target/release/polkadot /usr/local/bin

RUN useradd -m -u 1000 -U -s /bin/sh -d /polkadot polkadot && \
        mkdir -p /data /polkadot/.local/share && \
        chown -R polkadot:polkadot /data && \
        ln -s /data /polkadot/.local/share/polkadot && \
# unclutter and minimize the attack surface
        rm -rf /usr/bin /usr/sbin && \
# check if executable works in this container
        /usr/local/bin/polkadot --version

USER polkadot

EXPOSE 30333 9933 9944 9615
VOLUME ["/data"]

ENTRYPOINT ["/usr/local/bin/polkadot"]
```

**Comment by bkchr** [comment]
I just tried this dockerfile:
```
# This is the build stage for Polkadot. Here we create the binary in a temporary image.
FROM docker.io/paritytech/ci-linux:production as builder

WORKDIR /polkadot
COPY . /polkadot

RUN protoc --version
RUN git checkout v0.9.29
RUN cargo version
RUN cargo build --release


# This is the 2nd stage: a very small image where we copy the Polkadot binary."
FROM docker.io/library/ubuntu:20.04

LABEL description="Multistage Docker image for Polkadot: a platform for web3" \
        io.parity.image.type="builder" \
        io.parity.image.authors="chevdor@gmail.com, devops-team@parity.io" \
        io.parity.image.vendor="Parity Technologies" \
        io.parity.image.description="Polkadot: a platform for web3" \
        io.parity.image.source="https://github.com/paritytech/polkadot/blob/${VCS_REF}/scripts/dockerfiles/polkadot/polkadot_builder.Dockerfile" \
        io.parity.image.documentation="https://github.com/paritytech/polkadot/"

COPY --from=builder /polkadot/target/release/polkadot /usr/local/bin

RUN useradd -m -u 1000 -U -s /bin/sh -d /polkadot polkadot && \
        mkdir -p /data /polkadot/.local/share && \
        chown -R polkadot:polkadot /data && \
        ln -s /data /polkadot/.local/share/polkadot && \
# unclutter and minimize the attack surface
        rm -rf /usr/bin /usr/sbin && \
# check if executable works in this container
        /usr/local/bin/polkadot --version

USER polkadot

EXPOSE 30333 9933 9944 9615
VOLUME ["/data"]

ENTRYPOINT ["/usr/local/bin/polkadot"]
```

Maybe you need to pull a newer `ci-linux:production` image.

**Comment by klestrong** [comment]
Thanks @bkchr, that did the trick.  I see you guys did a commit for ci-linux:production on Aug 23, 2022 that I had missed.  My build is now successful.
