### ISSUE TITLE
Validator Errors Unexpectedly

### ISSUE THREAD

**Issue by jack-kearney** [paritytech/polkadot#635]
This is from a Kusama validator that was live in the first PoS era of CC3. The `session_setKeys` RPC call was not called for this validator so it was kicked out of the active set at the start of the second era. Shortly after that era began, I started to repeatedly see this stack trace.

System: Ubuntu-18.04, 4 CPUs, 15 GB memory

```
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]: ====================
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]: Version: 0.7.0-5598ed9b-x86_64-linux-gnu
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]: stack backtrace:
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:    0: substrate_panic_handler::set::{{closure}}
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:    1: std::panicking::rust_panic_with_hook
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:              at src/libstd/panicking.rs:477
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:    2: std::panicking::continue_panic_fmt
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:              at src/libstd/panicking.rs:380
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:    3: rust_begin_unwind
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:              at src/libstd/panicking.rs:307
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:    4: core::panicking::panic_fmt
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:              at src/libcore/panicking.rs:85
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:    5: core::slice::slice_index_len_fail
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:              at src/libcore/slice/mod.rs:2585
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:    6: <substrate_keystore::Store as substrate_primitives::traits::BareCryptoStore>::sr25519_public_keys
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:    7: <&mut dyn substrate_externalities::Externalities as sr_io::crypto::Crypto>::sr25519_public_keys
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:    8: std::thread::local::LocalKey<T>::with
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:    9: <<sr_io::crypto::HostFunctions as substrate_wasm_interface::HostFunctions>::host_functions::ExtCryptoSr25519PublicKeysVersion1 as substrate_wasm_interface::Function>::execute
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   10: <substrate_executor::wasmi_execution::FunctionExecutor as wasmi::host::Externals>::invoke_index
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   11: wasmi::func::FuncInstance::invoke
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   12: wasmi::runner::Interpreter::start_execution
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   13: wasmi::func::FuncInstance::invoke
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   14: std::thread::local::LocalKey<T>::with
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   15: <substrate_executor::wasmi_execution::WasmiRuntime as substrate_executor::wasm_runtime::WasmRuntime>::call
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   16: std::panicking::try::do_call
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   17: __rust_maybe_catch_panic
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:              at src/libpanic_unwind/lib.rs:80
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   18: substrate_executor::native_executor::safe_call
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   19: std::thread::local::LocalKey<T>::with
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   20: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   21: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   22: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client_api::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   23: <substrate_client::client::Client<B,E,Block,RA> as sr_api::CallRuntimeAt<Block>>::call_api_at
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   24: substrate_offchain_primitives::runtime_decl_for_OffchainWorkerApi::offchain_worker_call_api_at
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   25: substrate_offchain_primitives::OffchainWorkerApi::offchain_worker_with_context
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   26: <F as threadpool::FnBox>::call_box
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   27: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   28: __rust_maybe_catch_panic
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:              at src/libpanic_unwind/lib.rs:80
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   29: core::ops::function::FnOnce::call_once{{vtable.shim}}
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   30: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   31: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:       std::sys_common::thread::start_thread
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:              at src/libstd/sys_common/thread.rs:13
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:       std::sys::unix::thread::Thread::new::thread_start
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:              at src/libstd/sys/unix/thread.rs:79
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   32: start_thread
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]:   33: __clone
Nov 30 19:10:25 kusama-validator-02 polkadot-client[1134]: Thread '<unnamed>' panicked at 'index 4 out of range for slice of length 2', src/libcore/slice/mod.rs:2585
```

**Comment by bkchr** [comment]
Thanks for the report, will be fixed!

However, please make sure to run your node in `release` mode!

**Comment by jack-kearney** [comment]
Hey - The client being run here was compiled using the `--release` flag. Hope that provides some more context here!

**Comment by bkchr** [comment]
Ahh, I thought that this is a debug only check. Then nevermind, but the bug is fixed!
