### ISSUE TITLE
Externalities not allowed to fail within runtime

### ISSUE THREAD

**Issue by tugytur** [paritytech/polkadot#6370]
After upgrading to 0.9.33 yesterday we saw the following error for the first time on one of our Valdiators.
The Server never had any issues so far and at the time of the error the Validator was not in the active set.

```
✨ Imported #15541558 (0x3df8…fb5d)
====================
Version: 0.9.33-c7d6c21242f
   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   6: core::result::unwrap_failed
             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
   7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
   8: sp_io::storage::get_version_1
   9: sp_io::storage::ExtStorageGetVersion1::call
  10: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: wasmtime_runtime::traphandlers::catch_traps::call_closure
  16: wasmtime_setjmp
  17: sc_executor_wasmtime::runtime::perform_call
  18: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
  19: sc_executor_common::wasm_runtime::WasmInstance::call_export
  20: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  21: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
  22: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  23: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
  24: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  25: <kusama_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::__runtime_api_internal_call_api_at
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: polkadot_node_core_runtime_api::make_runtime_api_request::{{closure}}
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  29: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  30: tokio::runtime::task::raw::poll
  31: std::sys_common::backtrace::__rust_begin_short_backtrace
  32: core::ops::function::FnOnce::call_once{{vtable.shim}}
  33: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
  34: start_thread
  35: clone
Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x774e87c6d9c62681dcf5f50c91929a318e152fa4528355b6518e9246ef54359d"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/2dff067/primitives/state-machine/src/ext.rs:189
This is a bug. Please report it at:
        https://github.com/paritytech/polkadot/issues/new
```

We use the binary provided by parity.

Here are the parameters used for the validator:
```
ExecStart=/usr/local/bin/polkadot \
        --name "Amforc AG 4" \
        --validator \
        --state-pruning 1000 \
        --no-mdns \
        --public-addr=/ip4/X.X.X.X/tcp/30333 \
        --listen-addr=/ip4/X.X.X.X/tcp/30333 \
        --chain=kusama \
        --database=rocksdb \
        --prometheus-port 9615 \
        --rpc-port 9933 \
        --ws-port 9944 \
        --telemetry-url 'wss://telemetry-backend.w3f.community/submit 1' \
        --keystore-path=/var/blockchain/keystore \
        --base-path=/var/blockchain/data
```

**Comment by bkchr** [comment]
Probably the database got corrupted somehow.
