### ISSUE TITLE
Validator Crashed - Trie lookup error: Invalid state root

### ISSUE THREAD

**Issue by paradox-tt** [paritytech/polkadot#6389]
Hi guys,

One of my active validators on Kusama just crashed but recovered with an automated systemd restart.  An excerpt of the logs are attached and the error is as follows:

```
Dec 05 09:57:56 ns3219400 polkadot[364314]: ====================
Dec 05 09:57:56 ns3219400 polkadot[364314]: Version: 0.9.33-c7d6c21242f
Dec 05 09:57:56 ns3219400 polkadot[364314]:    0: sp_panic_handler::set::{{closure}}
Dec 05 09:57:56 ns3219400 polkadot[364314]:    1: std::panicking::rust_panic_with_hook
Dec 05 09:57:56 ns3219400 polkadot[364314]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
Dec 05 09:57:56 ns3219400 polkadot[364314]:    2: std::panicking::begin_panic_handler::{{closure}}
Dec 05 09:57:56 ns3219400 polkadot[364314]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
Dec 05 09:57:56 ns3219400 polkadot[364314]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Dec 05 09:57:56 ns3219400 polkadot[364314]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
Dec 05 09:57:56 ns3219400 polkadot[364314]:    4: rust_begin_unwind
Dec 05 09:57:56 ns3219400 polkadot[364314]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
Dec 05 09:57:56 ns3219400 polkadot[364314]:    5: core::panicking::panic_fmt
Dec 05 09:57:56 ns3219400 polkadot[364314]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
Dec 05 09:57:56 ns3219400 polkadot[364314]:    6: core::result::unwrap_failed
Dec 05 09:57:56 ns3219400 polkadot[364314]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
Dec 05 09:57:56 ns3219400 polkadot[364314]:    7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
Dec 05 09:57:56 ns3219400 polkadot[364314]:    8: sp_io::storage::get_version_1
Dec 05 09:57:56 ns3219400 polkadot[364314]:    9: sp_io::storage::ExtStorageGetVersion1::call
Dec 05 09:57:56 ns3219400 polkadot[364314]:   10: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
Dec 05 09:57:56 ns3219400 polkadot[364314]:   11: <unknown>
Dec 05 09:57:56 ns3219400 polkadot[364314]:   12: <unknown>
Dec 05 09:57:56 ns3219400 polkadot[364314]:   13: <unknown>
Dec 05 09:57:56 ns3219400 polkadot[364314]:   14: <unknown>
Dec 05 09:57:56 ns3219400 polkadot[364314]:   15: wasmtime_runtime::traphandlers::catch_traps::call_closure
Dec 05 09:57:56 ns3219400 polkadot[364314]:   16: wasmtime_setjmp
Dec 05 09:57:56 ns3219400 polkadot[364314]:   17: sc_executor_wasmtime::runtime::perform_call
Dec 05 09:57:56 ns3219400 polkadot[364314]:   18: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
Dec 05 09:57:56 ns3219400 polkadot[364314]:   19: sc_executor_common::wasm_runtime::WasmInstance::call_export
Dec 05 09:57:56 ns3219400 polkadot[364314]:   20: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
Dec 05 09:57:56 ns3219400 polkadot[364314]:   21: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
Dec 05 09:57:56 ns3219400 polkadot[364314]:   22: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
Dec 05 09:57:56 ns3219400 polkadot[364314]:   23: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
Dec 05 09:57:56 ns3219400 polkadot[364314]:   24: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Dec 05 09:57:56 ns3219400 polkadot[364314]:   25: <kusama_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::__runtime_api_internal_call_api_at
Dec 05 09:57:56 ns3219400 polkadot[364314]:   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Dec 05 09:57:56 ns3219400 polkadot[364314]:   27: polkadot_node_core_runtime_api::make_runtime_api_request::{{closure}}
Dec 05 09:57:56 ns3219400 polkadot[364314]:   28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Dec 05 09:57:56 ns3219400 polkadot[364314]:   29: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Dec 05 09:57:56 ns3219400 polkadot[364314]:   30: tokio::runtime::task::raw::poll
Dec 05 09:57:56 ns3219400 polkadot[364314]:   31: std::sys_common::backtrace::__rust_begin_short_backtrace
Dec 05 09:57:56 ns3219400 polkadot[364314]:   32: core::ops::function::FnOnce::call_once{{vtable.shim}}
Dec 05 09:57:56 ns3219400 polkadot[364314]:   33: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Dec 05 09:57:56 ns3219400 polkadot[364314]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
Dec 05 09:57:56 ns3219400 polkadot[364314]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Dec 05 09:57:56 ns3219400 polkadot[364314]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
Dec 05 09:57:56 ns3219400 polkadot[364314]:       std::sys::unix::thread::Thread::new::thread_start
Dec 05 09:57:56 ns3219400 polkadot[364314]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
Dec 05 09:57:56 ns3219400 polkadot[364314]:   34: start_thread
Dec 05 09:57:56 ns3219400 polkadot[364314]:   35: clone
Dec 05 09:57:56 ns3219400 polkadot[364314]: Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "[issue.log](https://github.com/paritytech/polkadot/files/10153102/issue.log) 0xe9b93786c09cbad03ccc07734defa99b81085679961a78400f0fd4983be4051c"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/2dff067/primitives/state-machine/src/ext.rs:189
Dec 05 09:57:56 ns3219400 polkadot[364314]: This is a bug. Please report it at:
Dec 05 09:57:56 ns3219400 polkadot[364314]:         https://github.com/paritytech/polkadot/issues/new
Dec 05 09:57:56 ns3219400 polkadot[364314]: 2022-12-05 09:57:56 âœ¨ Imported #15623986 (0x4d53â€¦4051)
Dec 05 09:57:57 ns3219400 systemd[1]: kusama1.service: Main process exited, code=exited, status=1/FAILURE
Dec 05 09:57:57 ns3219400 systemd[1]: kusama1.service: Failed with result 'exit-code'.

```

**Comment by bkchr** [comment]
So it crashed and then you have seen this error? Or it crashed with the given error?

Do you use ParityDB or Rocksdb?

**Comment by paradox-tt** [comment]
It crashed given the error, I discovered the error after being alerted that the service was momentarily offline.

I use Rocksdb, my flags are below with my IP redacted. 

```
[Unit]
Description=Kusama Node

[Service]
User=polkadota
Group=polkadota
ExecStart=/usr/local/bin/polkadot \
  --name Dox-KSM-11 \
  --validator \
  --public-addr=/XXX \
  --listen-addr=/XXX \
  --rpc-methods=Unsafe \
  -lsync=warn,afg=warn,babe=warn \
  --chain=kusama \
  --pruning=1000 \
  --prometheus-port=9701 \
  --telemetry-url 'wss://telemetry-backend.w3f.community/submit/ 1' \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 1' \
  --rpc-port=9931

Restart=always
RestartSec=60

[Install]
WantedBy=multi-user.target

```

**Comment by bkchr** [comment]
Okay and after the restart you got the same error again?

**Comment by paradox-tt** [comment]
After the restart there's no error and all appears to be in working order.  I created the issue because it was an unusual occurance and the advice that : `This is a bug. Please report it at: https://github.com/paritytech/polkadot/issues/new`

**Comment by bkchr** [comment]
Okay, thank you for the report. This should be duplicate of: https://github.com/paritytech/polkadot/issues/6377
