### ISSUE TITLE
Synchronization error

### ISSUE THREAD

**Issue by ERNcrypto** [paritytech/polkadot#6436]
54: core::ops::function::FnOnce::call_once{{vtable.shim}}
  55: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/alloc/src/boxed.rs:1940:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/alloc/src/boxed.rs:1940:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys/unix/thread.rs:108:17
  56: <unknown>
  57: <unknown>

Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x78aae5de4253ed2a66256f5e710cd83c0e1420af60df449ca7c83bd375e5ecfb"', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/2a0eeff/primitives/state-machine/src/ext.rs:189

This is a bug. Please report it at:

https://github.com/paritytech/polkadot/issues/new

**Comment by bkchr** [comment]
Duplicate of: https://github.com/paritytech/polkadot/issues/6377
