### ISSUE TITLE
Kusama

### ISSUE THREAD

**Issue by ERNcrypto** [paritytech/polkadot#6705]
Node steadily shuts down every 1-3 hours, works after a reboot, but then it happens again. I get three different errors. Node fully synchronised, version 0.9.37 

1) 
6: core::panicking::panic
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:114:5
   7: futures_channel::mpsc::queue::Queue<T>::pop_spin
   8: futures_channel::mpsc::UnboundedReceiver<T>::next_message
   9: <futures_channel::mpsc::UnboundedReceiver<T> as futures_core::stream::Stream>::poll_next
  10: <sc_utils::mpsc::inner::TracingUnboundedReceiver<T> as futures_core::stream::Stream>::poll_next
  11: <sc_peerset::Peerset as futures_core::stream::Stream>::poll_next
  12: <sc_network::protocol::notifications::behaviour::Notifications as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  13: <sc_network::protocol::Protocol<B,Client> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  14: <sc_network::behaviour::Behaviour<B,Client> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  15: libp2p_swarm::Swarm<TBehaviour>::poll_next_event
  16: <sc_network::service::NetworkWorker<B,H,Client> as core::future::future::Future>::poll
  17: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  18: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  21: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  22: tokio::runtime::context::BlockingRegionGuard::block_on
  23: tokio::runtime::handle::Handle::block_on
  24: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  25: std::panicking::try
  26: tokio::runtime::task::harness::Harness<T,S>::poll
  27: tokio::runtime::blocking::pool::Inner::run
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys/unix/thread.rs:108:17
  31: <unknown>
  32: <unknown>

Thread 'tokio-runtime-worker' panicked at 'assertion failed: (*tail).value.is_none()', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.25/src/mpsc/queue.rs:123

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

2) 

2023-02-13 07:14:54 ?? Imported #16614415 (0xd560??c20a)
2023-02-13 07:14:54 ?? Imported #16614415 (0xdb57??4651)
2023-02-13 07:14:54 cannot query the runtime API version: UnknownBlock: State already discarded for 0xc435a5718c2d5904d7ca4c1c19832ab0abf15b3c75a25e237e4f8851b9ea8c2d
2023-02-13 07:14:54 cannot query the runtime API version: UnknownBlock: State already discarded for 0xc435a5718c2d5904d7ca4c1c19832ab0abf15b3c75a25e237e4f8851b9ea8c2d
2023-02-13 07:14:58 ?? Idle (40 peers), best: #16614415 (0xd560??c20a), finalized #16614412 (0xfdc9??0306), ?? 809.9kiB/s ?? 1.6MiB/s
2023-02-13 07:14:59 cannot query the runtime API version: UnknownBlock: State already discarded for 0xc435a5718c2d5904d7ca4c1c19832ab0abf15b3c75a25e237e4f8851b9ea8c2d
2023-02-13 07:15:00 ?? Imported #16614416 (0x8ea2??4368)
2023-02-13 07:15:00 cannot query the runtime API version: UnknownBlock: State already discarded for 0xc435a5718c2d5904d7ca4c1c19832ab0abf15b3c75a25e237e4f8851b9ea8c2d
2023-02-13 07:15:03 ?? Idle (40 peers), best: #16614416 (0x8ea2??4368), finalized #16614414 (0x0afd??b151), ?? 1.1MiB/s ?? 1.8MiB/s
2023-02-13 07:15:03 cannot query the runtime API version: UnknownBlock: State already discarded for 0xc435a5718c2d5904d7ca4c1c19832ab0abf15b3c75a25e237e4f8851b9ea8c2d
Segmentation fault

3) 

2023-02-13 09:44:12 ????  Reorg on #16615906,0x4983??f682 to #16615906,0xf9f9??2431, common ancestor #16615905,0x67d0??f65f
2023-02-13 09:44:12 ?? Imported #16615906 (0xf9f9??2431) 
2023-02-13 09:44:12 ?? Imported #16615906 (0xafc8??1ecf) 
2023-02-13 09:44:15 ?? Idle (40 peers), best: #16615906 (0xf9f9??2431), finalized #16615903 (0xa03a??3c68), ?? 1.1MiB/s ?? 1.1MiB/s
2023-02-13 09:44:17 Essential task basic-block-import-worker failed. Shutting down service.
Error:
   0: Other: Essential task failed.

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by bkchr** [comment]
Looks like your main memory is broken. Please check it.

**Comment by ERNcrypto** [comment]
> Looks like your main memory is broken. Please check it.

Do you mean RAM? I don't think there's any problem with that

**Comment by bkchr** [comment]
Yes I mean the RAM. Can you please check it?

**Comment by bkchr** [comment]
What you want to tell me?

**Comment by ggwpez** [comment]
Yes please run this https://www.memtest86.com/ or similar.   
Multiple obscure errors in the past stemmed from silently broken RAM. There are no indications for this besides random program crashes.

**Comment by ERNcrypto** [comment]
Resolved

**Comment by chengjiao** [comment]
@ERNcrypto hello, I hit this error for now. how was it resovled? any sharing? The RAM used is 50%, I am using aws ec2.

**Comment by ERNcrypto** [comment]
> @ERNcrypto hello, I hit this error for now. how was it resovled? any sharing? The RAM used is 50%, I am using aws ec2.

Version?
