### ISSUE TITLE
Panic when running Polkadot:v0.9.43 in docker

### ISSUE THREAD

**Issue by aramikm** [paritytech/polkadot#7629]
# Description
After running polkadot docker image for [parity/polkadot:v0.9.43](https://github.com/paritytech/polkadot/issues/new#) and after para-chain connection I'm seeing the following error.

```
2023-08-15 17:19:30 2023-08-16 00:19:30.806  INFO tokio-runtime-worker substrate: 💤 Idle (1 peers), best: #5 (0xc2c4…be06), finalized #2 (0x76ec…837b), ⬇ 0.4kiB/s ⬆ 0.5kiB/s    
2023-08-15 17:19:31 
2023-08-15 17:19:31 ====================
2023-08-15 17:19:31 
2023-08-15 17:19:31 Version: 0.9.43-ba42b9ce51d
2023-08-15 17:19:31 
2023-08-15 17:19:31    0: sp_panic_handler::set::{{closure}}
2023-08-15 17:19:31    1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
2023-08-15 17:19:31              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9
2023-08-15 17:19:31       std::panicking::rust_panic_with_hook
2023-08-15 17:19:31              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13
2023-08-15 17:19:31    2: std::panicking::begin_panic_handler::{{closure}}
2023-08-15 17:19:31              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
2023-08-15 17:19:31    3: std::sys_common::backtrace::__rust_end_short_backtrace
2023-08-15 17:19:31              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
2023-08-15 17:19:31    4: rust_begin_unwind
2023-08-15 17:19:31              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
2023-08-15 17:19:31    5: core::panicking::panic_fmt
2023-08-15 17:19:31              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
2023-08-15 17:19:31    6: core::panicking::panic_display
2023-08-15 17:19:31    7: core::panicking::panic_str
2023-08-15 17:19:31              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:131:5
2023-08-15 17:19:31    8: core::option::expect_failed
2023-08-15 17:19:31              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/option.rs:2045:5
2023-08-15 17:19:31    9: wasmtime_runtime::libcalls::trampolines::impl_table_get_lazy_init_funcref
2023-08-15 17:19:31   10: <unknown>
2023-08-15 17:19:31   11: <unknown>
2023-08-15 17:19:31   12: <unknown>
2023-08-15 17:19:31   13: <unknown>
2023-08-15 17:19:31   14: <unknown>
2023-08-15 17:19:31   15: wasmtime_runtime::traphandlers::catch_traps::call_closure
2023-08-15 17:19:31   16: wasmtime_setjmp
2023-08-15 17:19:31   17: sc_executor_wasmtime::runtime::perform_call
2023-08-15 17:19:31   18: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
2023-08-15 17:19:31   19: sc_executor_common::wasm_runtime::WasmInstance::call_export
2023-08-15 17:19:31   20: sc_executor::executor::WasmExecutor<H>::with_instance::{{closure}}
2023-08-15 17:19:31   21: <sc_executor::executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
2023-08-15 17:19:31   22: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
2023-08-15 17:19:31   23: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
2023-08-15 17:19:31   24: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
2023-08-15 17:19:31   25: <rococo_runtime::RuntimeApiImpl<__SrApiBlock__,RuntimeApiImplCall> as sp_api::Core<__SrApiBlock__>>::__runtime_api_internal_call_api_at
2023-08-15 17:19:31   26: <F as threadpool::FnBox>::call_box
2023-08-15 17:19:31   27: std::sys_common::backtrace::__rust_begin_short_backtrace
2023-08-15 17:19:31   28: core::ops::function::FnOnce::call_once{{vtable.shim}}
2023-08-15 17:19:31   29: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2023-08-15 17:19:31              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
2023-08-15 17:19:31       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2023-08-15 17:19:31              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
2023-08-15 17:19:31       std::sys::unix::thread::Thread::new::thread_start
2023-08-15 17:19:31              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/thread.rs:108:17
2023-08-15 17:19:31   30: start_thread
2023-08-15 17:19:31   31: clone
2023-08-15 17:19:31 
2023-08-15 17:19:31 
2023-08-15 17:19:31 Thread 'offchain-worker' panicked at 'table access already bounds-checked', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-runtime-8.0.1/src/libcalls.rs:381
2023-08-15 17:19:31 
2023-08-15 17:19:31 This is a bug. Please report it at:
2023-08-15 17:19:31 
2023-08-15 17:19:31     https://github.com/paritytech/polkadot/issues/new

```

I've attached a more detailed log file.
[parity_error.log](https://github.com/paritytech/polkadot/files/12353902/parity_error.log)

**Comment by bkchr** [comment]
Please try the latest release.

**Comment by bkchr** [comment]
And are you sure that this isn't any hardware failure?

**Comment by aramikm** [comment]
Hard to tell if it's a hardware issue but if the direction is to use the latest version then I'm going to close this.
